import { useCallback, useEffect, useRef, useState } from 'react'
import { api } from '../../core/auth/api.js'
import { useUnsavedChanges } from '../../core/navigation/Navigation.jsx'
import { Button } from '../../core/ui/Button.jsx'
import { Dialog } from '../../core/ui/Dialog.jsx'
import { FormField } from '../../core/ui/FormField.jsx'
import { DateField } from '../../core/ui/DateField.jsx'
import { ReferenceField } from '../../core/ui/ReferenceField.jsx'
import { SelectField } from '../../core/ui/SelectField.jsx'
import { TextAreaField } from '../../core/ui/TextAreaField.jsx'
import { bookingQuote } from '../../../../../packages/contracts/booking-plan.js'

const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const date=value=>value?.slice(0,10)||''
const money=value=>value==null?'Not configured':`${Number(value).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2})} THB`
const message=e=>e.detail||`${e.message.replaceAll('_',' ')}. Your entries are preserved.`
const terms={UNSET:'Not specified',PREPAID:'Pay before service',PAID:'Already paid',COUNTER:'Pay on service day',AGENT_CREDIT:'Agent billing cycle',AFTER_SERVICE:'Pay after service · approval required'}
const specials=[['VEGAN','Vegan'],['VEGETARIAN','Vegetarian'],['OWN_TENT','Has own tent'],['OWN_BUNGALOW','Has own bungalow'],['NO_MEALS','No meals'],['NO_PARK_FEE','No park admission'],['NO_TRANSFER','No transfer'],['OTHER','Other requirements']]
const category=line=>line.resource?.category||line.snapshot?.category
const matches=(line,flag)=>({NO_MEALS:'MEAL',NO_PARK_FEE:'PARK_FEE',NO_TRANSFER:'TRANSFER',OWN_TENT:'ACCOMMODATION',OWN_BUNGALOW:'ACCOMMODATION'}[flag]===category(line))
const excludedBy=(line,flags)=>flags.some(flag=>matches(line,flag))
const key=line=>line.componentId||line.snapshot?.componentId||line.resourceId
const lookups=Object.fromEntries(['agents','hotels','channels'].map(entity=>[entity,({q,page,signal})=>api(`/api/operations/booking-options?${new URLSearchParams({entity,q,page})}`,undefined,{signal})]))
const guestFields=[['agentReference','Agent reference'],['contactPhone','Guest contact phone'],['room','Room (optional)'],['pickupPoint','Pickup point'],['dropoffPoint','Return drop-off point']]

export function BookingEditor({record,onClose,onSaved,canApprove,islandOnly=false}){
 const initial=useRef(record?{...record,tourId:record.tourId||record.trip?.tourId||record.trip?.tour?.id||'',serviceDate:date(record.serviceDate||record.outboundDate||record.returnDate||record.trip?.startsAt),returnDate:date(record.returnDate),returnStatus:record.returnStatus||'PENDING',allergyStatus:record.allergyStatus||(record.allergies?'HAS':'UNKNOWN'),specialRequirements:record.specialRequirements||[],lines:(record.lines||[]).map(l=>({...l,componentId:l.componentId||l.snapshot?.componentId,selection:l.selection||l.snapshot?.selection,removalCredit:l.removalCredit??l.snapshot?.removalCredit,selected:l.selected!==false}))}:{id:crypto.randomUUID(),version:0,name:'',tourId:'',serviceDate:today(),returnDate:'',returnStatus:'PENDING',adults:1,children:0,agentId:'',paymentTerms:'UNSET',allergyStatus:'UNKNOWN',specialRequirements:[],lines:[]})
 const [draft,setDraft]=useState(initial.current),[quote,setQuote]=useState(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[quoteError,setQuoteError]=useState(''),[retry,setRetry]=useState(0),[discard,setDiscard]=useState(false),[submitted,setSubmitted]=useState(false)
 const loadedProgram=useRef(record?initial.current.tourId:null),loadedAgent=useRef(record?.agentId||''),lock=useRef(false),formRef=useRef(null)
 const dirty=JSON.stringify(draft)!==JSON.stringify(initial.current);useUnsavedChanges(dirty||busy)
 const loadPrograms=useCallback(({q,page,signal})=>api(`/api/operations/booking-options?${new URLSearchParams({entity:'tours',q,page,...(islandOnly?{journeyMode:'RETURN_ONLY'}:{})})}`,undefined,{signal}),[islandOnly])
 const set=(field,value)=>setDraft(d=>({...d,[field]:value}))
 useEffect(()=>{
  if(!draft.tourId||!draft.serviceDate)return
  const c=new AbortController();setLoading(true);setQuoteError('')
  const timer=setTimeout(()=>api(`/api/operations/blueprint?${new URLSearchParams({tourId:draft.tourId,serviceDate:draft.serviceDate,adults:draft.adults,children:draft.children,agentId:draft.agentId||'',...(record?{bookingId:record.id}:{}),returnStatus:draft.returnStatus||'PENDING',...(draft.returnDate?{returnDate:draft.returnDate}:{})})}`,undefined,{signal:c.signal}).then(data=>{
   if(c.signal.aborted)return
   setQuote(data)
   setDraft(d=>{
    const same=loadedProgram.current===d.tourId,old=new Map(d.lines.map(l=>[key(l),l]))
    const lines=(data.lines||[]).map(l=>{const previous=same?old.get(key(l)):null;const next={...l,selected:previous?previous.selected:l.selected,quantity:previous?.quantityEdited?previous.quantity:l.quantity};if(Number(next.quantity)===0)next.selected=false;if(excludedBy(next,d.specialRequirements)&&next.selection!=='REQUIRED')next.selected=false;return next})
    if(same){const current=new Set(lines.map(key));for(const l of d.lines)if(!l.componentId&&!current.has(key(l)))lines.push(l)}
    const allowed=data.allowedPaymentTerms||['PREPAID','COUNTER'];const agentChanged=loadedAgent.current!==(d.agentId||'')
    loadedAgent.current=d.agentId||'';loadedProgram.current=d.tourId
    return {...d,adultPrice:data.adultPrice,childPrice:data.childPrice,lines,paymentTerms:agentChanged||(!allowed.includes(d.paymentTerms)&&d.paymentTerms!=='PAID')?(data.defaultPaymentTerms||allowed[0]||'UNSET'):d.paymentTerms}
   })
  }).catch(e=>{if(!c.signal.aborted)setQuoteError(message(e))}).finally(()=>{if(!c.signal.aborted)setLoading(false)}),150)
  return()=>{clearTimeout(timer);c.abort()}
 },[draft.tourId,draft.serviceDate,draft.adults,draft.children,draft.agentId,draft.returnStatus,draft.returnDate,retry,record])
 const mode=quote?.program?.journeyMode||record?.programSnapshot?.journeyMode||record?.journeyMode||record?.trip?.tour?.journeyMode
 let amount;try{amount=bookingQuote(draft)}catch{amount={}}
 function toggleSpecial(flag,checked){
  if(checked&&draft.lines.some(l=>matches(l,flag)&&l.selection==='REQUIRED')){setError('This program requires that service. Choose another program or ask your Manager to update its settings.');return}
  setError('');setDraft(d=>{const specialRequirements=checked?[...d.specialRequirements,flag]:d.specialRequirements.filter(f=>f!==flag);return {...d,specialRequirements,lines:d.lines.map(l=>checked&&matches(l,flag)?{...l,selected:false}:l)}})
 }
 async function save(e){
  e.preventDefault();setSubmitted(true);setError('')
  if(!draft.name.trim()||!draft.tourId||!draft.serviceDate||!e.currentTarget.checkValidity()){setError('Complete the required booking fields.');e.currentTarget.querySelector(':invalid,[aria-invalid="true"]')?.focus();return}
  if(loading||quoteError||!quote){setError('Wait for the program price to load or retry the quote.');return}
  if(draft.allergyStatus==='HAS'&&!draft.allergies?.trim()){setError('Specify the food allergies.');return}
  if(draft.specialRequirements.includes('OTHER')&&!draft.requestNotes?.trim()){setError('Describe the other requirements.');return}
  if(draft.lines.some(l=>l.selected!==false&&excludedBy(l,draft.specialRequirements))){setError('A selected service conflicts with the special requirements. Review the services below.');return}
  if(lock.current)return;lock.current=true;setBusy(true)
  try{await api('/api/operations/bookings',{id:draft.id,version:draft.version,name:draft.name,tourId:draft.tourId,serviceDate:draft.serviceDate,returnStatus:mode==='OPEN_RETURN'?draft.returnStatus:quote.journey?.returnStatus,returnDate:mode==='OPEN_RETURN'&&draft.returnStatus==='OUR'?draft.returnDate:undefined,adults:Number(draft.adults),children:Number(draft.children),agentId:draft.agentId||null,hotelId:draft.hotelId||null,channelId:draft.channelId||null,hotel:draft.hotel||'',allergyStatus:draft.allergyStatus,allergies:draft.allergyStatus==='HAS'?draft.allergies:'',specialRequirements:draft.specialRequirements,...Object.fromEntries([...guestFields.map(([k])=>k),'assistance','requestNotes','paymentTerms','afterServiceReason'].map(k=>[k,draft[k]||''])),lines:draft.lines.map(l=>({componentId:l.componentId||undefined,resourceId:l.resourceId,selected:l.selected!==false,quantity:Number(l.quantity),usagePoint:l.usagePoint||undefined,dispatchDirection:l.dispatchDirection||undefined}))});onSaved()}catch(err){setError(message(err))}finally{lock.current=false;setBusy(false)}
 }
 return <><Dialog title={record?`Edit booking · ${record.code}`:'New booking'} variant="table" busy={busy} onClose={()=>dirty?setDiscard(true):onClose()}><form ref={formRef} noValidate onSubmit={save}>
 <fieldset className="address-section" disabled={busy}><legend>Guest and journey</legend><p className="field-help">Booking number is assigned automatically when saved.</p><FormField label="Group / guest name" required value={draft.name} error={submitted&&!draft.name.trim()?'Group name is required.':undefined} onChange={e=>set('name',e.target.value)}/><ReferenceField label="Tour program" value={draft.tourId} selectedLabel={record?.trip?.tour?.name||record?.trip?.name} load={loadPrograms} error={submitted&&!draft.tourId?'Select a program.':undefined} onChange={e=>{setQuote(null);setDraft(d=>({...d,tourId:e.target.value,returnStatus:'PENDING',returnDate:''}))}}/><DateField label={mode==='RETURN_ONLY'?'Return service date':'Travel date'} required value={draft.serviceDate} onChange={e=>set('serviceDate',e.target.value)}/><p className="field-help">Date of the guest’s journey, even when this booking is entered in advance.</p><FormField label="Adults" type="number" min="0" step="1" required value={draft.adults} onChange={e=>set('adults',e.target.value)}/><FormField label="Children" type="number" min="0" step="1" required value={draft.children} onChange={e=>set('children',e.target.value)}/>
 {mode==='OPEN_RETURN'?<><SelectField label="Return arrangement" value={draft.returnStatus} onChange={e=>set('returnStatus',e.target.value)}><option value="PENDING">Waiting for guest’s return date</option><option value="OUR">Returning with Greenview</option><option value="OTHER">Not returning with Greenview</option></SelectField>{draft.returnStatus==='OUR'&&<DateField label="Return date" required min={draft.serviceDate} value={draft.returnDate} onChange={e=>set('returnDate',e.target.value)}/>}</>:quote&&<p>Outbound: {date(quote.journey?.outboundDate)||'Not with Greenview'} · Return: {date(quote.journey?.returnDate)||'Not with Greenview'}</p>}</fieldset>
 <fieldset className="address-section" disabled={busy}><legend>Agent and guest details</legend><ReferenceField label="Agent" value={draft.agentId||''} selectedLabel={draft.agent?.name} load={lookups.agents} onChange={e=>set('agentId',e.target.value)}/><p className="field-help">Leave empty for a direct booking. The program rate and payment options follow the selected agent.</p><ReferenceField label="Hotel" value={draft.hotelId||''} selectedLabel={draft.hotelRecord?.name||draft.hotel} load={lookups.hotels} onChange={e=>set('hotelId',e.target.value)}/>{draft.hotel&&!draft.hotelId&&<p>Previously recorded hotel: {draft.hotel}</p>}<ReferenceField label="Sales channel" value={draft.channelId||''} selectedLabel={draft.channel?.name} load={lookups.channels} onChange={e=>set('channelId',e.target.value)}/>{guestFields.map(([field,label])=><FormField key={field} label={label} value={draft[field]||''} onChange={e=>set(field,e.target.value)}/>)}</fieldset>
 <fieldset className="address-section" disabled={busy}><legend>Guest requirements</legend><SelectField label="Food allergies" value={draft.allergyStatus} onChange={e=>set('allergyStatus',e.target.value)}><option value="UNKNOWN">Not yet checked</option><option value="NONE">No food allergies</option><option value="HAS">Has food allergies</option></SelectField>{draft.allergyStatus==='HAS'&&<TextAreaField label="Allergy details" required value={draft.allergies||''} onChange={e=>set('allergies',e.target.value)}/>}{specials.map(([value,label])=><label className="checkbox-field" key={value}><input type="checkbox" checked={draft.specialRequirements.includes(value)} onChange={e=>toggleSpecial(value,e.target.checked)}/> {label}</label>)}<p className="field-help">Excluding a service uses its configured removal credit. Removing a special requirement does not reselect services; review them below.</p><TextAreaField label="Assistance needs" value={draft.assistance||''} onChange={e=>set('assistance',e.target.value)}/><TextAreaField label="Special request details" required={draft.specialRequirements.includes('OTHER')} value={draft.requestNotes||''} onChange={e=>set('requestNotes',e.target.value)}/></fieldset>
 <fieldset className="address-section" disabled={busy||loading}><legend>Program services</legend>{loading&&<p role="status">Loading program and agent rate…</p>}{quoteError&&<><p role="alert">{quoteError}</p><Button onClick={()=>setRetry(n=>n+1)}>Retry program price</Button></>}{draft.lines.map((line,index)=><fieldset className="address-section" key={key(line)}><legend>{line.resource?.name||line.snapshot?.name||'Service'}</legend><label className="checkbox-field"><input type="checkbox" checked={line.selected!==false} disabled={['REQUIRED','EXCLUDED'].includes(line.selection)||excludedBy(line,draft.specialRequirements)} onChange={e=>setDraft(d=>({...d,lines:d.lines.map((l,i)=>i===index?{...l,selected:e.target.checked}:l)}))}/> {line.selection==='REQUIRED'?'Required':line.included?'Included in package':'Optional'}</label><FormField label={`Quantity (${line.resource?.baseUnit||'units'})`} disabled={line.included} type="number" min={line.selected!==false?1:0} step="1" required value={line.quantity} onChange={e=>setDraft(d=>({...d,lines:d.lines.map((l,i)=>i===index?{...l,quantity:e.target.value,quantityEdited:true}:l)}))}/><p className="field-help">{line.included?`Removal credit / unit: ${money(line.removalCredit??line.snapshot?.removalCredit)}`:`Price / unit: ${money(line.unitPrice??line.snapshot?.unitPrice)}`}</p></fieldset>)}{quote&&!draft.lines.length&&<p>This program has no configured service components.</p>}<p className="field-help">Guide assigns boats. Head Driver assigns vehicles. Assistant Guide prepares supplies from boat assignments.</p></fieldset>
 <fieldset className="address-section" disabled={busy}><legend>Price and payment</legend><p>Adult: {money(draft.adultPrice)} · Child: {money(draft.childPrice)}</p><dl className="detail-list"><dt>Program price</dt><dd>{money(amount?.base)}</dd><dt>Removal credits</dt><dd>{money(amount?.credit)}</dd><dt>Add-ons</dt><dd>{money(amount?.addons)}</dd><dt>Total</dt><dd><strong>{money(amount?.total)}</strong></dd></dl><SelectField label="Payment terms" value={draft.paymentTerms} onChange={e=>set('paymentTerms',e.target.value)}>{[...new Set([...(quote?.allowedPaymentTerms||['PREPAID','COUNTER']),...(draft.paymentTerms==='PAID'?['PAID']:[])])].map(value=><option key={value} value={value} disabled={value==='AFTER_SERVICE'&&!canApprove}>{terms[value]||value}</option>)}</SelectField>{draft.paymentTerms==='AFTER_SERVICE'&&<TextAreaField label="Reason for payment after service" required value={draft.afterServiceReason||''} onChange={e=>set('afterServiceReason',e.target.value)}/>}</fieldset>{error&&<p role="alert">{error}</p>}<div className="dialog-actions"><Button type="submit" className="button-primary" busy={busy} disabled={busy||loading||!quote||Boolean(quoteError)}>Save draft</Button></div></form></Dialog>{discard&&<Dialog title="Discard changes?" onClose={()=>setDiscard(false)}><p>Your unsaved booking changes will be lost.</p><Button onClick={()=>setDiscard(false)}>Keep editing</Button><Button onClick={onClose}>Discard changes</Button></Dialog>}</>
}

export function BookingReturnAmendment({record,onClose,onSaved}){
 const initial=useRef({id:crypto.randomUUID(),bookingId:record.id,version:record.version,returnStatus:record.returnStatus||'PENDING',returnDate:date(record.returnDate),reason:''})
 const [draft,setDraft]=useState(initial.current),[busy,setBusy]=useState(false),[error,setError]=useState(''),[discard,setDiscard]=useState(false);const lock=useRef(false),dirty=JSON.stringify(draft)!==JSON.stringify(initial.current);useUnsavedChanges(dirty||busy)
 const set=(k,v)=>setDraft(d=>({...d,id:crypto.randomUUID(),[k]:v}))
 async function save(e){e.preventDefault();if(!e.currentTarget.checkValidity()){e.currentTarget.querySelector(':invalid')?.focus();setError('Complete the return date and reason.');return}if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await api('/api/operations/booking-return',{...draft,returnDate:draft.returnStatus==='OUR'?draft.returnDate:null});onSaved()}catch(err){setError(message(err))}finally{lock.current=false;setBusy(false)}}
 return <><Dialog title={`Update return journey · ${record.code}`} busy={busy} onClose={()=>dirty?setDiscard(true):onClose()}><form noValidate onSubmit={save}><fieldset className="address-section" disabled={busy}><legend>{record.name}</legend><SelectField label="Return arrangement" value={draft.returnStatus} onChange={e=>set('returnStatus',e.target.value)}><option value="PENDING">Waiting for return date</option><option value="OUR">Returning with Greenview</option><option value="OTHER">Not returning with Greenview</option></SelectField>{draft.returnStatus==='OUR'&&<DateField label="Return date" required min={date(record.outboundDate||record.serviceDate)} value={draft.returnDate} onChange={e=>set('returnDate',e.target.value)}/>}<TextAreaField label="Reason for change" required value={draft.reason} onChange={e=>set('reason',e.target.value)}/><p className="field-help">Existing return assignments must be released before changing a booked return journey.</p></fieldset>{error&&<p role="alert">{error}</p>}<div className="dialog-actions"><Button type="submit" busy={busy} className="button-primary">Update return journey</Button></div></form></Dialog>{discard&&<Dialog title="Discard changes?" onClose={()=>setDiscard(false)}><Button onClick={()=>setDiscard(false)}>Keep editing</Button><Button onClick={onClose}>Discard changes</Button></Dialog>}</>
}
