import LegacyCapacityBinding from './LegacyCapacityBinding.jsx'
import {useEffect,useState} from 'react'
import {useLocale} from '../../core/i18n/locale.jsx'
import {api} from '../../core/auth/api.js'
import {Button} from '../../core/ui/Button.jsx'
import {DataTable} from '../../core/ui/DataTable.jsx'
import {DateField} from '../../core/ui/DateField.jsx'
import {SelectField} from '../../core/ui/SelectField.jsx'
import {SummaryCards} from '../../core/ui/SummaryCards.jsx'
import {RefreshButton} from '../../core/ui/RefreshButton.jsx'
import {Dropdown} from '../../core/ui/Dropdown.jsx'
import {capacityText,capacityLabel} from '../../../../../packages/contracts/capacity-copy.js'
import CapacityPoolEditor from './CapacityPoolEditor.jsx'
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
export default function CapacityPage({actor}) {
 const {locale,t,formatDate}=useLocale(),c=key=>capacityText(key,locale),label=key=>capacityLabel(key,locale)
 const params=new URLSearchParams(location.search),[date,setDate]=useState(params.get('date')||today()),[kind,setKind]=useState(params.get('kind')==='VEHICLE'?'VEHICLE':'BOAT'),[retry,setRetry]=useState(0),[result,setState]=useState({loading:true}),[edit,setEdit]=useState(null),[notice,setNotice]=useState(''),[binding,setBinding]=useState(null)
 const requestKey=kind+':'+date,state=result.key===requestKey?result:{loading:true}
 const canManage=kind==='BOAT'?actor?.operations?.manageGuide:actor?.operations?.manageDriver
 useEffect(()=>{const controller=new AbortController();setState({key:requestKey,loading:true});api('/api/operations/capacity?'+new URLSearchParams({date,kind}),undefined,{signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setState({...data,key:requestKey})}).catch(e=>{if(!controller.signal.aborted)setState({key:requestKey,error:e.message})});return()=>controller.abort()},[date,kind,retry,requestKey])
 const rows=state.rows||[],active=rows.filter(r=>r.status==='ACTIVE')
 return <><div className="page-heading"><div><h1>{label('title')}</h1><p>{c('verified')}</p></div>{canManage&&<Button className="button-primary" onClick={()=>setEdit({})}>{c('newWindow')}</Button>}</div>
 <div className="filterbar has-fields"><DateField label={label('date')} value={date} onChange={e=>{setNotice('');setDate(e.target.value)}}/><SelectField label={t('Type')} value={kind} onChange={e=>{setNotice('');setKind(e.target.value)}}>{['BOAT','VEHICLE'].map(v=><option key={v} value={v}>{c(v)}</option>)}</SelectField><RefreshButton onClick={()=>setRetry(n=>n+1)}/></div>
 {notice&&<p role="status">{notice}</p>}<SummaryCards items={[{label:label('window'),value:state.loading||state.error?undefined:active.length},{label:label('total'),value:state.loading||state.error?undefined:active.reduce((n,r)=>n+r.passengers-r.heldPassengers,0)},{label:label('held'),value:state.loading||state.error?undefined:active.reduce((n,r)=>n+r.heldPassengers,0)},{label:label('review'),value:state.loading||state.error?undefined:active.filter(r=>kind==='BOAT'?r.plan&&r.plan.status!=='FEASIBLE':r.van?.additionalUnitsNeeded>0||r.van?.minimumAvailableVehicles===null).length}]}/>
 {state.loading?<section className="panel"><p role="status">{c('loading')}</p></section>:state.error?<section className="panel"><p role="alert">{c('error')}</p><Button onClick={()=>setRetry(n=>n+1)}>{c('refresh')}</Button></section>:!rows.length?<section className="panel"><div className="panel-heading"><p>{c('empty')}</p></div></section>:rows.map(row=><section key={row.id} className="panel table-panel" style={{marginBottom:20}}>
 <header className="panel-heading"><div><h2>{row.name} · {c(row.direction)}</h2><p>{row.code} · {formatDate(row.startsAt,{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Bangkok'})} – {formatDate(row.endsAt,{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Bangkok'})} · {c(row.status)}</p></div>{canManage&&<Dropdown rowActions label={`${c('editWindow')} ${row.code}`} items={[{label:c('editWindow'),icon:'edit',onSelect:()=>setEdit(row)}]}/>}</header>
 <DataTable label={label('vehicles')} layout="content" columns={[capacityText(kind,'en'),'Status',capacityText('usable','en')]} isEmpty={!row.offers.length}>{row.offers.map(o=><tr key={o.id}><td>{o.vehicle.name}</td><td>{c(o.status)}</td><td>{o.usableCapacity}</td></tr>)}</DataTable>
 {kind==='BOAT'?<><div className="panel-heading"><h3>{label('plan')}</h3><p>{c(row.plan.status==='FEASIBLE'?'fit':'unavailable')}{row.plan.status==='FEASIBLE'?` · ${c('boats')}: ${row.plan.boatCount} · ${c('spare')}: ${row.plan.spareSeats}`:''}</p></div>{row.plan.status!=='FEASIBLE'&&<p className="field-help">{c('review')} · {c(row.plan.reason||'unknown')}</p>}
 <DataTable label={label('plan')} layout="content" columns={['Boat',capacityText('whole','en'),capacityText('actual','en'),capacityText('spare','en')]} isEmpty={!row.plan.assignments?.length}>{(row.plan.assignments||[]).map(a=><tr key={a.boatId}><td>{row.offers.find(o=>o.vehicleId===a.boatId)?.vehicle.name||'—'}</td><td>{a.bookingIds.map(id=>row.groups.find(g=>g.id===id)?.code||'—').join(' · ')}</td><td>{a.pax} / {a.capacity}</td><td>{a.capacity-a.pax}</td></tr>)}</DataTable><p className="field-help">{c('selectionHint')} {c('noSplit')}</p></>:<><SummaryCards items={[{label:label('actual'),value:row.van.actualPassengers},{label:label('weighted'),value:row.van.weightedUnits},{label:label('vanMinimum'),value:row.van.minimumAvailableVehicles},{label:label('additional'),value:row.van.additionalUnitsNeeded}]}/><p>{c('factor')}: {row.van.overnightFactor} · {c('vanHint')}</p>{row.van.extraVehicles>0&&<p>{capacityText('vanExtra',locale,{count:row.van.extraVehicles,capacity:row.van.referenceVehicleCapacity})}</p>}</>}
 <DataTable label={label('whole')} layout="content" columns={['Booking',capacityText('actual','en'),capacityText('fixed','en'),'Actions']} isEmpty={!row.groups.length}>{row.groups.map(g=><tr key={g.id}><td>{g.code}</td><td>{g.pax}</td><td>{g.fixedBoatId?row.offers.find(o=>o.vehicleId===g.fixedBoatId)?.vehicle.name||'—':'—'}</td><td>{kind==='BOAT'&&canManage&&g.needsWindowSelection&&<Dropdown rowActions label={c('bindLegacy')+' '+g.code} items={[{label:c('bindLegacy'),icon:'edit',onSelect:()=>setBinding({pool:row,group:g})}]}/>}</td></tr>)}</DataTable>
 </section>)}{binding&&<LegacyCapacityBinding {...binding} onClose={()=>setBinding(null)} onSaved={result=>{setBinding(null);setNotice(result.requiresTeamReview?c('shortage'):t('Changes saved.'));setRetry(n=>n+1)}}/>}{edit&&<CapacityPoolEditor kind={kind} date={date} record={edit.id?edit:null} onClose={()=>setEdit(null)} onSaved={result=>{setEdit(null);setNotice(result.requiresTeamReview?c('shortage'):t('Changes saved.'));setRetry(n=>n+1)}}/>}</>
}
