import {translateLabel as bilingualLabel} from '../../core/i18n/runtime.js'
import { formatDate as displayDate, formatNumber } from '../../core/i18n/runtime.js'
import { translate as t, useLocale } from '../../core/i18n/locale.jsx'
import { Fragment } from 'react'
import { DocumentHeader } from './DocumentCore.jsx'
const money=v=>v==null?"Not set":formatNumber(v, {minimumFractionDigits:2,maximumFractionDigits:2})
const terms={PREPAID:"Before service",PAID:"Paid",COUNTER:"Pay on service day",AGENT_CREDIT:"Agent credit",AFTER_SERVICE:"Pay after service",UNSET:'Not set'}
const day=v=>displayDate(new Date(v), {timeZone:'Asia/Bangkok',dateStyle:'medium'})
const time=v=>v?displayDate(new Date(v), {timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}):'Not set'
export function DailyBookingSheet({document:d}){
 useLocale();
 const s=d.summary
 return <section className="job-sheet daily-booking-sheet"><DocumentHeader title={bilingualLabel("DAILY BOOKING JOB ORDER")} code={`GV-DAY-${d.date.replaceAll('-','')}`} date={d.date}/><p className="job-footnote">{t("Confirmed arrivals and return-only bookings · Updated")}{' '}{displayDate(new Date(d.generatedAt), {dateStyle:'short', timeStyle:'medium', ...{timeZone:'Asia/Bangkok'}})}</p><div className="document-counts">{[["Bookings",s.bookings],["Adults",s.adults],["Children",s.children],["Total",s.guests]].map(([label,value])=><div key={label}>{t(label)}<strong>{value}</strong></div>)}</div>
 <table className="document-table booking-daily-table"><colgroup>{[3,9,11,13,13,4,4,4,12,12,15].map((width,i)=><col key={i} style={{width:`${width}%`}}/>)}</colgroup><thead><tr><th colSpan="11">Greenview Tour · {d.date}{' '}{bilingualLabel("· Daily bookings")}</th></tr><tr>{['No.','Booking ref.',"Agent","Guest group","Program",'Adults','Child','Total',"Payment terms","Collect on service day (THB)","Notes"].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{d.rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.code}<small>{t("Rev.")}{' '}{r.version}</small></td><td>{r.agentName}</td><td>{r.name}</td><td>{r.programName}</td><td>{r.adults}</td><td>{r.children}</td><td>{r.adults+r.children}</td><td>{terms[r.paymentTerms]}</td><td className="document-money">{r.paymentTerms==='COUNTER'?money(r.collectAmount):'—'}</td><td>{r.notes||'—'}</td></tr>)}{!d.rows.length&&<tr><td colSpan="11">{t("No bookings for this service day")}</td></tr>}<tr className="job-total-row"><th colSpan="5">{bilingualLabel("Total")}</th><td>{s.adults}</td><td>{s.children}</td><td>{s.guests}</td><td></td><td className="document-money">{s.unknownPrices?t("Incomplete price"):money(s.collectAmount)}</td><td></td></tr></tbody></table>
 <div className="document-summaries"><section><h3>{bilingualLabel("PROGRAM SUMMARY")}</h3><table className="document-table"><thead><tr><th>{bilingualLabel("Program")}</th><th>{bilingualLabel("Adults")}</th><th>{bilingualLabel("Children")}</th><th>{bilingualLabel("Total")}</th></tr></thead><tbody>{s.programs.map(p=><tr key={p.name}><td>{p.name}</td><td>{p.adults}</td><td>{p.children}</td><td>{p.adults+p.children}</td></tr>)}</tbody></table></section><section><h3>{bilingualLabel("PAYMENT TERMS SUMMARY")}</h3><table className="document-table"><thead><tr><th>{bilingualLabel("Terms")}</th><th>{bilingualLabel("Bookings")}</th><th>{bilingualLabel("Guests")}</th></tr></thead><tbody>{s.payments.map(p=><tr key={p.terms}><td>{terms[p.terms]}</td><td>{p.bookings}</td><td>{p.guests}</td></tr>)}</tbody></table><p className="document-collection"><strong>{t("To collect:")}{' '}{s.unknownPrices?`Incomplete prices (${s.unknownPrices})`: `THB ${money(s.collectAmount)}`}</strong></p></section></div><p className="job-signoff">{t("Prepared by ____________________  Checked by ____________________")}</p></section>
}
export function TransferDailySheet({runs}){
 useLocale();
 const first=runs[0];if(!first)return null
 const vehicle=first.slot?.vehicle
 return <section className="job-sheet transfer-daily-sheet"><DocumentHeader title={bilingualLabel("TRANSFER JOB ORDER")} code={`GV-VN-${vehicle?.id?.slice(0,8)||first.code}`} date={day(first.slot.startsAt)}/><div className="document-vehicle"><strong>{vehicle?.name||t("Unassigned vehicle")} · {vehicle?.registration||'—'}</strong><span>{t("Capacity")}{' '}{vehicle?.capacity||first.capacity}</span><span>{t("Driver:")}{' '}{[...new Set(runs.flatMap(r=>r.staff.map(p=>p.name)))].join(' / ')||t("Not assigned")}</span></div>
 {['OUTBOUND','RETURN'].map(direction=>{const pickup=direction==='OUTBOUND';const selected=runs.filter(r=>r.direction===direction);const rows=selected.flatMap(run=>run.assignments.map(a=>({...a,run}))).sort((a,b)=>pickup?String(a.pickupAt||'').localeCompare(String(b.pickupAt||'')):String(a.dropoffPoint||a.booking.hotel||'').localeCompare(String(b.dropoffPoint||b.booking.hotel||'')));const adults=rows.reduce((n,r)=>n+r.adults,0),children=rows.reduce((n,r)=>n+r.children,0);return <Fragment key={direction}><h3 className="document-section">{pickup?bilingualLabel("PICKUP"):bilingualLabel("DROP-OFF")}</h3><table className="document-table"><thead><tr><th colSpan={pickup?10:9}>{vehicle?.name} · {day(first.slot.startsAt)} · {pickup?bilingualLabel("PICKUP"):bilingualLabel("DROP-OFF")} · {selected.map(r=>`${r.code} Rev. ${r.version}`).join(' / ')}</th></tr><tr><th>{bilingualLabel("No.")}</th>{pickup&&<th>{bilingualLabel("Pickup time")}</th>}<th>{bilingualLabel("Guest / Booking")}</th><th>{bilingualLabel("Agent / Contact")}</th><th>{bilingualLabel("Adults")}</th><th>{bilingualLabel("Children")}</th><th>{pickup?bilingualLabel('Hotel / Meeting point'):bilingualLabel("Pickup point")}</th><th>{bilingualLabel("Destination")}</th><th>{bilingualLabel("Room")}</th><th>{bilingualLabel("Notes / Check")}</th></tr></thead><tbody>{rows.map((a,i)=><tr key={a.id}><td>{i+1}</td>{pickup&&<td><strong>{time(a.pickupAt)}</strong></td>}<td>{a.booking.name}<small>{a.booking.code}</small></td><td>{a.booking.agentName||'Direct'}<small>{a.booking.agentPhone}</small></td><td>{a.adults}</td><td>{a.children}</td><td>{pickup?a.booking.pickupPoint||a.booking.hotel||t("Not set"):t("Pier meeting point")}</td><td>{a.dropoffPoint||a.booking.dropoffPoint||(!pickup?a.booking.hotel:null)||t("Not set")}</td><td>{a.booking.room||'—'}</td><td>{[a.booking.assistance,a.notes].filter(Boolean).join(' · ')||'—'}<small>{t("□ Checked")}</small></td></tr>)}{!rows.length&&<tr><td colSpan={pickup?10:9}>{t("No assignments")}</td></tr>}<tr className="job-total-row"><th colSpan={pickup?4:3}>{bilingualLabel("Total")}</th><td>{adults}</td><td>{children}</td><td colSpan="4">{adults+children}{' '}{t("passengers ·")}{' '}{rows.length}{' '}{t("groups")}</td></tr></tbody></table></Fragment>})}<p className="job-footnote">{t("Drop-off times are not specified")}</p><p className="job-signoff">{t("Driver acknowledgement ____________________  Dispatch checked by ____________________")}</p></section>
}
