import { Fragment } from 'react'
import { DocumentHeader } from './DocumentCore.jsx'
const money=v=>v==null?'Not set / ยังไม่ระบุ':new Intl.NumberFormat('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2}).format(v)
const terms={PAID:'Paid / ชำระแล้ว',COUNTER:'Counter / ชำระวันบริการ',AGENT_CREDIT:'Agent credit / เครดิตเอเย่นต์',AFTER_SERVICE:'After service / หลังบริการ',UNSET:'Not set'}
const day=v=>new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',dateStyle:'medium'}).format(new Date(v))
const time=v=>v?new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(v)):'Not set'
export function DailyBookingSheet({document:d}){
 const s=d.summary
 return <section className="job-sheet daily-booking-sheet"><DocumentHeader title="DAILY BOOKING JOB ORDER / ใบงานบุ๊กกิ้งประจำวัน" code={`GV-DAY-${d.date.replaceAll('-','')}`} date={d.date}/><p className="job-footnote">Confirmed and completed bookings active on this service day · รายการยืนยันและเสร็จสิ้นที่อยู่ในวันบริการนี้ · Updated {new Date(d.generatedAt).toLocaleString('en-GB',{timeZone:'Asia/Bangkok'})}</p><div className="document-counts">{[['Bookings / รายการ',s.bookings],['Adults / ผู้ใหญ่',s.adults],['Children / เด็ก',s.children],['Total / รวม',s.guests]].map(([label,value])=><div key={label}>{label}<strong>{value}</strong></div>)}</div>
 <table className="document-table booking-daily-table"><colgroup>{[3,7,9,10,10,4,4,4,11,10,10,7,11].map((width,i)=><col key={i} style={{width:`${width}%`}}/>)}</colgroup><thead><tr><th colSpan="13">Greenview Tour · {d.date} · Daily bookings / รายการประจำวัน</th></tr><tr>{['No.','Booking ref.','Agent / เอเย่นต์','Guest group / ชื่อกลุ่ม','Program / โปรแกรม','Adults','Child','Total','Payment terms / เงื่อนไขชำระ','Collect on service day (THB) / ยอดเก็บวันบริการ','Hotel / Room','Transfer / รถรับส่ง','Notes / หมายเหตุ'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{d.rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.code}<small>Rev. {r.version}</small></td><td>{r.agentName}</td><td>{r.name}</td><td>{r.programName}</td><td>{r.adults}</td><td>{r.children}</td><td>{r.adults+r.children}</td><td>{terms[r.paymentTerms]}</td><td className="document-money">{r.paymentTerms==='COUNTER'?money(r.collectAmount):'—'}</td><td>{[r.hotel,r.room].filter(Boolean).join(' / ')||'—'}</td><td>{r.transfers.map(x=>x==='OUTBOUND'?'รับ':'ส่ง').join(' / ')||'—'}</td><td>{r.notes||'—'}</td></tr>)}{!d.rows.length&&<tr><td colSpan="13">No bookings for this service day / ไม่มีรายการในวันบริการนี้</td></tr>}<tr className="job-total-row"><th colSpan="5">Total / รวม</th><td>{s.adults}</td><td>{s.children}</td><td>{s.guests}</td><td></td><td className="document-money">{s.unknownPrices?'Incomplete / ราคาไม่ครบ':money(s.collectAmount)}</td><td colSpan="3"></td></tr></tbody></table>
 <div className="document-summaries"><section><h3>PROGRAM SUMMARY / สรุปตามโปรแกรม</h3><table className="document-table"><thead><tr><th>Program</th><th>Adults</th><th>Children</th><th>Total</th></tr></thead><tbody>{s.programs.map(p=><tr key={p.name}><td>{p.name}</td><td>{p.adults}</td><td>{p.children}</td><td>{p.adults+p.children}</td></tr>)}</tbody></table></section><section><h3>PAYMENT TERMS SUMMARY / สรุปตามเงื่อนไขชำระ</h3><table className="document-table"><thead><tr><th>Terms</th><th>Bookings</th><th>Guests</th></tr></thead><tbody>{s.payments.map(p=><tr key={p.terms}><td>{terms[p.terms]}</td><td>{p.bookings}</td><td>{p.guests}</td></tr>)}</tbody></table><p className="document-collection"><strong>To collect / ยอดเก็บวันบริการ: {s.unknownPrices?`Incomplete prices (${s.unknownPrices})`: `THB ${money(s.collectAmount)}`}</strong></p></section></div><p className="job-signoff">Prepared by ____________________  Checked by ____________________</p></section>
}
export function TransferDailySheet({runs}){
 const first=runs[0];if(!first)return null
 const vehicle=first.slot?.vehicle
 return <section className="job-sheet transfer-daily-sheet"><DocumentHeader title="TRANSFER JOB ORDER / ใบงานรถ" code={`GV-VN-${vehicle?.id?.slice(0,8)||first.code}`} date={day(first.slot.startsAt)}/><div className="document-vehicle"><strong>{vehicle?.name||'Unassigned vehicle'} · {vehicle?.registration||'—'}</strong><span>Capacity / ความจุ {vehicle?.capacity||first.capacity}</span><span>Driver / คนขับ: {[...new Set(runs.flatMap(r=>r.staff.map(p=>p.name)))].join(' / ')||'Not assigned / ยังไม่จัดคนขับ'}</span></div>
 {['OUTBOUND','RETURN'].map(direction=>{const pickup=direction==='OUTBOUND';const selected=runs.filter(r=>r.direction===direction);const rows=selected.flatMap(run=>run.assignments.map(a=>({...a,run}))).sort((a,b)=>pickup?String(a.pickupAt||'').localeCompare(String(b.pickupAt||'')):String(a.dropoffPoint||a.booking.hotel||'').localeCompare(String(b.dropoffPoint||b.booking.hotel||'')));const adults=rows.reduce((n,r)=>n+r.adults,0),children=rows.reduce((n,r)=>n+r.children,0);return <Fragment key={direction}><h3 className="document-section">{pickup?'รับ / PICKUP':'ส่ง / DROP-OFF'}</h3><table className="document-table"><thead><tr><th colSpan={pickup?10:9}>{vehicle?.name} · {day(first.slot.startsAt)} · {pickup?'รับ / PICKUP':'ส่ง / DROP-OFF'} · {selected.map(r=>`${r.code} Rev. ${r.version}`).join(' / ')}</th></tr><tr><th>No.</th>{pickup&&<th>Pickup time / เวลารับ</th>}<th>Guest / Booking</th><th>Agent / Contact</th><th>Adults</th><th>Children</th><th>{pickup?'Hotel / Meeting point':'Pickup point / จุดขึ้นรถ'}</th><th>Destination / ปลายทาง</th><th>Room / ห้อง</th><th>Notes / Check</th></tr></thead><tbody>{rows.map((a,i)=><tr key={a.id}><td>{i+1}</td>{pickup&&<td><strong>{time(a.pickupAt)}</strong></td>}<td>{a.booking.name}<small>{a.booking.code}</small></td><td>{a.booking.agentName||'Direct'}<small>{a.booking.agentPhone}</small></td><td>{a.adults}</td><td>{a.children}</td><td>{pickup?a.booking.pickupPoint||a.booking.hotel||'Not set':'Pier meeting point / จุดนัดหมายท่าเรือ'}</td><td>{a.dropoffPoint||a.booking.dropoffPoint||(!pickup?a.booking.hotel:null)||'Not set'}</td><td>{a.booking.room||'—'}</td><td>{[a.booking.assistance,a.notes].filter(Boolean).join(' · ')||'—'}<small>□ Checked</small></td></tr>)}{!rows.length&&<tr><td colSpan={pickup?10:9}>No assignments / ไม่มีรายการ</td></tr>}<tr className="job-total-row"><th colSpan={pickup?4:3}>Total / รวม</th><td>{adults}</td><td>{children}</td><td colSpan="4">{adults+children} passengers / คน · {rows.length} groups / กลุ่ม</td></tr></tbody></table></Fragment>})}<p className="job-footnote">Drop-off times are not specified / ไม่ระบุเวลาถึงโรงแรม</p><p className="job-signoff">Driver acknowledgement ____________________  Dispatch checked by ____________________</p></section>
}
