import {translateLabel as bilingualLabel} from '../../core/i18n/runtime.js'
import { translate as t, useLocale } from '../../core/i18n/locale.jsx'
import {useCallback,useEffect,useRef,useState} from 'react'
import {api} from '../../core/auth/api.js'
import {Button} from '../../core/ui/Button.jsx'
import {DataTable} from '../../core/ui/DataTable.jsx'
import {Pagination} from '../../core/ui/Pagination.jsx'
import {Dropdown} from '../../core/ui/Dropdown.jsx'
import {Dialog} from '../../core/ui/Dialog.jsx'
import {FormField} from '../../core/ui/FormField.jsx'
import {TextAreaField} from '../../core/ui/TextAreaField.jsx'
import {SelectField} from '../../core/ui/SelectField.jsx'
import {ReferenceField} from '../../core/ui/ReferenceField.jsx'
import {SearchField} from '../../core/ui/SearchField.jsx'
import {RefreshButton} from '../../core/ui/RefreshButton.jsx'
import {useUnsavedChanges} from '../../core/navigation/Navigation.jsx'
import {localStamp} from '../../../../../packages/contracts/operations.js'
const errorMessage=e=>({STAFF_TIME_CONFLICT:'This guide has an overlapping boat, transfer or guide assignment. Choose another guide or time.',INVALID_RUN_STAFF:'Select an active guide.',INVALID_TIME_RANGE:'The end time must follow the start time.',INVALID_TIME:'Use YYYY-MM-DD HH:mm for both times.',SERVICE_SLOT_UNAVAILABLE:'The assignment must fit the booked travel dates.',SETTINGS_CONFLICT:'This assignment changed. Close and refresh before trying again.',BOOKING_LOCKED:'Use a confirmed Booking, or cancel an existing assignment.',GUIDE_JOB_NOT_FINISHED:'The assignment cannot be completed before its end time.'}[e.message]||e.detail||'Unable to complete the action. Check your entries and retry.')
function Reference({entity,...props}){
 useLocale();const load=useCallback(({q,page,signal})=>api('/api/guide-assignments/options?'+new URLSearchParams({entity,q,page}),undefined,{signal}),[entity]);return <ReferenceField {...props} load={load}/>}
function Editor({row,onClose,onSaved}){
 useLocale();
 const initial={bookingId:row?.bookingId||'',guideId:row?.guideId||'',startsAt:row?localStamp(row.startsAt):'',endsAt:row?localStamp(row.endsAt):'',status:row?.status||'PLANNED',notes:row?.notes||''}
 const [values,setValues]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[discard,setDiscard]=useState(false),[confirm,setConfirm]=useState(false),id=useRef(row?.id||crypto.randomUUID()),base=useRef(JSON.stringify(initial)),lock=useRef(false)
 const dirty=JSON.stringify(values)!==base.current;useUnsavedChanges(dirty||busy)
 const change=key=>e=>{setValues(v=>({...v,[key]:e.target.value}));setConfirm(false);setError('')}
 const close=()=>{if(!busy){if(dirty)setDiscard(true);else onClose()}}
 async function save(e){e.preventDefault();if(lock.current)return;if(!values.bookingId||!values.guideId||!values.startsAt||!values.endsAt||values.status==='CANCELLED'&&!values.notes.trim()){setError('Select a Booking and guide, enter start/end times, and give a reason when cancelling.');return}if(row&&values.status!==row.status&&!confirm){setConfirm(true);return}lock.current=true;setBusy(true);try{await api('/api/guide-assignments',{...values,id:id.current,version:row?.version||0});onSaved()}catch(e){setError(errorMessage(e))}finally{lock.current=false;setBusy(false)}}
 return <Dialog title={row?bilingualLabel('Edit guide assignment'):bilingualLabel('Assign guide to Booking')} onClose={close} busy={busy}>{discard?<><p>{t("Discard unsaved assignment changes?")}</p><div className="dialog-actions"><Button onClick={()=>setDiscard(false)}>{t("Keep editing")}</Button><Button onClick={onClose}>{t("Discard changes")}</Button></div></>:<form noValidate onSubmit={save}><p>{t("Assign a guide independently of a boat or vehicle, including partner tours. Times use Thailand time (UTC+7).")}</p><Reference entity="bookings" label={bilingualLabel("Confirmed Booking")} value={values.bookingId} selectedLabel={row?row.booking.code+' · '+row.booking.name:undefined} onChange={change('bookingId')} disabled={busy||Boolean(row)}/><Reference entity="staff" label={bilingualLabel("Guide")} value={values.guideId} selectedLabel={row?.guide.displayName} onChange={change('guideId')} disabled={busy}/><FormField label={bilingualLabel("Starts at")} hint={t("YYYY-MM-DD HH:mm · Thailand time")} value={values.startsAt} onChange={change('startsAt')} disabled={busy}/><FormField label={bilingualLabel("Ends at")} hint={t("YYYY-MM-DD HH:mm · Thailand time")} value={values.endsAt} onChange={change('endsAt')} disabled={busy}/>{row&&<SelectField label={bilingualLabel("Status")} value={values.status} onChange={change('status')} disabled={busy}><option value="PLANNED">{t("Planned")}</option><option value="COMPLETED">{t("Completed")}</option><option value="CANCELLED">{t("Cancelled")}</option></SelectField>}<TextAreaField label={bilingualLabel("Guide instructions / cancellation reason")} value={values.notes} onChange={change('notes')} maxLength={2000} disabled={busy}/>{error&&<p role="alert">{t(error)}</p>}{confirm&&<p role="alert">{t("Confirm marking this assignment")}{' '}{t(values.status.toLowerCase())}{t(". A closed assignment cannot be edited.")}</p>}<div className="dialog-actions"><Button type="submit" disabled={busy} busy={busy}>{confirm?t('Confirm status change'):t('Save assignment')}</Button></div></form>}</Dialog>
}
export default function GuideAssignmentsPage(){
 useLocale();
 const [query,setQuery]=useState(''),[composing,setComposing]=useState(false),[page,setPage]=useState(1),[attempt,setAttempt]=useState(0),[state,setState]=useState({loading:true,rows:[]}),[editor,setEditor]=useState(null),[detail,setDetail]=useState(null),[notice,setNotice]=useState('')
 useEffect(()=>{if(composing)return;const c=new AbortController(),timer=setTimeout(()=>{setState(s=>({...s,loading:true}));api('/api/guide-assignments?'+new URLSearchParams({q:query,page}),undefined,{signal:c.signal}).then(r=>{if(!c.signal.aborted)setState(r)}).catch(e=>{if(!c.signal.aborted)setState({rows:[],error:errorMessage(e)})})},query?300:0);return()=>{clearTimeout(timer);c.abort()}},[query,page,attempt,composing])
 return <><div className="page-heading"><div><h1>{bilingualLabel("Booking guide assignments")}</h1><p>{t("Guide-only work for Greenview and partner tours.")}</p></div>{state.canManage&&<Button onClick={()=>setEditor({})}>{t("Assign guide")}</Button>}</div><section className="panel table-panel"><div className="filterbar"><SearchField label={bilingualLabel("Search Booking")} value={query} onChange={v=>{setQuery(v);setPage(1)}} onCompositionChange={setComposing}/><RefreshButton onClick={()=>setAttempt(n=>n+1)}/></div>{notice&&<p role="status">{t(notice)}</p>}<DataTable label={bilingualLabel("Guide assignments")} columns={['Booking','Guide','Service time','Status','Actions']} busy={state.loading} error={state.error} onRetry={()=>setAttempt(n=>n+1)} isEmpty={!state.rows.length} empty="No guide assignments found.">{state.rows.map(r=><tr key={r.id}><td>{r.booking.code}<span className="cell-sub">{r.booking.name}</span></td><td>{r.guide.displayName}</td><td>{localStamp(r.startsAt)}<span className="cell-sub">{t("to")}{' '}{localStamp(r.endsAt)}</span></td><td>{t(r.status)}</td><td><Dropdown rowActions label={bilingualLabel('Actions for {value0}', {value0:r.booking.code})} items={[{label:'View job',icon:'view',onSelect:()=>setDetail(r)},...(state.canManage&&r.status==='PLANNED'?[{label:'Edit',icon:'edit',onSelect:()=>setEditor(r)}]:[])]}/></td></tr>)}</DataTable><Pagination page={state.page||page} pageSize={25} total={state.total} busy={state.loading} onPageChange={setPage}/></section>{editor&&<Editor row={editor.id?editor:null} onClose={()=>setEditor(null)} onSaved={()=>{setEditor(null);setNotice('Guide assignment saved.');setAttempt(n=>n+1)}}/>}{detail&&<Dialog title={bilingualLabel('Guide job · {code}', {code:detail.booking.code})} onClose={()=>setDetail(null)}><dl className="catalog-details">{Object.entries({Program:detail.booking.programName,Customer:detail.booking.name,Passengers:`${t('{adults} adults · {children} children', {adults:detail.booking.adults,children:detail.booking.children})}`,Guide:detail.guide.displayName,Starts:localStamp(detail.startsAt),Ends:localStamp(detail.endsAt),Allergies:detail.booking.allergyStatus==='NONE'?'None declared':detail.booking.allergies||'Not declared',Instructions:detail.notes||'—',Status:detail.status}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'—'}</dd></div>)}</dl></Dialog>}</>
}
