import {tableHeading, translateLabel as bilingualLabel} from '../../core/i18n/runtime.js'
import { formatDate as displayDate } from '../../core/i18n/runtime.js'
import { translate as t, useLocale } from '../../core/i18n/locale.jsx'
import { DocumentHeader } from './DocumentCore.jsx'
import { Fragment } from 'react'
import { CompactBoatSheet } from './CompactBoatSheet.jsx'
import { Dropdown } from '../../core/ui/Dropdown.jsx'
import './dispatch.css'
const stamp=value=>value?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):''
const day=value=>value?displayDate(new Date(value), {timeZone:'Asia/Bangkok',day:'2-digit',month:'short',year:'numeric'}):'Not set'
const text=value=>value||'—'
const payment={PREPAID:"Before service",PAID:"Paid",COUNTER:"Pay at counter",AGENT_CREDIT:"Agent credit",AFTER_SERVICE:"Pay after service",UNSET:"Not set"}
function SheetHeader({title,code,subtitle,revision,updatedAt,date,children}){
 useLocale();
 return <header className="job-document-header"><div className="job-brand"><strong>Greenview Tour</strong><span>{subtitle}</span></div><div className="job-document-title"><h2>{bilingualLabel(title)} · {code}</h2><p>{day(date)}{' '}{t("· Thailand time")}</p><p>{t("Revision")}{' '}{revision}{updatedAt?` · Updated ${stamp(updatedAt)}`:''}</p></div><div className="job-document-context">{children}</div></header>
}
function RunTable({run}){
 useLocale();
 const boat=run.kind==='BOAT',rows=run.assignments,adults=rows.reduce((n,a)=>n+a.adults,0),children=rows.reduce((n,a)=>n+a.children,0)
 const recorded=rows.filter(a=>a.actualAdults!=null&&a.actualChildren!=null)
 const actual=recorded.reduce((n,a)=>n+a.actualAdults+a.actualChildren,0)
 return <table className="job-print-table"><colgroup>{(boat?[3,24,10,5,5,11,11,21,10]:[3,22,5,5,18,10,17,20]).map((width,i)=><col key={i} style={{width:`${width}%`}}/>)}</colgroup><thead><tr><th colSpan={boat?9:8}>Greenview Tour · {run.code} · {run.slot?.vehicle?.name} · {tableHeading(run.direction)} · {day(run.slot?.startsAt)}{' '}{tableHeading("· Revision")}{' '}{run.version}</th></tr><tr><th>{tableHeading("No.")}</th><th>{tableHeading("Agent / guest group")}</th>{boat&&<th>{tableHeading("Program")}</th>}<th>{tableHeading("Adult")}</th><th>{tableHeading("Child")}</th>{boat?<><th>{tableHeading("Arrival")}</th><th>{tableHeading("Departure")}</th><th>{tableHeading("Requests / remarks")}</th><th>{tableHeading("Actual A / C")}</th></>:<><th>{tableHeading("Hotel / room")}</th><th>{tableHeading("Pickup time")}</th><th>{tableHeading("Pickup / drop-off")}</th><th>{tableHeading("Assistance / notes / actual")}</th></>}</tr></thead><tbody>
 <tr className="job-section-row"><th colSpan={boat?9:8}>{run.direction==='RETURN'?tableHeading("Back to mainland / Return"):tableHeading("Outbound")} · {rows.length}{' '}{tableHeading("groups")}</th></tr>
 {rows.map((a,i)=><tr key={a.id}><td>{i+1}</td><td>{a.booking.agentName||t("Direct booking")}{!boat&&<div>{text(a.booking.agentPhone)}</div>}<strong className="job-cell-line">{a.booking.name}</strong><div>{a.booking.code}{a.booking.agentReference?` · ${a.booking.agentReference}`:''}</div></td>{boat&&<td>{a.booking.programName||t("Standalone service")}</td>}<td>{a.adults}</td><td>{a.children}</td>{boat?<><td>{day(a.booking.arrivalAt)}</td><td>{day(a.booking.departureAt)}</td><td>{[a.booking.allergies,...(a.booking.specialRequirements||[]),a.booking.assistance,a.booking.requestNotes,a.notes,a.changeReason].filter(Boolean).join(' · ')||t("None reported")}</td><td>{a.actualAdults==null||a.actualChildren==null?t('Not recorded'):`${a.actualAdults} / ${a.actualChildren}`}</td></>:<><td>{text(a.booking.hotel)}<div>{t("Room:")}{' '}{text(a.booking.room)}</div></td><td>{stamp(a.pickupAt)||'Time not set'}</td><td>{t("From:")}{' '}{a.booking.pickupPoint||a.booking.hotel||t("Not set")}<div>{t("To:")}{' '}{a.dropoffPoint||a.booking.dropoffPoint||t("Not set")}</div></td><td>{[a.booking.assistance,a.notes].filter(Boolean).join(' · ')||t("None reported")}<div>{t("Actual A / C:")}{' '}{a.actualAdults==null||a.actualChildren==null?t('Not recorded'):`${a.actualAdults} / ${a.actualChildren}`}</div>{a.changeReason&&<div>{a.changeReason}</div>}</td></>}</tr>)}
 <tr className="job-total-row"><th colSpan={boat?3:2}>{tableHeading("Total planned")}</th><td>{adults}</td><td>{children}</td><td colSpan={4}>{adults+children}{' '}{t("passengers · Actual:")}{' '}{recorded.length?`${actual} passengers (${recorded.length}/${rows.length} groups recorded)`:t('Not recorded')}</td></tr>
 </tbody></table>
}
export function JobSheet({run,canManage,onCommand}){
 useLocale();
 return <section className="job-sheet"><SheetHeader title={run.kind==='BOAT'?bilingualLabel('Boat Job Order'):bilingualLabel('Transfer Job Order')} code={run.code} subtitle={`${run.slot?.vehicle?.name||'No vehicle'} · ${run.name}`} revision={run.version} updatedAt={run.updatedAt} date={run.slot?.startsAt}>
 <p><strong>{run.direction==='RETURN'?t("Back to mainland / Return"):t("Outbound")}</strong> · {run.period} · {stamp(run.slot?.startsAt)} — {stamp(run.slot?.endsAt)}</p>
 <p>{run.staff.map(p=>`${p.name} (${p.role.replaceAll('_',' ')})`).join(' · ')||t("No staff assigned")}</p>
 <p>{run.assignments.reduce((n,a)=>n+a.adults+a.children,0)}{' '}{t("passengers /")}{' '}{run.capacity}{' '}{t("capacity")}</p>
 </SheetHeader><div className="job-lines">{run.assignments.map(a=><article className="job-group" key={a.id}><h3>{a.booking.name} <small>{a.booking.code}</small></h3><dl><dt>{bilingualLabel("Agent")}</dt><dd>{a.booking.agentName||'Direct'}{run.kind==='VEHICLE'&&a.booking.agentPhone?` · ${a.booking.agentPhone}`:''}</dd><dt>{bilingualLabel("Passengers")}</dt><dd>{a.adults}{' '}{t("adults ·")}{' '}{a.children}{' '}{t("children")}</dd><dt>{bilingualLabel("Actual")}</dt><dd>{a.actualAdults==null?t('Not recorded'):`${a.actualAdults} adults · ${a.actualChildren} children`}{a.changeReason?` · ${a.changeReason}`:''}</dd>{run.kind==='BOAT'?<><dt>{bilingualLabel("Program")}</dt><dd>{a.booking.programName||t("Standalone service")}</dd><dt>{bilingualLabel("Arrival / departure")}</dt><dd>{day(a.booking.arrivalAt)} / {day(a.booking.departureAt)}</dd><dt>{bilingualLabel("Allergies / assistance")}</dt><dd>{[a.booking.allergies,a.booking.assistance].filter(Boolean).join(' · ')||t("None reported")}</dd></>:<><dt>{bilingualLabel("Hotel / room")}</dt><dd>{[a.booking.hotel,a.booking.room].filter(Boolean).join(' · ')||t("Not set")}</dd><dt>{bilingualLabel("Pickup")}</dt><dd>{stamp(a.pickupAt)||'Time not set'} · {a.booking.pickupPoint||a.booking.hotel||t("Point not set")}</dd><dt>{bilingualLabel("Drop-off")}</dt><dd>{a.dropoffPoint||a.booking.dropoffPoint||t("Not set")}</dd></>}<dt>{bilingualLabel("Requests / notes")}</dt><dd>{[run.kind==='VEHICLE'?a.booking.assistance:a.booking.requestNotes,a.notes].filter(Boolean).join(' · ')||'None'}</dd></dl>{canManage&&<div className="job-actions"><Dropdown rowActions label={bilingualLabel("Actions for {value0}", {value0: a.booking.code})} items={[{label:'Record actual passengers',icon:'edit',onSelect:()=>onCommand(a,'ACTUAL')},{label:'Remove assignment',icon:'close',danger:true,onSelect:()=>onCommand(a,'REMOVE')}]}/></div>}</article>)}</div><RunTable run={run}/>{!run.assignments.length&&<p>{t("No bookings assigned to this run.")}</p>}</section>
}

export function BoatDailySheet({runs}) { return <CompactBoatSheet runs={runs}/> }

export function BookingSheet({booking:b}){
 useLocale();
 const assignments=(b.lines||[]).filter(l=>l.selected!==false).flatMap(l=>(l.dispatchAssignments||[]).map(a=>({...a,service:l.snapshot?.name||l.resource?.name})))
 const selected=(b.lines||[]).filter(l=>l.selected!==false)
 const fields=[['Agent',b.agentName||b.agent?.name||'Direct booking'],['Agent reference',b.agentReference],['Guest phone',b.contactPhone],['Hotel / room',[b.hotel,b.room].filter(Boolean).join(' · ')],['Arrival / departure',`${day(b.outboundDate)} / ${b.returnStatus==='PENDING'?'Waiting for date':b.returnStatus==='OTHER'||b.returnStatus==='NONE'?'Not with Greenview':day(b.returnDate)}`],['Payment terms',payment[b.paymentTerms]||'Not set'],['After-service reason',b.afterServiceReason],['Pickup point',b.pickupPoint],['Drop-off point',b.dropoffPoint],['Allergies',b.allergies||({NONE:'None reported',UNKNOWN:'Not checked'}[b.allergyStatus])],['Special requirements',(b.specialRequirements||[]).join(' · ')],['Assistance',b.assistance],['Requests',b.requestNotes]]
 return <section className="job-sheet booking-sheet"><SheetHeader title={bilingualLabel("Booking Job Order")} code={b.code} subtitle={b.trip?.name||'Standalone services'} revision={b.version} updatedAt={b.updatedAt} date={b.trip?.startsAt}><p><strong>{b.name}</strong> · {b.adults}{' '}{t("adults ·")}{' '}{b.children}{' '}{t("children ·")}{' '}{b.adults+b.children}{' '}{t("passengers")}</p><p>{t("Status:")}{' '}{t(b.status)} · {payment[b.paymentTerms]||t("Payment terms not set")}</p></SheetHeader>
 <div className="booking-facts">{fields.filter(([,value])=>value).map(([label,value])=><div key={label}><strong>{t(label)}</strong><span>{value}</span></div>)}</div>
 <h3>{bilingualLabel("Assigned boats and vehicles")}</h3>
 {assignments.length?<><div className="job-lines">{assignments.map(a=><article className="job-group" key={a.id}><h3>{a.run.slot?.vehicle?.name||a.run.name}</h3><dl><dt>{bilingualLabel("Run / direction")}</dt><dd>{a.run.code} · {t(a.run.direction)}</dd><dt>{bilingualLabel("Passengers")}</dt><dd>{a.adults}{' '}{t("adults ·")}{' '}{a.children}{' '}{t("children")}</dd><dt>{bilingualLabel("Time")}</dt><dd>{stamp(a.pickupAt||a.run.slot?.startsAt)||t("Not set")}</dd><dt>{bilingualLabel("Service")}</dt><dd>{a.service}</dd></dl></article>)}</div><table className="job-print-table"><thead><tr><th colSpan="6">{tableHeading("Booking")}{' '}{b.code}{' '}{tableHeading("· Handoff · Revision")}{' '}{b.version}</th></tr><tr><th>{tableHeading("Boat / vehicle")}</th><th>{tableHeading("Run / direction")}</th><th>{tableHeading("Adults")}</th><th>{tableHeading("Children")}</th><th>{tableHeading("Pickup / run time")}</th><th>{tableHeading("Service")}</th></tr></thead><tbody>{assignments.map(a=><tr key={a.id}><td>{a.run.kind==='BOAT'?t('Boat'):t('Vehicle')} · {a.run.slot?.vehicle?.name||a.run.name}</td><td>{a.run.code} · {t(a.run.direction)}</td><td>{a.adults}</td><td>{a.children}</td><td>{stamp(a.pickupAt||a.run.slot?.startsAt)||t("Not set")}</td><td>{a.service}</td></tr>)}</tbody></table></>:<p>{t("No boat or vehicle allocation yet. Guide and Head Driver arrange these separately.")}</p>}
 {selected.filter(l=>['TRANSFER','TOUR_BOAT','LONGTAIL_BOAT'].includes(l.resource?.category||l.snapshot?.category)).map(l=><Fragment key={l.id}>{(l.dispatchDirection==='BOTH'||!l.dispatchDirection?['OUTBOUND','RETURN']:[l.dispatchDirection]).map(direction=>{const links=(l.dispatchAssignments||[]).filter(a=>a.run.direction===direction),adults=links.reduce((n,a)=>n+a.adults,0),children=links.reduce((n,a)=>n+a.children,0);return adults<b.adults||children<b.children?<p className="job-pending" key={direction}>{l.snapshot?.name||l.resource?.name} · {direction}{t(": Waiting for allocation —")}{' '}{Math.max(0,b.adults-adults)}{' '}{t("adults /")}{' '}{Math.max(0,b.children-children)}{' '}{t("children.")}</p>:null})}</Fragment>)}
 <h3>{bilingualLabel("Selected services and supplies")}</h3><div className="booking-services">{selected.map((l,i)=><p key={l.id||i}>{l.snapshot?.name||l.resource?.name||t("Resource")} · {l.quantity} {l.snapshot?.baseUnit||l.resource?.baseUnit} · {l.usagePoint||'Unspecified'}</p>)}{!selected.length&&<p>{t("No selected services.")}</p>}</div>
 <p className="job-signoff">{t("Check-in: ____________________   Handed to Guide: ____________________   Time: __________")}</p><p className="job-footnote">{t("Operational handoff copy. Check-in and handoff spaces are for handwritten confirmation.")}</p></section>
}
