import { Fragment } from 'react'
import { Dropdown } from '../../core/ui/Dropdown.jsx'
import './dispatch.css'
const stamp=value=>value?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):''
const day=value=>value?new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',day:'2-digit',month:'short',year:'numeric'}).format(new Date(value)):'Not set'
const text=value=>value||'—'
const payment={PAID:'Paid · ชำระแล้ว',COUNTER:'Pay at counter · ชำระวันบริการ',AGENT_CREDIT:'Agent credit · เครดิตเอเย่นต์',AFTER_SERVICE:'Pay after service · ชำระหลังบริการ',UNSET:'Not set · ยังไม่ระบุ'}
function SheetHeader({title,code,subtitle,revision,updatedAt,date,children}){
 return <header className="job-document-header"><div className="job-brand"><strong>Greenview Tour</strong><span>{subtitle}</span></div><div className="job-document-title"><h2>{title} · {code}</h2><p>{day(date)} · Thailand time</p><p>Revision {revision}{updatedAt?` · Updated ${stamp(updatedAt)}`:''}</p></div><div className="job-document-context">{children}</div></header>
}
function RunTable({run}){
 const boat=run.kind==='BOAT',rows=run.assignments,adults=rows.reduce((n,a)=>n+a.adults,0),children=rows.reduce((n,a)=>n+a.children,0)
 const recorded=rows.filter(a=>a.actualAdults!=null&&a.actualChildren!=null)
 const actual=recorded.reduce((n,a)=>n+a.actualAdults+a.actualChildren,0)
 return <table className="job-print-table"><colgroup>{(boat?[3,24,10,5,5,11,11,21,10]:[3,22,5,5,18,10,17,20]).map((width,i)=><col key={i} style={{width:`${width}%`}}/>)}</colgroup><thead><tr><th colSpan={boat?9:8}>Greenview Tour · {run.code} · {run.slot?.vehicle?.name} · {run.direction} · {day(run.slot?.startsAt)} · Revision {run.version}</th></tr><tr><th>No.</th><th>Agent / guest group</th>{boat&&<th>Program</th>}<th>Adult</th><th>Child</th>{boat?<><th>Arrival</th><th>Departure</th><th>Requests / remarks</th><th>Actual A / C</th></>:<><th>Hotel / room</th><th>Pickup time</th><th>Pickup / drop-off</th><th>Assistance / notes / actual</th></>}</tr></thead><tbody>
 <tr className="job-section-row"><th colSpan={boat?9:8}>{run.direction==='RETURN'?'Back to mainland / Return · ขากลับ':'Outbound · ขาไป'} · {rows.length} groups</th></tr>
 {rows.map((a,i)=><tr key={a.id}><td>{i+1}</td><td>{a.booking.agentName||'Direct booking'}{!boat&&<div>{text(a.booking.agentPhone)}</div>}<strong className="job-cell-line">{a.booking.name}</strong><div>{a.booking.code}{a.booking.agentReference?` · ${a.booking.agentReference}`:''}</div></td>{boat&&<td>{a.booking.programName||'Standalone service'}</td>}<td>{a.adults}</td><td>{a.children}</td>{boat?<><td>{day(a.booking.arrivalAt)}</td><td>{day(a.booking.departureAt)}</td><td>{[a.booking.allergies,a.booking.assistance,a.booking.requestNotes,a.notes,a.changeReason].filter(Boolean).join(' · ')||'None reported'}</td><td>{a.actualAdults==null||a.actualChildren==null?'Not recorded':`${a.actualAdults} / ${a.actualChildren}`}</td></>:<><td>{text(a.booking.hotel)}<div>Room: {text(a.booking.room)}</div></td><td>{stamp(a.pickupAt)||'Time not set'}</td><td>From: {a.booking.pickupPoint||a.booking.hotel||'Not set'}<div>To: {a.dropoffPoint||a.booking.dropoffPoint||'Not set'}</div></td><td>{[a.booking.assistance,a.notes].filter(Boolean).join(' · ')||'None reported'}<div>Actual A / C: {a.actualAdults==null||a.actualChildren==null?'Not recorded':`${a.actualAdults} / ${a.actualChildren}`}</div>{a.changeReason&&<div>{a.changeReason}</div>}</td></>}</tr>)}
 <tr className="job-total-row"><th colSpan={boat?3:2}>Total planned · รวม</th><td>{adults}</td><td>{children}</td><td colSpan={4}>{adults+children} passengers · Actual: {recorded.length?`${actual} passengers (${recorded.length}/${rows.length} groups recorded)`:'Not recorded'}</td></tr>
 </tbody></table>
}
export function JobSheet({run,canManage,onCommand}){
 return <section className="job-sheet"><SheetHeader title={run.kind==='BOAT'?'Boat Job Order':'Transfer Job Order'} code={run.code} subtitle={`${run.slot?.vehicle?.name||'No vehicle'} · ${run.name}`} revision={run.version} updatedAt={run.updatedAt} date={run.slot?.startsAt}>
 <p><strong>{run.direction==='RETURN'?'Back to mainland / Return · ขากลับ':'Outbound · ขาไป'}</strong> · {run.period} · {stamp(run.slot?.startsAt)} — {stamp(run.slot?.endsAt)}</p>
 <p>{run.staff.map(p=>`${p.name} (${p.role.replaceAll('_',' ')})`).join(' · ')||'No staff assigned'}</p>
 <p>{run.assignments.reduce((n,a)=>n+a.adults+a.children,0)} passengers / {run.capacity} capacity</p>
 </SheetHeader><div className="job-lines">{run.assignments.map(a=><article className="job-group" key={a.id}><h3>{a.booking.name} <small>{a.booking.code}</small></h3><dl><dt>Agent</dt><dd>{a.booking.agentName||'Direct'}{run.kind==='VEHICLE'&&a.booking.agentPhone?` · ${a.booking.agentPhone}`:''}</dd><dt>Passengers</dt><dd>{a.adults} adults · {a.children} children</dd><dt>Actual</dt><dd>{a.actualAdults==null?'Not recorded':`${a.actualAdults} adults · ${a.actualChildren} children`}{a.changeReason?` · ${a.changeReason}`:''}</dd>{run.kind==='BOAT'?<><dt>Program</dt><dd>{a.booking.programName||'Standalone service'}</dd><dt>Arrival / departure</dt><dd>{day(a.booking.arrivalAt)} / {day(a.booking.departureAt)}</dd><dt>Allergies / assistance</dt><dd>{[a.booking.allergies,a.booking.assistance].filter(Boolean).join(' · ')||'None reported'}</dd></>:<><dt>Hotel / room</dt><dd>{[a.booking.hotel,a.booking.room].filter(Boolean).join(' · ')||'Not set'}</dd><dt>Pickup</dt><dd>{stamp(a.pickupAt)||'Time not set'} · {a.booking.pickupPoint||a.booking.hotel||'Point not set'}</dd><dt>Drop-off</dt><dd>{a.dropoffPoint||a.booking.dropoffPoint||'Not set'}</dd></>}<dt>Requests / notes</dt><dd>{[run.kind==='VEHICLE'?a.booking.assistance:a.booking.requestNotes,a.notes].filter(Boolean).join(' · ')||'None'}</dd></dl>{canManage&&<div className="job-actions"><Dropdown label={`Actions for ${a.booking.code}`} items={[{label:'Record actual passengers',icon:'edit',onSelect:()=>onCommand(a,'ACTUAL')},{label:'Remove assignment',icon:'close',danger:true,onSelect:()=>onCommand(a,'REMOVE')}]}><span aria-hidden="true">⋯</span></Dropdown></div>}</article>)}</div><RunTable run={run}/>{!run.assignments.length&&<p>No bookings assigned to this run.</p>}</section>
}

export function BookingSheet({booking:b}){
 const assignments=(b.lines||[]).filter(l=>l.selected!==false).flatMap(l=>(l.dispatchAssignments||[]).map(a=>({...a,service:l.snapshot?.name||l.resource?.name})))
 const selected=(b.lines||[]).filter(l=>l.selected!==false)
 const fields=[['Agent',b.agentName||b.agent?.name||'Direct booking'],['Agent reference',b.agentReference],['Guest phone',b.contactPhone],['Hotel / room',[b.hotel,b.room].filter(Boolean).join(' · ')],['Arrival / departure',`${day(b.trip?.startsAt)} / ${day(b.trip?.endsAt)}`],['Payment terms',payment[b.paymentTerms]||'Not set'],['After-service reason',b.afterServiceReason],['Pickup point',b.pickupPoint],['Drop-off point',b.dropoffPoint],['Allergies',b.allergies],['Assistance',b.assistance],['Requests',b.requestNotes]]
 return <section className="job-sheet booking-sheet"><SheetHeader title="Booking Job Order" code={b.code} subtitle={b.trip?.name||'Standalone services'} revision={b.version} updatedAt={b.updatedAt} date={b.trip?.startsAt}><p><strong>{b.name}</strong> · {b.adults} adults · {b.children} children · {b.adults+b.children} passengers</p><p>Status: {b.status} · {payment[b.paymentTerms]||'Payment terms not set'}</p></SheetHeader>
 <div className="booking-facts">{fields.filter(([,value])=>value).map(([label,value])=><div key={label}><strong>{label}</strong><span>{value}</span></div>)}</div>
 <h3>Assigned boats and vehicles · ส่งต่อลูกค้า</h3>
 {assignments.length?<><div className="job-lines">{assignments.map(a=><article className="job-group" key={a.id}><h3>{a.run.slot?.vehicle?.name||a.run.name}</h3><dl><dt>Run / direction</dt><dd>{a.run.code} · {a.run.direction}</dd><dt>Passengers</dt><dd>{a.adults} adults · {a.children} children</dd><dt>Time</dt><dd>{stamp(a.pickupAt||a.run.slot?.startsAt)||'Not set'}</dd><dt>Service</dt><dd>{a.service}</dd></dl></article>)}</div><table className="job-print-table"><thead><tr><th colSpan="6">Booking {b.code} · Handoff · Revision {b.version}</th></tr><tr><th>Boat / vehicle</th><th>Run / direction</th><th>Adults</th><th>Children</th><th>Pickup / run time</th><th>Service</th></tr></thead><tbody>{assignments.map(a=><tr key={a.id}><td>{a.run.kind==='BOAT'?'Boat':'Vehicle'} · {a.run.slot?.vehicle?.name||a.run.name}</td><td>{a.run.code} · {a.run.direction}</td><td>{a.adults}</td><td>{a.children}</td><td>{stamp(a.pickupAt||a.run.slot?.startsAt)||'Not set'}</td><td>{a.service}</td></tr>)}</tbody></table></>:<p>No boat or vehicle allocation yet. Guide and Head Driver arrange these separately.</p>}
 {selected.filter(l=>['TRANSFER','TOUR_BOAT','LONGTAIL_BOAT'].includes(l.resource?.category||l.snapshot?.category)).map(l=><Fragment key={l.id}>{(l.dispatchDirection==='BOTH'||!l.dispatchDirection?['OUTBOUND','RETURN']:[l.dispatchDirection]).map(direction=>{const links=(l.dispatchAssignments||[]).filter(a=>a.run.direction===direction),adults=links.reduce((n,a)=>n+a.adults,0),children=links.reduce((n,a)=>n+a.children,0);return adults<b.adults||children<b.children?<p className="job-pending" key={direction}>{l.snapshot?.name||l.resource?.name} · {direction}: Waiting for allocation — {Math.max(0,b.adults-adults)} adults / {Math.max(0,b.children-children)} children.</p>:null})}</Fragment>)}
 <h3>Selected services and supplies</h3><div className="booking-services">{selected.map((l,i)=><p key={l.id||i}>{l.snapshot?.name||l.resource?.name||'Resource'} · {l.quantity} {l.snapshot?.baseUnit||l.resource?.baseUnit} · {l.usagePoint||'Unspecified'}</p>)}{!selected.length&&<p>No selected services.</p>}</div>
 <p className="job-signoff">Check-in: ____________________ &nbsp; Handed to Guide: ____________________ &nbsp; Time: __________</p><p className="job-footnote">Operational handoff copy. Check-in and handoff spaces are for handwritten confirmation.</p></section>
}
