import {translateLabel as bilingualLabel} from '../../core/i18n/runtime.js'
import { formatDate as displayDate } from '../../core/i18n/runtime.js'
import { translate as t, useLocale } from '../../core/i18n/locale.jsx'
import { DocumentHeader } from './DocumentCore.jsx'
import { Fragment } from 'react'
import { programSummary } from '../../../../../packages/contracts/job-summary.js'
import { Dropdown } from '../../core/ui/Dropdown.jsx'
import './dispatch.css'
const stamp=value=>value?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):''
const day=value=>value?displayDate(new Date(value), {timeZone:'Asia/Bangkok',day:'2-digit',month:'short',year:'numeric'}):'Not set'
const text=value=>value||'—'
const payment={PREPAID:"Before service",PAID:"Paid",COUNTER:"Pay at counter",AGENT_CREDIT:"Agent credit",AFTER_SERVICE:"Pay after service",UNSET:"Not set"}
function SheetHeader({title,code,subtitle,revision,updatedAt,date,children}){
 useLocale();
 return <header className="job-document-header"><div className="job-brand"><strong>Greenview Tour</strong><span>{subtitle}</span></div><div className="job-document-title"><h2>{bilingualLabel(title)} · {code}</h2><p>{day(date)}{' '}{t("· Thailand time")}</p><p>{t("Revision")}{' '}{revision}{updatedAt?` · Updated ${stamp(updatedAt)}`:''}</p></div><div className="job-document-context">{children}</div></header>
}
function RunTable({run}){
 useLocale();
 const boat=run.kind==='BOAT',rows=run.assignments,adults=rows.reduce((n,a)=>n+a.adults,0),children=rows.reduce((n,a)=>n+a.children,0)
 const recorded=rows.filter(a=>a.actualAdults!=null&&a.actualChildren!=null)
 const actual=recorded.reduce((n,a)=>n+a.actualAdults+a.actualChildren,0)
 return <table className="job-print-table"><colgroup>{(boat?[3,24,10,5,5,11,11,21,10]:[3,22,5,5,18,10,17,20]).map((width,i)=><col key={i} style={{width:`${width}%`}}/>)}</colgroup><thead><tr><th colSpan={boat?9:8}>Greenview Tour · {run.code} · {run.slot?.vehicle?.name} · {bilingualLabel(run.direction)} · {day(run.slot?.startsAt)}{' '}{bilingualLabel("· Revision")}{' '}{run.version}</th></tr><tr><th>{bilingualLabel("No.")}</th><th>{bilingualLabel("Agent / guest group")}</th>{boat&&<th>{bilingualLabel("Program")}</th>}<th>{bilingualLabel("Adult")}</th><th>{bilingualLabel("Child")}</th>{boat?<><th>{bilingualLabel("Arrival")}</th><th>{bilingualLabel("Departure")}</th><th>{bilingualLabel("Requests / remarks")}</th><th>{bilingualLabel("Actual A / C")}</th></>:<><th>{bilingualLabel("Hotel / room")}</th><th>{bilingualLabel("Pickup time")}</th><th>{bilingualLabel("Pickup / drop-off")}</th><th>{bilingualLabel("Assistance / notes / actual")}</th></>}</tr></thead><tbody>
 <tr className="job-section-row"><th colSpan={boat?9:8}>{run.direction==='RETURN'?bilingualLabel("Back to mainland / Return"):bilingualLabel("Outbound")} · {rows.length}{' '}{bilingualLabel("groups")}</th></tr>
 {rows.map((a,i)=><tr key={a.id}><td>{i+1}</td><td>{a.booking.agentName||t("Direct booking")}{!boat&&<div>{text(a.booking.agentPhone)}</div>}<strong className="job-cell-line">{a.booking.name}</strong><div>{a.booking.code}{a.booking.agentReference?` · ${a.booking.agentReference}`:''}</div></td>{boat&&<td>{a.booking.programName||t("Standalone service")}</td>}<td>{a.adults}</td><td>{a.children}</td>{boat?<><td>{day(a.booking.arrivalAt)}</td><td>{day(a.booking.departureAt)}</td><td>{[a.booking.allergies,...(a.booking.specialRequirements||[]),a.booking.assistance,a.booking.requestNotes,a.notes,a.changeReason].filter(Boolean).join(' · ')||t("None reported")}</td><td>{a.actualAdults==null||a.actualChildren==null?t('Not recorded'):`${a.actualAdults} / ${a.actualChildren}`}</td></>:<><td>{text(a.booking.hotel)}<div>{t("Room:")}{' '}{text(a.booking.room)}</div></td><td>{stamp(a.pickupAt)||'Time not set'}</td><td>{t("From:")}{' '}{a.booking.pickupPoint||a.booking.hotel||t("Not set")}<div>{t("To:")}{' '}{a.dropoffPoint||a.booking.dropoffPoint||t("Not set")}</div></td><td>{[a.booking.assistance,a.notes].filter(Boolean).join(' · ')||t("None reported")}<div>{t("Actual A / C:")}{' '}{a.actualAdults==null||a.actualChildren==null?t('Not recorded'):`${a.actualAdults} / ${a.actualChildren}`}</div>{a.changeReason&&<div>{a.changeReason}</div>}</td></>}</tr>)}
 <tr className="job-total-row"><th colSpan={boat?3:2}>{bilingualLabel("Total planned")}</th><td>{adults}</td><td>{children}</td><td colSpan={4}>{adults+children}{' '}{t("passengers · Actual:")}{' '}{recorded.length?`${actual} passengers (${recorded.length}/${rows.length} groups recorded)`:t('Not recorded')}</td></tr>
 </tbody></table>
}
export function JobSheet({run,canManage,onCommand}){
 useLocale();
 return <section className="job-sheet"><SheetHeader title={run.kind==='BOAT'?bilingualLabel('Boat Job Order'):bilingualLabel('Transfer Job Order')} code={run.code} subtitle={`${run.slot?.vehicle?.name||'No vehicle'} · ${run.name}`} revision={run.version} updatedAt={run.updatedAt} date={run.slot?.startsAt}>
 <p><strong>{run.direction==='RETURN'?t("Back to mainland / Return"):t("Outbound")}</strong> · {run.period} · {stamp(run.slot?.startsAt)} — {stamp(run.slot?.endsAt)}</p>
 <p>{run.staff.map(p=>`${p.name} (${p.role.replaceAll('_',' ')})`).join(' · ')||t("No staff assigned")}</p>
 <p>{run.assignments.reduce((n,a)=>n+a.adults+a.children,0)}{' '}{t("passengers /")}{' '}{run.capacity}{' '}{t("capacity")}</p>
 </SheetHeader><div className="job-lines">{run.assignments.map(a=><article className="job-group" key={a.id}><h3>{a.booking.name} <small>{a.booking.code}</small></h3><dl><dt>{bilingualLabel("Agent")}</dt><dd>{a.booking.agentName||'Direct'}{run.kind==='VEHICLE'&&a.booking.agentPhone?` · ${a.booking.agentPhone}`:''}</dd><dt>{bilingualLabel("Passengers")}</dt><dd>{a.adults}{' '}{t("adults ·")}{' '}{a.children}{' '}{t("children")}</dd><dt>{bilingualLabel("Actual")}</dt><dd>{a.actualAdults==null?t('Not recorded'):`${a.actualAdults} adults · ${a.actualChildren} children`}{a.changeReason?` · ${a.changeReason}`:''}</dd>{run.kind==='BOAT'?<><dt>{bilingualLabel("Program")}</dt><dd>{a.booking.programName||t("Standalone service")}</dd><dt>{bilingualLabel("Arrival / departure")}</dt><dd>{day(a.booking.arrivalAt)} / {day(a.booking.departureAt)}</dd><dt>{bilingualLabel("Allergies / assistance")}</dt><dd>{[a.booking.allergies,a.booking.assistance].filter(Boolean).join(' · ')||t("None reported")}</dd></>:<><dt>{bilingualLabel("Hotel / room")}</dt><dd>{[a.booking.hotel,a.booking.room].filter(Boolean).join(' · ')||t("Not set")}</dd><dt>{bilingualLabel("Pickup")}</dt><dd>{stamp(a.pickupAt)||'Time not set'} · {a.booking.pickupPoint||a.booking.hotel||t("Point not set")}</dd><dt>{bilingualLabel("Drop-off")}</dt><dd>{a.dropoffPoint||a.booking.dropoffPoint||t("Not set")}</dd></>}<dt>{bilingualLabel("Requests / notes")}</dt><dd>{[run.kind==='VEHICLE'?a.booking.assistance:a.booking.requestNotes,a.notes].filter(Boolean).join(' · ')||'None'}</dd></dl>{canManage&&<div className="job-actions"><Dropdown rowActions label={bilingualLabel("Actions for {value0}", {value0: a.booking.code})} items={[{label:'Record actual passengers',icon:'edit',onSelect:()=>onCommand(a,'ACTUAL')},{label:'Remove assignment',icon:'close',danger:true,onSelect:()=>onCommand(a,'REMOVE')}]}/></div>}</article>)}</div><RunTable run={run}/>{!run.assignments.length&&<p>{t("No bookings assigned to this run.")}</p>}</section>
}

const shortDay=value=>value?displayDate(new Date(value), {timeZone:'Asia/Bangkok',day:'2-digit',month:'2-digit'}):'—'
const crewRoles=[["Captain",['CAPTAIN','HEAD_CAPTAIN']],["Assistant captain",['ASSISTANT_CAPTAIN']],["Guide",['GUIDE','HEAD_GUIDE']],["Assistant guide",['ASSISTANT_TOUR_GUIDE']]]
export function BoatDailySheet({runs}){
 useLocale();
 const first=runs[0]
 if(!first)return null
 const date=day(first.slot?.startsAt),vehicle=first.slot?.vehicle
 const documentCode=`BOAT-${vehicle?.id?.slice(0,8)||first.code}-${stamp(first.slot?.startsAt).slice(0,10).replaceAll('-','')}`
 const crew=roles=>{
  const values=runs.map(run=>[...new Set(run.staff.filter(p=>roles.includes(p.role)).map(p=>p.name))].map((name,i)=>`${i+1}. ${name}`).join(' / ')||'________________')
  return new Set(values).size===1?values[0]:runs.map((run,i)=>`${run.direction==='RETURN'?"Return":"Outbound"} ${stamp(run.slot?.startsAt).slice(11)}: ${values[i]}`).join(' / ')
 }
 return <section className="job-sheet boat-daily-sheet">
  <DocumentHeader title={bilingualLabel("BOAT JOB ORDER")} code={documentCode} date={date}/><header className="boat-daily-header">
   <div className="boat-daily-identity"><p><strong>{t("Boat:")}</strong> {vehicle?.name||t("Not assigned")}</p><div className="boat-crew">{crewRoles.map(([label,roles])=><p key={label}><strong>{t(label)}:</strong> {crew(roles)}</p>)}</div></div>
   <div className="boat-daily-reference"><p><strong>{t("Document no.:")}</strong><br/>{documentCode}</p><p><strong>{t("Date:")}</strong> {date}</p><span>{t("Outbound + return")}</span></div>
  </header>
  <div className="boat-daily-cards">{runs.map(run=><JobSheet key={run.id} run={run} canManage={false}/>)}</div>
  <table className="job-print-table boat-daily-table"><colgroup>{[3,9,16,12,10,4,4,6,6,24,6].map((width,i)=><col key={i} style={{width:`${width}%`}}/>)}</colgroup>
   <thead><tr className="boat-repeat-title"><th colSpan="11">{vehicle?.name} · {documentCode} · {date}</th></tr><tr><th>{bilingualLabel("No.")}</th><th>{bilingualLabel("Agent")}</th><th>{bilingualLabel("Guest group")}</th><th>{bilingualLabel("Booking / Reference")}</th><th>{bilingualLabel("Program")}</th><th>{bilingualLabel("Adult")}<br/>{bilingualLabel("Adults")}</th><th>{bilingualLabel("Child")}<br/>{bilingualLabel("Children")}</th><th>{bilingualLabel("Arrival")}<br/>{bilingualLabel("Arrival date")}</th><th>{bilingualLabel("Departure")}<br/>{bilingualLabel("Return date")}</th><th>{bilingualLabel("Requests / remarks")}</th><th>{bilingualLabel("Actual")}<br/>{bilingualLabel("Actual A/C")}</th></tr></thead>
   <tbody>{['OUTBOUND','RETURN'].map(direction=>{
    const selected=runs.filter(r=>r.direction===direction),rows=selected.flatMap(run=>run.assignments.map(a=>({...a,run}))).sort((a,b)=>a.booking.code.localeCompare(b.booking.code))
    const adults=rows.reduce((n,a)=>n+a.adults,0),children=rows.reduce((n,a)=>n+a.children,0),recorded=rows.filter(a=>a.actualAdults!=null&&a.actualChildren!=null)
    return <Fragment key={direction}><tr className="job-section-row"><th colSpan="11">{direction==='OUTBOUND'?bilingualLabel("Outbound"):bilingualLabel("Return")} · {rows.length}{' '}{bilingualLabel("groups")}{' '}{selected.map(r=>` · ${stamp(r.slot?.startsAt).slice(11)} (${r.code}, rev. ${r.version})`).join('')}</th></tr>
     {rows.map((a,i)=><tr key={a.id}><td>{i+1}</td><td>{a.booking.agentName||t("Direct booking")}</td><td><strong>{a.booking.name}</strong></td><td className="boat-booking-ref">{a.booking.code}{a.booking.agentReference?<div>{a.booking.agentReference}</div>:null}</td><td>{a.booking.programName||t("Standalone service")}</td><td>{a.adults}</td><td>{a.children}</td><td>{shortDay(a.booking.arrivalAt)}</td><td>{shortDay(a.booking.departureAt)}</td><td>{[a.booking.allergies,...(a.booking.specialRequirements||[]),a.booking.assistance,a.booking.requestNotes,a.notes,a.changeReason].filter(Boolean).join(' · ')||'—'}</td><td>{a.actualAdults==null||a.actualChildren==null?'—':`${a.actualAdults}/${a.actualChildren}`}</td></tr>)}
     {!rows.length&&<tr><td colSpan="11">{t("No bookings assigned")}</td></tr>}
     <tr className="job-total-row"><th colSpan="5">{direction==='OUTBOUND'?bilingualLabel("Outbound total"):bilingualLabel("Return total")}</th><td>{adults}</td><td>{children}</td><td colSpan="4">{adults+children}{' '}{t("passengers · Actual:")}{' '}{recorded.length?`${recorded.reduce((n,a)=>n+a.actualAdults+a.actualChildren,0)} (${recorded.length}/${rows.length} groups)`:t('Not recorded')}</td></tr>
    </Fragment>
   })}</tbody>
  </table><div className="boat-program-summaries">{['OUTBOUND','RETURN'].map(direction=>{
   const programs=programSummary(runs,direction),total=programs.reduce((n,p)=>n+p.passengers,0)
   const directionRuns=runs.filter(r=>r.direction===direction),crewCounts=directionRuns.map(r=>r.staff.length)
   const crewCount=crewCounts.length?new Set(crewCounts).size===1?String(crewCounts[0]):crewCounts.join(' / '):'0'
   return <section className="boat-program-summary" key={direction}><h3>{direction==='OUTBOUND'?bilingualLabel("Outbound packages"):bilingualLabel("Return packages")}</h3><table><thead><tr><th>{bilingualLabel("Program")}</th><th>{bilingualLabel("Adult")}</th><th>{bilingualLabel("Child")}</th><th>{bilingualLabel("Total passengers")}</th></tr></thead><tbody>{programs.map(p=><tr key={p.key}><td>{p.name}</td><td>{p.adults}</td><td>{p.children}</td><td><strong>{p.passengers}</strong></td></tr>)}<tr className="job-total-row"><th>{bilingualLabel("All programs")}</th><td>{programs.reduce((n,p)=>n+p.adults,0)}</td><td>{programs.reduce((n,p)=>n+p.children,0)}</td><td><strong>{total}</strong></td></tr></tbody></table><p>{t("Crew")}{' '}{crewCount}{' '}{t("Passengers per run · planned boat total")}{' '}{directionRuns.map(r=>r.assignments.reduce((n,a)=>n+a.adults+a.children,0)+r.staff.length).join(' / ')||0}{' '}{t("Passengers per run")}</p></section>
  })}</div><p className="boat-daily-legend">{t("A/C = Adult/Child — = Actual not recorded · Thailand time")}</p>
 </section>
}

export function BookingSheet({booking:b}){
 useLocale();
 const assignments=(b.lines||[]).filter(l=>l.selected!==false).flatMap(l=>(l.dispatchAssignments||[]).map(a=>({...a,service:l.snapshot?.name||l.resource?.name})))
 const selected=(b.lines||[]).filter(l=>l.selected!==false)
 const fields=[['Agent',b.agentName||b.agent?.name||'Direct booking'],['Agent reference',b.agentReference],['Guest phone',b.contactPhone],['Hotel / room',[b.hotel,b.room].filter(Boolean).join(' · ')],['Arrival / departure',`${day(b.outboundDate)} / ${b.returnStatus==='PENDING'?'Waiting for date':b.returnStatus==='OTHER'||b.returnStatus==='NONE'?'Not with Greenview':day(b.returnDate)}`],['Payment terms',payment[b.paymentTerms]||'Not set'],['After-service reason',b.afterServiceReason],['Pickup point',b.pickupPoint],['Drop-off point',b.dropoffPoint],['Allergies',b.allergies||({NONE:'None reported',UNKNOWN:'Not checked'}[b.allergyStatus])],['Special requirements',(b.specialRequirements||[]).join(' · ')],['Assistance',b.assistance],['Requests',b.requestNotes]]
 return <section className="job-sheet booking-sheet"><SheetHeader title={bilingualLabel("Booking Job Order")} code={b.code} subtitle={b.trip?.name||'Standalone services'} revision={b.version} updatedAt={b.updatedAt} date={b.trip?.startsAt}><p><strong>{b.name}</strong> · {b.adults}{' '}{t("adults ·")}{' '}{b.children}{' '}{t("children ·")}{' '}{b.adults+b.children}{' '}{t("passengers")}</p><p>{t("Status:")}{' '}{t(b.status)} · {payment[b.paymentTerms]||t("Payment terms not set")}</p></SheetHeader>
 <div className="booking-facts">{fields.filter(([,value])=>value).map(([label,value])=><div key={label}><strong>{t(label)}</strong><span>{value}</span></div>)}</div>
 <h3>{bilingualLabel("Assigned boats and vehicles")}</h3>
 {assignments.length?<><div className="job-lines">{assignments.map(a=><article className="job-group" key={a.id}><h3>{a.run.slot?.vehicle?.name||a.run.name}</h3><dl><dt>{bilingualLabel("Run / direction")}</dt><dd>{a.run.code} · {t(a.run.direction)}</dd><dt>{bilingualLabel("Passengers")}</dt><dd>{a.adults}{' '}{t("adults ·")}{' '}{a.children}{' '}{t("children")}</dd><dt>{bilingualLabel("Time")}</dt><dd>{stamp(a.pickupAt||a.run.slot?.startsAt)||t("Not set")}</dd><dt>{bilingualLabel("Service")}</dt><dd>{a.service}</dd></dl></article>)}</div><table className="job-print-table"><thead><tr><th colSpan="6">{bilingualLabel("Booking")}{' '}{b.code}{' '}{bilingualLabel("· Handoff · Revision")}{' '}{b.version}</th></tr><tr><th>{bilingualLabel("Boat / vehicle")}</th><th>{bilingualLabel("Run / direction")}</th><th>{bilingualLabel("Adults")}</th><th>{bilingualLabel("Children")}</th><th>{bilingualLabel("Pickup / run time")}</th><th>{bilingualLabel("Service")}</th></tr></thead><tbody>{assignments.map(a=><tr key={a.id}><td>{a.run.kind==='BOAT'?t('Boat'):t('Vehicle')} · {a.run.slot?.vehicle?.name||a.run.name}</td><td>{a.run.code} · {t(a.run.direction)}</td><td>{a.adults}</td><td>{a.children}</td><td>{stamp(a.pickupAt||a.run.slot?.startsAt)||t("Not set")}</td><td>{a.service}</td></tr>)}</tbody></table></>:<p>{t("No boat or vehicle allocation yet. Guide and Head Driver arrange these separately.")}</p>}
 {selected.filter(l=>['TRANSFER','TOUR_BOAT','LONGTAIL_BOAT'].includes(l.resource?.category||l.snapshot?.category)).map(l=><Fragment key={l.id}>{(l.dispatchDirection==='BOTH'||!l.dispatchDirection?['OUTBOUND','RETURN']:[l.dispatchDirection]).map(direction=>{const links=(l.dispatchAssignments||[]).filter(a=>a.run.direction===direction),adults=links.reduce((n,a)=>n+a.adults,0),children=links.reduce((n,a)=>n+a.children,0);return adults<b.adults||children<b.children?<p className="job-pending" key={direction}>{l.snapshot?.name||l.resource?.name} · {direction}{t(": Waiting for allocation —")}{' '}{Math.max(0,b.adults-adults)}{' '}{t("adults /")}{' '}{Math.max(0,b.children-children)}{' '}{t("children.")}</p>:null})}</Fragment>)}
 <h3>{bilingualLabel("Selected services and supplies")}</h3><div className="booking-services">{selected.map((l,i)=><p key={l.id||i}>{l.snapshot?.name||l.resource?.name||t("Resource")} · {l.quantity} {l.snapshot?.baseUnit||l.resource?.baseUnit} · {l.usagePoint||'Unspecified'}</p>)}{!selected.length&&<p>{t("No selected services.")}</p>}</div>
 <p className="job-signoff">{t("Check-in: ____________________   Handed to Guide: ____________________   Time: __________")}</p><p className="job-footnote">{t("Operational handoff copy. Check-in and handoff spaces are for handwritten confirmation.")}</p></section>
}
