import MemberHeader from '../core/MemberHeader.jsx'
import { useLocale, label as headingLabel, t as msg, formatMoney, formatDate, formatNumber, bookingStatus } from "../core/locale.js";import DemoCheckout from './DemoCheckout.jsx';
import Recovery from './Recovery.jsx';
import Auth from './Auth.jsx';
import LeaveGuard from '../core/LeaveGuard.jsx';
import Documents from './Documents.jsx';
import TourRequest from './TourRequest.jsx';
import { useEffect, useRef, useState } from 'react';
import { Button, Field, Select, Notice } from '../core/ui.jsx';
import { api, errorText } from '../core/api.js';
import { prepareDocumentImage } from '../../../../packages/contracts/document-image.js';
function readRecovery() {const fragment = new URLSearchParams(location.hash.slice(1));const input = fragment.get('type') === 'recovery' ? { access_token: fragment.get('access_token'), refresh_token: fragment.get('refresh_token') } : null;if (location.hash) history.replaceState(null, '', location.pathname + location.search);return input;}
let initialRecovery = readRecovery(),recoveryAttempt;
const hasRecovery = Boolean(initialRecovery);
const money = formatMoney;
function Profile({ customer, onSaved }) {useLocale();const [name, setName] = useState(customer.displayName),[phone, setPhone] = useState(customer.phone || ''),[busy, setBusy] = useState(false),[notice, setNotice] = useState('');async function save(e) {e.preventDefault();if (busy) return;if (!name.trim()) {setNotice(msg("กรุณากรอกชื่อ"));return;}setBusy(true);try {const r = await api('/api/member/profile', { version: customer.version, displayName: name, phone });onSaved(r.customer);setNotice(msg("บันทึกข้อมูลแล้ว"));} catch (e) {setNotice(errorText(e));} finally {setBusy(false);}}return <section className="panel"><LeaveGuard dirty={name !== customer.displayName || phone !== (customer.phone || '') || busy} /><h1>{headingLabel("ข้อมูลของฉัน")}</h1><p>{customer.email}</p><form noValidate onSubmit={save}><Field label={msg("ชื่อผู้ติดต่อ")} value={name} onChange={(e) => setName(e.target.value)} maxLength={200} /><Field label={msg("โทรศัพท์")} type="tel" value={phone} onChange={(e) => setPhone(e.target.value)} maxLength={32} /><Notice>{notice}</Notice><Button type="submit" disabled={busy} busy={busy}>{msg("บันทึกข้อมูล")}</Button></form></section>;}
function PaymentProof({ row, payment, onSaved }) {useLocale();
  const [file, setFile] = useState(null),[busy, setBusy] = useState(false),[notice, setNotice] = useState(''),key = useRef(crypto.randomUUID());
  async function upload() {if (!file || busy) return;setBusy(true);try {const prepared = await prepareDocumentImage(file);const actual = prepared;const buffer = await actual.arrayBuffer();let binary = '';for (const byte of new Uint8Array(buffer)) binary += String.fromCharCode(byte);await api('/api/member/proof', { id: key.current, targetId: row.id, filename: actual.name, mimeType: actual.type, base64: btoa(binary), note: '', documentNumber: '' });onSaved();} catch (e) {setNotice(errorText(e));} finally {setBusy(false);}}
  return <section><LeaveGuard dirty={Boolean(file) || busy} /><h3>{headingLabel("ยอดชำระเต็มจำนวน")} {money(row.snapshot.confirmedTotal)}</h3>{payment?.bankName && payment?.bankAccountNumber ? <p>{payment.bankName}<br />{payment.bankAccountName}<br />{payment.bankAccountNumber}<br />{payment.paymentInstructions}</p> : <p>{msg("กรุณาติดต่อบริษัทเพื่อรับข้อมูลบัญชีที่ถูกต้องก่อนโอนเงิน")}</p>}{row.snapshot.paymentReview?.message && <Notice>{msg("ข้อความจากทีมงาน:")} {row.snapshot.paymentReview.message}</Notice>}<p>{msg("หลักฐานที่แนบต้องรอพนักงานตรวจยอด")}</p><Field label={msg("หลักฐานการโอน (JPEG, PNG หรือ PDF ไม่เกิน 5 MB)")} type="file" accept="image/jpeg,image/png,application/pdf" onChange={(e) => {setFile(e.target.files[0] || null);key.current = crypto.randomUUID();}} disabled={busy} /><Notice>{notice}</Notice>{file && <Button className="secondary" disabled={busy} onClick={() => setFile(null)}>{msg("นำไฟล์ที่เลือกออก")}</Button>}<Button disabled={!file || busy} busy={busy} onClick={upload}>{msg("ส่งหลักฐานให้ตรวจสอบ")}</Button></section>;
}
function CancelRequest({ row, onSaved }) {useLocale();const [confirm, setConfirm] = useState(false),[busy, setBusy] = useState(false),[notice, setNotice] = useState('');async function cancel() {if (busy) return;setBusy(true);try {await api('/api/member/cancel', { requestId: row.id, version: row.version });onSaved();} catch (e) {setNotice(errorText(e));} finally {setBusy(false);}}return <section>{confirm ? <><p>{msg("ยกเลิกคำขอที่ยังไม่ได้รับการยืนยันนี้? สิทธิ์โปรโมชั่นจะกลับไปให้ผู้จองคนอื่น")}</p><div className="actions"><Button className="secondary" disabled={busy} onClick={() => setConfirm(false)}>{msg("เก็บคำขอไว้")}</Button><Button disabled={busy} busy={busy} onClick={cancel}>{msg("ยืนยันยกเลิกคำขอ")}</Button></div></> : <Button className="secondary" onClick={() => setConfirm(true)}>{msg("ยกเลิกคำขอ")}</Button>}<Notice error>{notice}</Notice></section>;}
function Trips() {useLocale();const [state, setState] = useState({ loading: true }),[page, setPage] = useState(1),[attempt, setAttempt] = useState(0);useEffect(() => {const c = new AbortController();setState({ loading: true });api('/api/member/requests?page=' + page, undefined, c.signal).then((r) => setState(r)).catch((e) => {if (!c.signal.aborted) setState({ error: errorText(e) });});return () => c.abort();}, [page, attempt]);return <><h1>{headingLabel("ทริปของฉัน")}</h1><p>{msg("ติดตามคำขอจอง วันเดินทาง และสถานะจากทีมงาน")}</p>{state.loading ? <Notice>{msg("กำลังโหลด…")}</Notice> : state.error ? <><Notice error>{state.error}</Notice><Button onClick={() => setAttempt((n) => n + 1)}>{msg("ลองอีกครั้ง")}</Button></> : <>{!state.rows.length && <section className="panel"><h2>{headingLabel("ยังไม่มีการจอง")}</h2><p>{msg("เริ่มเลือกทัวร์ที่เหมาะกับวันพักผ่อนของคุณ")}</p><a href="/tours">{msg("เลือกโปรแกรมทัวร์ →")}</a></section>}{state.rows.map((r) => <article className="panel" key={r.id}><span className="eyebrow">{formatDate(r.serviceDate)}</span><h2>{r.snapshot.tourName}</h2><p>{msg("ผู้ใหญ่")} {formatNumber(r.adults)} {msg("· เด็ก")} {formatNumber(r.children)}</p><p>{r.snapshot.demoCheckout?.payment.status === 'SUCCEEDED' ? msg("ยืนยัน Booking ทดสอบแล้ว") : { REQUESTED: msg("รอทีมงานตรวจสอบ"), ACCEPTED: msg("ทีมงานรับคำขอแล้ว"), AWAITING_PAYMENT: msg("รอชำระเงิน"), PAYMENT_REVIEW: msg("รอตรวจสอบยอดชำระ"), PAID: msg("ตรวจสอบชำระเงินแล้ว"), EXPIRED: msg("สิทธิ์โปรโมชั่นหมดอายุ กรุณาส่งคำขอใหม่"), REJECTED: msg("ไม่สามารถรับคำขอได้"), CANCELLED: msg("ยกเลิกแล้ว") }[r.status] || r.status}</p><p>{msg("ราคาแพ็กเกจตามคำขอ")} {money(r.snapshot.packageTotal)}</p><p>{r.snapshot.promotion?.name}</p>{r.holdUntil && r.status === 'REQUESTED' && <p>{msg("กันสิทธิ์โปรโมชั่นรอการตรวจถึง")} {formatDate(r.holdUntil, true)}</p>}{r.booking && <p>Booking {r.booking.code} · {bookingStatus(r.booking.status)}</p>}<Documents requestId={r.id} />{r.demoCheckoutEnabled && <DemoCheckout row={r} onSaved={() => setAttempt((n) => n + 1)} />}{r.status === 'REQUESTED' && <CancelRequest row={r} onSaved={() => setAttempt((n) => n + 1)} />} {['AWAITING_PAYMENT', 'PAYMENT_REVIEW'].includes(r.status) && <PaymentProof row={r} payment={state.payment} onSaved={() => setAttempt((n) => n + 1)} />}</article>)}<div className="actions"><Button disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>{msg("ก่อนหน้า")}</Button><span>{msg("หน้า")} {formatNumber(state.page)}</span><Button disabled={state.page * 12 >= state.total} onClick={() => setPage((p) => p + 1)}>{msg("ถัดไป")}</Button></div></>}</>;}
function Tours({ customer }) {useLocale();const slug = new URLSearchParams(location.search).get('tour'),[state, setState] = useState({ loading: true }),[page, setPage] = useState(1),[attempt, setAttempt] = useState(0);useEffect(() => {const c = new AbortController();setState({ loading: true });api('/api/public/tours?' + new URLSearchParams({ page, ...(slug ? { slug } : {}) }), undefined, c.signal).then(setState).catch((e) => {if (!c.signal.aborted) setState({ error: errorText(e) });});return () => c.abort();}, [page, slug, attempt]);return <><h1>{headingLabel("โปรแกรมทัวร์")}</h1>{state.loading ? <Notice>{msg("กำลังโหลดทัวร์…")}</Notice> : state.error ? <><Notice error>{state.error}</Notice><Button onClick={() => setAttempt((n) => n + 1)}>{msg("ลองอีกครั้ง")}</Button></> : <>{!state.rows.length && <Notice>{msg("ยังไม่มีทัวร์เปิดเผยแพร่ กรุณาติดต่อบริษัทเพื่อสอบถาม")}</Notice>}<div className={slug ? '' : 'tour-grid'}>{state.rows.map((t) => <article className="panel" key={t.id}>{t.imageUrls && <img className="tour-cover" src={t.imageUrls.split('\n')[0]} alt={t.name} />}<span className="eyebrow">{t.durationDays == null ? '—' : formatNumber(t.durationDays)} {msg("วัน")}</span><h2>{t.name}</h2><p>{t.description}</p><p>{msg("ราคาปกติ ผู้ใหญ่")} {money(t.adultPrice)} {msg("· เด็ก")} {money(t.childPrice)}</p>{slug && t.promotions.map((p) => <section className="quote-panel" key={p.id}><h3>{p.name}</h3><p>{msg("ผู้ใหญ่")} {money(p.adultPrice)} {msg("· เด็ก")} {money(p.childPrice)}</p><p>{msg("เดินทาง")} {formatDate(p.serviceStartsOn)} {msg("ถึง")} {formatDate(p.serviceEndsOn)}</p><p>{p.remaining === null ? msg("ไม่จำกัดโควตาโปรโมชั่น") : `${msg("เหลือ")} ${formatNumber(p.remaining)} ${p.quotaUnit === 'SEAT' ? msg("ที่นั่ง") : msg("การจอง")}`} {msg("· รอทีมงานยืนยันที่ว่าง")}</p><p>{p.terms}</p></section>)}{slug ? <>{[[msg("จุดเด่น"), t.highlights], [msg("โปรแกรมเดินทาง"), t.route], [msg("อาหาร"), t.meals], [msg("ค่าธรรมเนียม"), t.fees], [msg("รวมในราคา"), t.inclusions], [msg("ไม่รวมในราคา"), t.exclusions], [msg("สิ่งที่ต้องเตรียม"), t.preparationNotes], [msg("เงื่อนไขยกเลิก"), t.cancellationTerms]].map(([label, text]) => text && <section key={label}><h3>{headingLabel(label)}</h3><p className="preserve">{text}</p></section>)}<TourRequest tour={t} customer={customer} /></> : <a href={'/tours?tour=' + encodeURIComponent(t.slug)}>{msg("รายละเอียดและวันเดินทาง →")}</a>}</article>)}</div>{!slug && <div className="actions"><Button disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>{msg("ก่อนหน้า")}</Button><span>{msg("หน้า")} {formatNumber(state.page)}</span><Button disabled={page * 12 >= state.total} onClick={() => setPage((p) => p + 1)}>{msg("ถัดไป")}</Button></div>}</>}</>;}
export default function App() {const { locale } = useLocale();const [session, setSession] = useState({ loading: true }),[notice, setNotice] = useState('');useEffect(() => {const c = new AbortController();if (hasRecovery) {recoveryAttempt ||= api('/api/member/recovery-session', initialRecovery);initialRecovery = null;recoveryAttempt.then((r) => {if (!c.signal.aborted) setSession(r);}).catch((e) => {if (!c.signal.aborted) setSession({ error: errorText(e) });});return () => c.abort();}api('/api/member/profile', undefined, c.signal).then((r) => setSession(r)).catch((e) => {if (!c.signal.aborted) setSession({ error: e.status === 401 ? null : errorText(e) });});return () => c.abort();}, []);const path = location.pathname;useEffect(() => {document.title = ({ '/tours': msg("โปรแกรมทัวร์"), '/profile': msg("ข้อมูลของฉัน"), '/login': msg("เข้าสู่ระบบสมาชิก"), '/': msg("ทริปของฉัน") }[path] || msg("ไม่พบหน้านี้")) + ' · Greenview Tour';}, [path, locale]);async function logout() {try {await api('/api/member/logout', {});location.assign('/login');} catch (e) {setNotice(errorText(e));}}return <><a className="skip" href="#content">{msg("ข้ามไปเนื้อหา")}</a><MemberHeader customer={session.customer} recovery={session.recovery} onLogout={logout} /><main id="content"><Notice error>{notice || session.error}</Notice>{!['/', '/tours', '/profile', '/login'].includes(path) ? <section><h1>{headingLabel("ไม่พบหน้านี้")}</h1><a href="/">{msg("กลับหน้าทริปของฉัน")}</a></section> : session.loading ? <Notice>{msg("กำลังตรวจสอบบัญชี…")}</Notice> : session.recovery ? <Recovery reset /> : path === '/tours' ? <Tours customer={session.customer} /> : !session.customer ? <Auth onLogin={(customer) => {const next = new URLSearchParams(location.search).get('next');if (next?.startsWith('/tours?') && !next.includes('\\')) location.assign(next);else setSession({ customer });}} /> : path === '/profile' ? <Profile customer={session.customer} onSaved={(customer) => setSession({ customer })} /> : <Trips />}</main><footer><a className="website-home" href="http://localhost:5173">{msg("← กลับหน้าแรกเว็บไซต์")}</a><span>{msg("Greenview Tour · ทุกทริปเริ่มต้นที่นี่")}</span></footer></>;}
