import DemoCheckout from './DemoCheckout.jsx'
import Recovery from './Recovery.jsx'
import Auth from './Auth.jsx'
import LeaveGuard from '../core/LeaveGuard.jsx'
import Documents from './Documents.jsx'
import TourRequest from './TourRequest.jsx'
import {useEffect,useRef,useState} from 'react'
import {Button,Field,Select,Notice} from '../core/ui.jsx'
import {api,errorText} from '../core/api.js'
import {prepareDocumentImage} from '../../../../packages/contracts/document-image.js'
function readRecovery(){const fragment=new URLSearchParams(location.hash.slice(1));const input=fragment.get('type')==='recovery'?{access_token:fragment.get('access_token'),refresh_token:fragment.get('refresh_token')}:null;if(location.hash)history.replaceState(null,'',location.pathname+location.search);return input}
let initialRecovery=readRecovery(),recoveryAttempt
const hasRecovery=Boolean(initialRecovery)
const money=v=>v===null?'ติดต่อสอบถาม':new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(Number(v))
function Profile({customer,onSaved}){const [name,setName]=useState(customer.displayName),[phone,setPhone]=useState(customer.phone||''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');async function save(e){e.preventDefault();if(busy)return;if(!name.trim()){setNotice('กรุณากรอกชื่อ');return}setBusy(true);try{const r=await api('/api/member/profile',{version:customer.version,displayName:name,phone});onSaved(r.customer);setNotice('บันทึกข้อมูลแล้ว')}catch(e){setNotice(errorText(e))}finally{setBusy(false)}}return <section className="panel"><LeaveGuard dirty={name!==customer.displayName||phone!==(customer.phone||'')||busy}/><h1>ข้อมูลของฉัน</h1><p>{customer.email}</p><form noValidate onSubmit={save}><Field label="ชื่อผู้ติดต่อ" value={name} onChange={e=>setName(e.target.value)} maxLength={200}/><Field label="โทรศัพท์" type="tel" value={phone} onChange={e=>setPhone(e.target.value)} maxLength={32}/><Notice>{notice}</Notice><Button type="submit" disabled={busy} busy={busy}>บันทึกข้อมูล</Button></form></section>}
function PaymentProof({row,payment,onSaved}){
 const [file,setFile]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),key=useRef(crypto.randomUUID())
 async function upload(){if(!file||busy)return;setBusy(true);try{const prepared=await prepareDocumentImage(file);const actual=prepared;const buffer=await actual.arrayBuffer();let binary='';for(const byte of new Uint8Array(buffer))binary+=String.fromCharCode(byte);await api('/api/member/proof',{id:key.current,targetId:row.id,filename:actual.name,mimeType:actual.type,base64:btoa(binary),note:'',documentNumber:''});onSaved()}catch(e){setNotice(errorText(e))}finally{setBusy(false)}}
 return <section><LeaveGuard dirty={Boolean(file)||busy}/><h3>ยอดชำระเต็มจำนวน {money(row.snapshot.confirmedTotal)}</h3>{payment?.bankName&&payment?.bankAccountNumber?<p>{payment.bankName}<br/>{payment.bankAccountName}<br/>{payment.bankAccountNumber}<br/>{payment.paymentInstructions}</p>:<p>กรุณาติดต่อบริษัทเพื่อรับข้อมูลบัญชีที่ถูกต้องก่อนโอนเงิน</p>}{row.snapshot.paymentReview?.message&&<Notice>ข้อความจากทีมงาน: {row.snapshot.paymentReview.message}</Notice>}<p>หลักฐานที่แนบต้องรอพนักงานตรวจยอด</p><Field label="หลักฐานการโอน (JPEG, PNG หรือ PDF ไม่เกิน 5 MB)" type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>{setFile(e.target.files[0]||null);key.current=crypto.randomUUID()}} disabled={busy}/><Notice>{notice}</Notice>{file&&<Button className="secondary" disabled={busy} onClick={()=>setFile(null)}>นำไฟล์ที่เลือกออก</Button>}<Button disabled={!file||busy} busy={busy} onClick={upload}>ส่งหลักฐานให้ตรวจสอบ</Button></section>
}
function CancelRequest({row,onSaved}){const [confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');async function cancel(){if(busy)return;setBusy(true);try{await api('/api/member/cancel',{requestId:row.id,version:row.version});onSaved()}catch(e){setNotice(errorText(e))}finally{setBusy(false)}}return <section>{confirm?<><p>ยกเลิกคำขอที่ยังไม่ได้รับการยืนยันนี้? สิทธิ์โปรโมชั่นจะกลับไปให้ผู้จองคนอื่น</p><div className="actions"><Button className="secondary" disabled={busy} onClick={()=>setConfirm(false)}>เก็บคำขอไว้</Button><Button disabled={busy} busy={busy} onClick={cancel}>ยืนยันยกเลิกคำขอ</Button></div></>:<Button className="secondary" onClick={()=>setConfirm(true)}>ยกเลิกคำขอ</Button>}<Notice error>{notice}</Notice></section>}
function Trips(){const [state,setState]=useState({loading:true}),[page,setPage]=useState(1),[attempt,setAttempt]=useState(0);useEffect(()=>{const c=new AbortController();setState({loading:true});api('/api/member/requests?page='+page,undefined,c.signal).then(r=>setState(r)).catch(e=>{if(!c.signal.aborted)setState({error:errorText(e)})});return()=>c.abort()},[page,attempt]);return <><h1>ทริปของฉัน</h1><p>ติดตามคำขอจอง วันเดินทาง และสถานะจากทีมงาน</p>{state.loading?<Notice>กำลังโหลด…</Notice>:state.error?<><Notice error>{state.error}</Notice><Button onClick={()=>setAttempt(n=>n+1)}>ลองอีกครั้ง</Button></>:<>{!state.rows.length&&<section className="panel"><h2>ยังไม่มีการจอง</h2><p>เริ่มเลือกทัวร์ที่เหมาะกับวันพักผ่อนของคุณ</p><a href="/tours">เลือกโปรแกรมทัวร์ →</a></section>}{state.rows.map(r=><article className="panel" key={r.id}><span className="eyebrow">{String(r.serviceDate).slice(0,10)}</span><h2>{r.snapshot.tourName}</h2><p>ผู้ใหญ่ {r.adults} · เด็ก {r.children}</p><p>{r.snapshot.demoCheckout?.payment.status==='SUCCEEDED'?'ยืนยัน Booking ทดสอบแล้ว':({REQUESTED:'รอทีมงานตรวจสอบ',ACCEPTED:'ทีมงานรับคำขอแล้ว',AWAITING_PAYMENT:'รอชำระเงิน',PAYMENT_REVIEW:'รอตรวจสอบยอดชำระ',PAID:'ตรวจสอบชำระเงินแล้ว',EXPIRED:'สิทธิ์โปรโมชั่นหมดอายุ กรุณาส่งคำขอใหม่',REJECTED:'ไม่สามารถรับคำขอได้',CANCELLED:'ยกเลิกแล้ว'})[r.status]||r.status}</p><p>ราคาแพ็กเกจตามคำขอ {money(r.snapshot.packageTotal)}</p><p>{r.snapshot.promotion?.name}</p>{r.holdUntil&&r.status==='REQUESTED'&&<p>กันสิทธิ์โปรโมชั่นรอการตรวจถึง {new Date(r.holdUntil).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'})}</p>}{r.booking&&<p>Booking {r.booking.code} · {r.booking.status}</p>}<Documents requestId={r.id}/>{r.demoCheckoutEnabled&&<DemoCheckout row={r} onSaved={()=>setAttempt(n=>n+1)}/>}{r.status==='REQUESTED'&&<CancelRequest row={r} onSaved={()=>setAttempt(n=>n+1)}/>} {['AWAITING_PAYMENT','PAYMENT_REVIEW'].includes(r.status)&&<PaymentProof row={r} payment={state.payment} onSaved={()=>setAttempt(n=>n+1)}/>}</article>)}<div className="actions"><Button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>ก่อนหน้า</Button><span>หน้า {state.page}</span><Button disabled={state.page*12>=state.total} onClick={()=>setPage(p=>p+1)}>ถัดไป</Button></div></>}</>}
function Tours({customer}){const slug=new URLSearchParams(location.search).get('tour'),[state,setState]=useState({loading:true}),[page,setPage]=useState(1),[attempt,setAttempt]=useState(0);useEffect(()=>{const c=new AbortController();setState({loading:true});api('/api/public/tours?'+new URLSearchParams({page,...(slug?{slug}:{})}),undefined,c.signal).then(setState).catch(e=>{if(!c.signal.aborted)setState({error:errorText(e)})});return()=>c.abort()},[page,slug,attempt]);return <><h1>โปรแกรมทัวร์</h1>{state.loading?<Notice>กำลังโหลดทัวร์…</Notice>:state.error?<><Notice error>{state.error}</Notice><Button onClick={()=>setAttempt(n=>n+1)}>ลองอีกครั้ง</Button></>:<>{!state.rows.length&&<Notice>ยังไม่มีทัวร์เปิดเผยแพร่ กรุณาติดต่อบริษัทเพื่อสอบถาม</Notice>}<div className={slug?'':'tour-grid'}>{state.rows.map(t=><article className="panel" key={t.id}>{t.imageUrls&&<img className="tour-cover" src={t.imageUrls.split('\n')[0]} alt={t.name}/>}<span className="eyebrow">{t.durationDays||'—'} วัน</span><h2>{t.name}</h2><p>{t.description}</p><p>ราคาปกติ ผู้ใหญ่ {money(t.adultPrice)} · เด็ก {money(t.childPrice)}</p>{slug&&t.promotions.map(p=><section className="quote-panel" key={p.id}><h3>{p.name}</h3><p>ผู้ใหญ่ {money(p.adultPrice)} · เด็ก {money(p.childPrice)}</p><p>เดินทาง {String(p.serviceStartsOn).slice(0,10)} ถึง {String(p.serviceEndsOn).slice(0,10)}</p><p>{p.remaining===null?'ไม่จำกัดโควตาโปรโมชั่น':`เหลือ ${p.remaining} ${p.quotaUnit==='SEAT'?'ที่นั่ง':'การจอง'}`} · รอทีมงานยืนยันที่ว่าง</p><p>{p.terms}</p></section>)}{slug?<>{[['จุดเด่น',t.highlights],['โปรแกรมเดินทาง',t.route],['อาหาร',t.meals],['ค่าธรรมเนียม',t.fees],['รวมในราคา',t.inclusions],['ไม่รวมในราคา',t.exclusions],['สิ่งที่ต้องเตรียม',t.preparationNotes],['เงื่อนไขยกเลิก',t.cancellationTerms]].map(([label,text])=>text&&<section key={label}><h3>{label}</h3><p className="preserve">{text}</p></section>)}<TourRequest tour={t} customer={customer}/></>:<a href={'/tours?tour='+encodeURIComponent(t.slug)}>รายละเอียดและวันเดินทาง →</a>}</article>)}</div>{!slug&&<div className="actions"><Button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>ก่อนหน้า</Button><span>หน้า {state.page}</span><Button disabled={page*12>=state.total} onClick={()=>setPage(p=>p+1)}>ถัดไป</Button></div>}</>}</>}
export default function App(){const [session,setSession]=useState({loading:true}),[notice,setNotice]=useState('');useEffect(()=>{const c=new AbortController();if(hasRecovery){recoveryAttempt ||=api('/api/member/recovery-session',initialRecovery);initialRecovery=null;recoveryAttempt.then(r=>{if(!c.signal.aborted)setSession(r)}).catch(e=>{if(!c.signal.aborted)setSession({error:errorText(e)})});return()=>c.abort()}api('/api/member/profile',undefined,c.signal).then(r=>setSession(r)).catch(e=>{if(!c.signal.aborted)setSession({error:e.status===401?null:errorText(e)})});return()=>c.abort()},[]);const path=location.pathname;useEffect(()=>{document.title=({ '/tours':'โปรแกรมทัวร์','/profile':'ข้อมูลของฉัน','/login':'เข้าสู่ระบบสมาชิก','/':'ทริปของฉัน' }[path]||'ไม่พบหน้านี้')+' · Greenview Tour'},[path]);async function logout(){try{await api('/api/member/logout',{});location.assign('/login')}catch(e){setNotice(errorText(e))}}return <><a className="skip" href="#content">ข้ามไปเนื้อหา</a><header><a className="brand" href="/">GREENVIEW <span>MEMBER</span></a><nav aria-label="เมนูสมาชิก"><a href="/tours">โปรแกรมทัวร์</a>{session.customer&&!session.recovery&&<><a href="/">ทริปของฉัน</a><a href="/profile">ข้อมูลของฉัน</a></>}{session.customer?<Button className="secondary" onClick={logout}>ออกจากระบบ</Button>:<a href="/login">เข้าสู่ระบบ</a>}</nav></header><main id="content"><Notice error>{notice||session.error}</Notice>{!['/','/tours','/profile','/login'].includes(path)?<section><h1>ไม่พบหน้านี้</h1><a href="/">กลับหน้าทริปของฉัน</a></section>:session.loading?<Notice>กำลังตรวจสอบบัญชี…</Notice>:session.recovery?<Recovery reset/>:path==='/tours'?<Tours customer={session.customer}/>:!session.customer?<Auth onLogin={customer=>{const next=new URLSearchParams(location.search).get('next');if(next?.startsWith('/tours?')&&!next.includes('\\'))location.assign(next);else setSession({customer})}}/>:path==='/profile'?<Profile customer={session.customer} onSaved={customer=>setSession({customer})}/>:<Trips/>}</main><footer><a className="website-home" href="http://localhost:5173">← กลับหน้าแรกเว็บไซต์</a><span>Greenview Tour · ทุกทริปเริ่มต้นที่นี่</span></footer></>}
