import { useLocale, label as headingLabel, t as msg, formatMoney, formatDate } from "../core/locale.js";import { useState } from 'react';
import { Button, Notice } from '../core/ui.jsx';
import { api, errorText } from '../core/api.js';
export default function DemoCheckout({ row, onSaved }) {useLocale();
  const [busy, setBusy] = useState(false),[error, setError] = useState('');
  const checkout = row.snapshot.demoCheckout,payment = checkout?.payment,done = payment?.status === 'SUCCEEDED';
  async function run(action) {if (busy) return;setBusy(true);setError('');try {await api('/api/member/demo-checkout', { requestId: row.id, action, paymentId: payment?.id });onSaved();} catch (e) {setError({ DEMO_PAYMENT_EXPIRED: msg("รายการทดสอบหมดเวลาแล้ว กดเตรียมการชำระใหม่"), DEMO_ONLY: msg("รายการนี้ไม่ใช่ทัวร์ DEMO ที่อนุญาต"), PROGRAM_COMPONENTS_STALE: msg("ข้อมูลทัวร์เปลี่ยนแล้ว กรุณาจองตัวอย่างใหม่"), PAYMENT_REFERENCE_MISMATCH: msg("รายการชำระเปลี่ยนแล้ว กรุณาโหลดหน้านี้ใหม่") }[e.message] || errorText(e));} finally {setBusy(false);}}
  return <section className="quote-panel" aria-label={msg("ทดสอบชำระและแจ้ง LINE")}><h3>{headingLabel("DEMO · ทดสอบชำระเงินและ LINE")}</h3><p>{msg("ไม่มีการรับเงินจริง ไม่ต้องสแกนหรือแนบสลิป ข้อความ LINE จะแสดงเป็นตัวอย่างในหน้านี้เท่านั้น")}</p>{done ? <><Notice>{msg("ชำระจำลองสำเร็จ · ระบบยืนยัน Booking")} {row.snapshot.bookingCode} {msg("แล้ว")}</Notice><h3>{headingLabel("ตัวอย่างข้อความ LINE สำหรับบัญชีของคุณ")}</h3><p className="preserve">{checkout.notification?.text}</p><p>{msg("สถานะ: จำลองแล้ว · ยังไม่ได้ส่ง LINE จริง")}</p></> : row.status === 'REQUESTED' ? <><p>{msg("ยอดทดสอบ")} {formatMoney(row.snapshot.packageTotal)}</p>{payment && <p>{msg("ใช้รายการนี้ได้ถึง")} {formatDate(payment.expiresAt, true)} {msg("· ยังไม่มี QR สำหรับรับเงินจริง")}</p>}<div className="actions"><Button className="secondary" busy={busy} disabled={busy} onClick={() => run('PREPARE')}>{payment ? msg("เตรียมการชำระใหม่") : msg("เตรียมการชำระจำลอง")}</Button>{payment && <Button busy={busy} disabled={busy} onClick={() => run('SUCCEED')}>{msg("จำลองจ่ายสำเร็จและยืนยัน Booking")}</Button>}</div></> : <p>{msg("คำขอนี้ไม่อยู่ในสถานะที่ทดสอบชำระได้")}</p>}<Notice error>{error}</Notice></section>;
}
