import {useState} from 'react'
import {Button,Notice} from '../core/ui.jsx'
import {api,errorText} from '../core/api.js'
export default function DemoCheckout({row,onSaved}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('')
 const checkout=row.snapshot.demoCheckout,payment=checkout?.payment,done=payment?.status==='SUCCEEDED'
 async function run(action){if(busy)return;setBusy(true);setError('');try{await api('/api/member/demo-checkout',{requestId:row.id,action,paymentId:payment?.id});onSaved()}catch(e){setError(({DEMO_PAYMENT_EXPIRED:'รายการทดสอบหมดเวลาแล้ว กดเตรียมการชำระใหม่',DEMO_ONLY:'รายการนี้ไม่ใช่ทัวร์ DEMO ที่อนุญาต',PROGRAM_COMPONENTS_STALE:'ข้อมูลทัวร์เปลี่ยนแล้ว กรุณาจองตัวอย่างใหม่',PAYMENT_REFERENCE_MISMATCH:'รายการชำระเปลี่ยนแล้ว กรุณาโหลดหน้านี้ใหม่'})[e.message]||errorText(e))}finally{setBusy(false)}}
 return <section className="quote-panel" aria-label="ทดสอบชำระและแจ้ง LINE"><h3>DEMO · ทดสอบชำระเงินและ LINE</h3><p>ไม่มีการรับเงินจริง ไม่ต้องสแกนหรือแนบสลิป ข้อความ LINE จะแสดงเป็นตัวอย่างในหน้านี้เท่านั้น</p>{done?<><Notice>ชำระจำลองสำเร็จ · ระบบยืนยัน Booking {row.snapshot.bookingCode} แล้ว</Notice><h3>ตัวอย่างข้อความ LINE สำหรับบัญชีของคุณ</h3><p className="preserve">{checkout.notification?.text}</p><p>สถานะ: จำลองแล้ว · ยังไม่ได้ส่ง LINE จริง</p></>:row.status==='REQUESTED'?<><p>ยอดทดสอบ {new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(Number(row.snapshot.packageTotal))}</p>{payment&&<p>ใช้รายการนี้ได้ถึง {new Date(payment.expiresAt).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'})} · ยังไม่มี QR สำหรับรับเงินจริง</p>}<div className="actions"><Button className="secondary" busy={busy} disabled={busy} onClick={()=>run('PREPARE')}>{payment?'เตรียมการชำระใหม่':'เตรียมการชำระจำลอง'}</Button>{payment&&<Button busy={busy} disabled={busy} onClick={()=>run('SUCCEED')}>จำลองจ่ายสำเร็จและยืนยัน Booking</Button>}</div></>:<p>คำขอนี้ไม่อยู่ในสถานะที่ทดสอบชำระได้</p>}<Notice error>{error}</Notice></section>
}
