const messages={
 menuPending:['ยกเลิกการเชื่อมบัญชีแล้ว เมนู LINE ยังอัปเดตไม่สำเร็จ ระบบจะลองอัปเดตอีกครั้งเมื่อคุณใช้งานแชท LINE ครั้งถัดไป','Your LINE account is disconnected. The LINE menu could not update yet; it will retry the next time you interact with the LINE chat.'],
 onboardingTitle:['เชื่อม LINE ก่อนเริ่มใช้งาน','Connect LINE to start work'],
 onboardingIntro:['บัญชีพนักงานของคุณพร้อมแล้ว กรุณาเชื่อม LINE ของคุณเพื่อรับข้อมูลงานก่อนเข้าสู่พื้นที่ทำงาน','Your employee account is ready. Connect your own LINE account to receive work information before opening the workspace.'],
 onboardingRetry:['ตรวจสอบการเชื่อมและเข้าใช้งาน','Check connection and continue'],
 signOut:['ออกจากระบบ','Sign out'],
 profile:['ข้อมูลส่วนตัวและรหัสผ่าน','Profile and password'],

 title:['เชื่อมบัญชี LINE พนักงาน','Staff LINE connection'],
 intro:['เชื่อมบัญชีของคุณกับ Greenview Staff เพื่อเตรียมรับแจ้งเตือนตามสิทธิ์และงานที่รับผิดชอบ','Link your account to Greenview Staff for future work notifications based on current permissions and assignments.'],
 loading:['กำลังตรวจสอบการเชื่อมต่อ…','Checking LINE connection…'],
 local:['ขณะนี้เป็น Local: ยังไม่เปิดการเชื่อมกับ LINE จริง ต้องตั้งค่า Webhook HTTPS และข้อมูลช่องทางก่อน','Local only: live LINE linking is not enabled. An HTTPS webhook and channel credentials are required.'],
 test:['ทดสอบบน Local เท่านั้น — ไม่ใช่การเชื่อม LINE จริง','Local test only — not a real LINE connection'],
 paused:['ส่วนนี้ยังไม่เปิดการส่งแจ้งเตือนอัตโนมัติ','Automatic work notifications are not enabled by this feature.'],
 unlinked:['ยังไม่เชื่อมบัญชี','Not linked'],linked:['เชื่อมบัญชีแล้ว','Linked'],
 blocked:['LINE ถูกบล็อก — ยกเลิกการเชื่อมแล้วเชื่อมใหม่เมื่อพร้อม','LINE blocked — unlink and reconnect when ready'],
 suspended:['การเชื่อมถูกระงับ','Connection suspended'],pending:['กำลังรอ LINE ยืนยัน','Waiting for LINE confirmation'],
 connect:['เชื่อมบัญชี LINE','Connect LINE account'],identityUnavailable:['ยังไม่มีชื่อ LINE ให้แสดง','LINE display name is unavailable'],friend:['เปิด Greenview Staff','Open Greenview Staff'],
 instructions:['เพิ่มเพื่อนหรือเปิดแชท Greenview Staff แล้วแตะปุ่ม “เชื่อมบัญชี LINE” เปิดลิงก์ที่ OA ตอบกลับ เข้าสู่ระบบ และยืนยันบัญชีของคุณ','Add or open Greenview Staff, then tap “เชื่อมบัญชี LINE” (Connect LINE account) in the chat menu. Open the reply link, sign in and confirm your own account.'],
 contact:['LINE ID ในข้อมูลติดต่อไม่ใช่การยืนยันบัญชี LINE','The contact LINE ID field does not verify your LINE identity.'],
 refresh:['ตรวจสอบสถานะ','Refresh connection'],unlink:['ยกเลิกการเชื่อม','Unlink LINE'],cancelPending:['ยกเลิกคำขอที่รออยู่','Cancel pending request'],
 confirmUnlink:['ยืนยันยกเลิกการเชื่อม LINE?','Unlink your LINE account?'],
 unlinkText:['บัญชีพนักงานและข้อมูลงานจะยังอยู่ การยกเลิกนี้ลบการจับคู่ LINE และยกเลิกคำขอเชื่อมที่ค้าง','Your employee account and work remain intact. This removes the LINE pairing and cancels pending link requests.'],
 keep:['เก็บการเชื่อมไว้','Keep connection'],close:['ปิด','Close'],
 error:['ตรวจสอบ LINE ไม่สำเร็จ กรุณาลองใหม่','Unable to check LINE. Please try again.'],done:['ยกเลิกการเชื่อมแล้ว','LINE connection removed.'],
 login:['เข้าสู่ระบบพนักงาน','Staff sign in'],email:['อีเมล','Email address'],password:['รหัสผ่านปัจจุบัน','Current password'],signIn:['เข้าสู่ระบบ','Sign in'],
 consent:['ฉันยืนยันว่าเป็นบัญชี LINE ของฉัน และรับทราบว่ายกเลิกการเชื่อมได้ทุกเมื่อ','I confirm this is my own LINE account. I can unlink it at any time.'],
 confirm:['ยืนยันและไปตรวจสอบกับ LINE','Confirm and continue to LINE'],as:['กำลังเชื่อมบัญชีพนักงาน','Employee account to link'],lineName:['ชื่อบัญชี LINE','LINE account name'],
 invalid:['ลิงก์ไม่ถูกต้อง หมดอายุ หรือถูกใช้แล้ว ส่ง “LINK STAFF” ใน OA เพื่อขอลิงก์ใหม่','This link is invalid, expired or already used. Send “LINK STAFF” to the OA for a new link.'],
 conflict:['บัญชีพนักงานหรือ LINE นี้มีการเชื่อมอยู่แล้ว ยกเลิกการเชื่อมเดิมก่อน','The employee or LINE account is already linked. Unlink the existing connection first.'],
 wrongPassword:['รหัสผ่านไม่ถูกต้อง กรุณาลองใหม่','The password is incorrect. Please try again.'],return:['กลับข้อมูลผู้ใช้','Back to profile'],
 noLink:['หน้านี้ต้องเปิดจากลิงก์เชื่อมบัญชีที่ Greenview Staff ส่งให้เท่านั้น','Open this page using the account-linking URL sent by Greenview Staff.'],
 privacy:['ไม่ใช้ชื่อ LINE หรือ LINE ID ที่กรอกเองเพื่อกำหนดสิทธิ์','Your LINE name or editable contact LINE ID never grants employee access.'],
 after:['หลัง LINE ยืนยัน ให้กลับมาที่ข้อมูลผู้ใช้และกดตรวจสอบสถานะ','After LINE confirms, return to your profile and refresh the connection status.'],
 saveFirst:['บันทึกหรือยกเลิกข้อมูลโปรไฟล์ที่กำลังแก้ก่อนดำเนินการ','Save or discard your profile edits before continuing.'],
 changed:['สถานะการเชื่อมเปลี่ยนแล้ว กรุณาตรวจสอบสถานะใหม่','The connection changed. Refresh its status and try again.'],
 rate:['ลองเชื่อมหลายครั้งเกินไป กรุณารอสักครู่','Too many connection attempts. Please wait before trying again.'],
 required:['กรอกรหัสผ่านและยอมรับการเชื่อมบัญชีก่อน','Enter your password and accept the account-linking confirmation.'],
}
export const lineCopy=locale=>Object.fromEntries(Object.entries(messages).map(([key,pair])=>[key,pair[locale==='th'?0:1]]))
export function lineError(error,copy){return ({LINE_LINK_INVALID:copy.invalid,LINE_LINK_CONFLICT:copy.conflict,LINE_LINK_CHANGED:copy.changed,INVALID_CREDENTIALS:copy.wrongPassword,LINE_LOCAL_ONLY:copy.local,LINE_NOT_CONFIGURED:copy.local,AUTH_RATE_LIMITED:copy.rate,LINE_CONSENT_REQUIRED:copy.required})[error.message]||copy.error}
