BEGIN;
SET LOCAL search_path = app_private;
ALTER TABLE "CompanySettings" ADD COLUMN "province" VARCHAR(100);
ALTER TABLE "CompanySettings" ADD COLUMN "district" VARCHAR(100);
ALTER TABLE "CompanySettings" ADD COLUMN "subdistrict" VARCHAR(100);
ALTER TABLE "CompanySettings" ADD COLUMN "houseNumber" VARCHAR(50);
ALTER TABLE "CompanySettings" ADD COLUMN "moo" VARCHAR(20);
ALTER TABLE "CompanySettings" ADD COLUMN "villageName" VARCHAR(150);
ALTER TABLE "CompanySettings" ADD COLUMN "mapUrl" VARCHAR(2048);
ALTER TABLE "CompanySettings" ADD COLUMN "latitude" VARCHAR(30);
ALTER TABLE "CompanySettings" ADD COLUMN "longitude" VARCHAR(30);
ALTER TABLE "BusinessPartner" ADD COLUMN "province" VARCHAR(100);
ALTER TABLE "BusinessPartner" ADD COLUMN "district" VARCHAR(100);
ALTER TABLE "BusinessPartner" ADD COLUMN "subdistrict" VARCHAR(100);
ALTER TABLE "BusinessPartner" ADD COLUMN "houseNumber" VARCHAR(50);
ALTER TABLE "BusinessPartner" ADD COLUMN "moo" VARCHAR(20);
ALTER TABLE "BusinessPartner" ADD COLUMN "villageName" VARCHAR(150);
ALTER TABLE "BusinessPartner" ADD COLUMN "mapUrl" VARCHAR(2048);
ALTER TABLE "BusinessPartner" ADD COLUMN "latitude" VARCHAR(30);
ALTER TABLE "BusinessPartner" ADD COLUMN "longitude" VARCHAR(30);
ALTER TABLE "PickupLocation" ADD COLUMN "province" VARCHAR(100);
ALTER TABLE "PickupLocation" ADD COLUMN "district" VARCHAR(100);
ALTER TABLE "PickupLocation" ADD COLUMN "subdistrict" VARCHAR(100);
ALTER TABLE "PickupLocation" ADD COLUMN "houseNumber" VARCHAR(50);
ALTER TABLE "PickupLocation" ADD COLUMN "moo" VARCHAR(20);
ALTER TABLE "PickupLocation" ADD COLUMN "villageName" VARCHAR(150);
ALTER TABLE "PickupLocation" ADD COLUMN "mapUrl" VARCHAR(2048);
ALTER TABLE "UserProfile" ADD COLUMN "province" VARCHAR(100);
ALTER TABLE "UserProfile" ADD COLUMN "district" VARCHAR(100);
ALTER TABLE "UserProfile" ADD COLUMN "subdistrict" VARCHAR(100);
ALTER TABLE "UserProfile" ADD COLUMN "houseNumber" VARCHAR(50);
ALTER TABLE "UserProfile" ADD COLUMN "moo" VARCHAR(20);
ALTER TABLE "UserProfile" ADD COLUMN "villageName" VARCHAR(150);
ALTER TABLE "UserProfile" ADD COLUMN "mapUrl" VARCHAR(2048);
ALTER TABLE "UserProfile" ADD COLUMN "latitude" VARCHAR(30);
ALTER TABLE "UserProfile" ADD COLUMN "longitude" VARCHAR(30);
COMMIT;
