import {jobCodeManualSections} from '../../../../packages/contracts/job-code-guide.js'
import {capacityManualSections} from './capacity-guide.js'
import {roleNames} from '../../../../packages/contracts/access.js'
import {AccessError} from '../../modules/identity-access/membership.js'
const pair=(en,th)=>({en,th})
const section=(heading,headingTh,en,th)=>({heading:pair(heading,headingTh),body:pair(en,th)})
const duties={
 BOOKING:pair('Open Booking from the navigation. Check the service date, tour program, guest count and booking status before opening a record. Use the record’s existing actions to continue; a dashboard total does not confirm or change a booking.','เปิด Booking จากเมนู ตรวจวันให้บริการ โปรแกรมทัวร์ จำนวนผู้โดยสาร และสถานะก่อนเปิดรายการ ดำเนินงานผ่านคำสั่งในรายการ ยอดบน Dashboard ไม่ได้ยืนยันหรือแก้ไขการจอง'),
 HEAD_BOOKING:pair('Review bookings and customer check-in within your assigned scope. Confirm the service date and unresolved work before coordinating your team. Company-only actions still require their existing permissions.','ตรวจการจองและการเช็กอินลูกค้าตามขอบเขตที่ได้รับมอบหมาย ตรวจวันให้บริการและงานค้างก่อนประสานทีม คำสั่งระดับบริษัทยังใช้สิทธิ์เดิม'),
 SALES:pair('Use the work areas shown in your navigation. Check customer and booking information in the permitted workspace before following up with the team. This role does not automatically grant booking-edit or finance rights.','ใช้ส่วนงานที่ปรากฏในเมนู ตรวจข้อมูลลูกค้าและการจองในหน้าที่ได้รับสิทธิ์ก่อนติดตามกับทีม ตำแหน่งนี้ไม่ได้ให้สิทธิ์แก้ไขการจองหรือการเงินโดยอัตโนมัติ'),
 ACCOUNT:pair('Open an accounts work area available in your navigation. Review the booking, bill and supporting evidence before recording a permitted finance action. Payment, receipt and signature states are separate; dashboard figures do not approve a transaction.','เปิดส่วนงานบัญชีที่มีในเมนู ตรวจการจอง ใบเรียกเก็บ และหลักฐานก่อนบันทึกรายการตามสิทธิ์ สถานะการชำระเงิน การรับเอกสาร และลายเซ็นแยกจากกัน ยอดบน Dashboard ไม่ได้อนุมัติธุรกรรม'),
 GUIDE:pair('Open Boat to review your permitted boat jobs and guide assignments. Check service date, passengers, meeting details and crew before continuing. Assignment changes use the existing authorized actions.','เปิด Boat เพื่อตรวจงานเรือและงานไกด์ตามสิทธิ์ ตรวจวันให้บริการ ผู้โดยสาร จุดนัดหมาย และทีมงานก่อนดำเนินการ การเปลี่ยนการจัดงานใช้คำสั่งที่ได้รับสิทธิ์เดิม'),
 HEAD_GUIDE:pair('Review boat jobs and guide assignments for your permitted team. Check allocation and crew before assigning work through the existing Boat workspace. Confirm the correct service date and scope before saving.','ตรวจงานเรือและงานไกด์ในขอบเขตทีม ตรวจการจัดสรรและลูกเรือก่อนมอบหมายผ่านหน้า Boat ตรวจวันให้บริการและขอบเขตให้ถูกต้องก่อนบันทึก'),
 ASSISTANT_TOUR_GUIDE:pair('Open Boat and review only jobs assigned or otherwise permitted to you. Check meeting and passenger instructions for the selected service date. Contact the responsible guide for work outside your available actions.','เปิด Boat และตรวจเฉพาะงานที่มอบหมายหรือได้รับสิทธิ์ ตรวจคำแนะนำนัดหมายและผู้โดยสารตามวันให้บริการ ติดต่อไกด์ผู้รับผิดชอบเมื่อต้องดำเนินการนอกสิทธิ์'),
 CAPTAIN:pair('Open Boat to review your permitted sailing jobs. Check the service date, assigned boat, crew and passenger instructions before the trip. Use the responsible team to resolve assignment changes.','เปิด Boat เพื่อตรวจงานเดินเรือตามสิทธิ์ ตรวจวันให้บริการ เรือ ลูกเรือ และคำแนะนำผู้โดยสารก่อนเดินทาง ประสานทีมผู้รับผิดชอบเมื่อต้องเปลี่ยนการจัดงาน'),
 HEAD_CAPTAIN:pair('Review the boat jobs available to your account and coordinate the responsible captains. Confirm dates, vessels and crew in the work record; the role title alone does not grant assignment-edit rights.','ตรวจงานเรือที่บัญชีเข้าถึงได้และประสานกัปตันผู้รับผิดชอบ ยืนยันวัน เรือ และลูกเรือจากรายการงาน ชื่อตำแหน่งไม่ได้เพิ่มสิทธิ์แก้ไขการจัดงานโดยอัตโนมัติ'),
 ASSISTANT_CAPTAIN:pair('Review your permitted boat jobs, service dates and crew instructions. Follow the assigned captain’s coordination and use only actions available in the job record.','ตรวจงานเรือ วันให้บริการ และคำแนะนำลูกเรือตามสิทธิ์ ประสานกัปตันที่ได้รับมอบหมายและใช้เฉพาะคำสั่งที่มีในรายการงาน'),
 DRIVER:pair('Open Driver to review your permitted vehicle jobs. Check the service date, vehicle, pickup details and passengers before the transfer. Review changes in the work record before departing.','เปิด Driver เพื่อตรวจงานรถตามสิทธิ์ ตรวจวันให้บริการ รถ จุดรับ และผู้โดยสารก่อนรับส่ง ตรวจการเปลี่ยนแปลงในรายการงานก่อนออกเดินทาง'),
 HEAD_DRIVER:pair('Open Driver and review the permitted transfer jobs and allocation. Confirm vehicles, drivers, pickup dates and passenger details before saving an authorized assignment.','เปิด Driver ตรวจงานรับส่งและการจัดสรรตามสิทธิ์ ตรวจรถ คนขับ วันรับ และรายละเอียดผู้โดยสารก่อนบันทึกการมอบหมาย'),
 HOUSEKEEPING:pair('Open the cleaning work area shown in your navigation. Review your assigned zone, schedule and instructions, then record progress using available actions. Acceptance is a separate authorized step.','เปิดส่วนงานทำความสะอาดในเมนู ตรวจพื้นที่ ตาราง และคำแนะนำที่ได้รับมอบหมาย แล้วบันทึกความคืบหน้าด้วยคำสั่งที่มี การตรวจรับเป็นอีกขั้นตอนตามสิทธิ์'),
 HEAD_HOUSEKEEPING:pair('Review cleaning zones, schedules and work within your permitted team. Assign or accept work only through the actions available to your account, checking the work record before confirmation.','ตรวจพื้นที่ ตาราง และงานทำความสะอาดในขอบเขตทีม มอบหมายหรือตรวจรับผ่านคำสั่งที่บัญชีได้รับสิทธิ์ โดยตรวจรายการก่อนยืนยัน'),
}
const roleThai={BOOKING:'เจ้าหน้าที่ Booking',HEAD_BOOKING:'ผู้จัดการฝ่าย Booking',SALES:'ฝ่ายขาย',ACCOUNT:'ฝ่ายบัญชี',GUIDE:'ไกด์',HEAD_GUIDE:'หัวหน้าไกด์',ASSISTANT_TOUR_GUIDE:'ผู้ช่วยไกด์',CAPTAIN:'กัปตัน',HEAD_CAPTAIN:'หัวหน้ากัปตัน',ASSISTANT_CAPTAIN:'ผู้ช่วยกัปตัน',DRIVER:'คนขับรถ',HEAD_DRIVER:'หัวหน้าคนขับรถ',HOUSEKEEPING:'แม่บ้าน',HEAD_HOUSEKEEPING:'หัวหน้าแม่บ้าน'}
function manual(role){
 const title=pair(role==='ADMIN_MANAGER'?'Programmer / System Administrator':role==='MANAGER'?'General Manager':roleNames[role],role==='ADMIN_MANAGER'?'โปรแกรมเมอร์ / ผู้ดูแลระบบ':role==='MANAGER'?'ผู้จัดการทั่วไป':roleThai[role])
 const sections=[section('Your workspace','พื้นที่ทำงานของคุณ','Sign in with your own staff account. The navigation shows work areas permitted to that account. User Info contains your profile, language and sign-out controls.','เข้าสู่ระบบด้วยบัญชีพนักงานของตนเอง เมนูแสดงส่วนงานตามสิทธิ์ของบัญชี User Info มีโปรไฟล์ ภาษา และออกจากระบบ')]
 if(role==='ADMIN_MANAGER'){
  sections.push(section('System dashboard','Dashboard ผู้ดูแลระบบ','The four monitoring cards, error/warning histories, deployments, background jobs and resource rings show Not connected until their data source is available. A dash is not zero. System performance shows the latest dashboard request duration from this browser, not historical server performance.','การ์ดติดตามระบบ ประวัติข้อผิดพลาด คำเตือน การนำขึ้นระบบ งานเบื้องหลัง และทรัพยากรแสดงว่ายังไม่เชื่อมต่อจนกว่าจะมีแหล่งข้อมูล ขีดไม่ได้หมายถึงศูนย์ ประสิทธิภาพที่แสดงคือเวลาคำขอ Dashboard ล่าสุดจากเบราว์เซอร์นี้ ไม่ใช่ประวัติเซิร์ฟเวอร์'))
  sections.push(section('Tools and notes','เครื่องมือและบันทึก','Quick tools open existing authorized workspaces. Add a note using + Add note, enter text and save; tick it when complete. Notes exist only for this visit and clear when you leave the dashboard. The bell currently has no connected notification feed.','Quick tools เปิดส่วนงานเดิมตามสิทธิ์ เพิ่มบันทึกด้วย + Add note กรอกข้อความแล้วบันทึก ติ๊กเมื่องานเสร็จ บันทึกอยู่เฉพาะการเข้าชมครั้งนี้และหายเมื่อออกจาก Dashboard กระดิ่งยังไม่มีแหล่งแจ้งเตือนที่เชื่อมต่อ'))
  sections.push(section('All role guides','คู่มือทุกตำแหน่ง','Company-wide Admin Managers can open all role guides. This visibility does not change the permissions of another account. Select a role from the guide index to read its instructions.','Admin Manager ระดับบริษัทเปิดคู่มือได้ทุกตำแหน่ง การเห็นคู่มือไม่เปลี่ยนสิทธิ์ของบัญชีอื่น เลือกตำแหน่งจากหน้ารวมคู่มือเพื่ออ่านคำแนะนำ'))
 }else if(['BOOKING','HEAD_BOOKING'].includes(role)){
  sections.push(section('Customers and the next 30 days','ลูกค้าและภาพรวม 30 วัน','Both Booking roles see all customers and confirmed/completed arrivals over the next 30 days. Select a chart bar for program totals.','ทั้งสองตำแหน่ง Booking เห็นลูกค้าทั้งหมดและยอดเดินทางที่ยืนยันหรือเสร็จสิ้นใน 30 วัน เลือกแท่งกราฟเพื่อดูยอดแยกโปรแกรม'))
  sections.push(section('Booking responsibility','ผู้รับผิดชอบ Booking',role==='HEAD_BOOKING'?'Review every assistant’s work. In Bookings, choose Assign booking and select the responsible staff member.':'You can read every booking, but edit and update only your assigned bookings. Ask the Booking Manager to assign or transfer work.',role==='HEAD_BOOKING'?'ตรวจงานเจ้าหน้าที่ทุกคน จากหน้า Bookings เลือกมอบหมาย Booking และเลือกผู้รับผิดชอบ':'ดูการจองทั้งหมดได้ แต่แก้ไขเฉพาะรายการที่ตนรับผิดชอบ ติดต่อ Booking Manager เพื่อมอบหมายหรือโอนงาน'))
  sections.push(section('Booking commission','ค่าคอมมิชชั่น Booking','If either the Agent or Tour Program excludes Booking commission, no commission applies. Direct bookings use the program condition. Saved rates and beneficiary remain attached to the booking; reassignment does not transfer commission. Missing rates are unconfigured, not zero. Amounts are estimates, not payroll payments.','หาก Agent หรือโปรแกรมทัวร์ไม่มีค่าคอม ให้ไม่มีค่าคอม รายการตรงใช้เงื่อนไขโปรแกรม อัตราและผู้ได้รับค่าคอมที่บันทึกไว้คงอยู่กับ Booking การมอบหมายงานใหม่ไม่โอนค่าคอม อัตราที่ไม่กำหนดไม่ใช่ศูนย์ ยอดเป็นประมาณการ ไม่ใช่รายการจ่ายเงินเดือน'))
 }else if(role==='MANAGER'){
  sections.push(section('Read the management dashboard','อ่าน Dashboard ผู้จัดการ','Customers and booking totals use confirmed/completed arrivals for the stated period. Click a bar in Customers next 30 days to see program totals. Top agents uses the reporting season from 15 October through 15 May inclusive; outside the season it shows the upcoming one. Monthly overview covers the last six months. Reporting periods do not change program availability.','ยอดลูกค้าและการจองนับวันมาถึงของรายการยืนยันหรือเสร็จสิ้นในช่วงที่ระบุ คลิกแท่ง Customers next 30 days เพื่อดูยอดตามโปรแกรม Top agents ใช้ฤดูกาลรายงาน 15 ตุลาคม–15 พฤษภาคม รวมวันสุดท้าย นอกฤดูกาลแสดงรอบถัดไป ส่วน Monthly overview ครอบคลุมหกเดือนล่าสุด ช่วงรายงานไม่เปลี่ยนวันเปิดบริการของโปรแกรม'))
  sections.push(section('Daily follow-up','ติดตามงานประจำวัน','Switch Today and Tomorrow to inspect booking statuses. Transport and boat cards link to the existing work areas. Open the record there before making changes. Revenue and expense summaries are not connected; a dash is not a zero balance.','สลับ Today และ Tomorrow เพื่อตรวจสถานะการจอง การ์ดรถและเรือลิงก์ไปส่วนงานเดิม เปิดรายการที่นั่นก่อนแก้ไข รายรับและรายจ่ายยังไม่เชื่อมต่อ ขีดไม่ได้หมายถึงยอดเป็นศูนย์'))
 }else{
  sections.push(section('Dashboard status','สถานะ Dashboard','Review your permitted work using Today and Tomorrow. Run links open the selected job; queue links open the work area. Counts cover all authorized records; previews show at most 10 rows. DONE awaits acceptance. Preparation quantities remain separate by item and unit. Unconfigured sources display a dash, not zero.','ตรวจงานตามสิทธิ์โดยสลับ Today และ Tomorrow ลิงก์เที่ยวเปิดงานนั้น ส่วนลิงก์คิวเปิดหน้าทำงาน ยอดนับครบชุดตามสิทธิ์ ตารางย่อแสดงสูงสุด 10 รายการ DONE คือรอตรวจรับ จำนวนเตรียมของแยกรายการและหน่วย แหล่งข้อมูลที่ยังไม่ตั้งค่าแสดงขีด ไม่แทนด้วยศูนย์'))
  const duty=duties[role];sections.push({heading:pair('Your role’s work','งานตามตำแหน่ง'),body:duty})
 }
 if(['ADMIN_MANAGER','MANAGER','BOOKING','HEAD_BOOKING','GUIDE','HEAD_GUIDE','ASSISTANT_TOUR_GUIDE','CAPTAIN','HEAD_CAPTAIN','ASSISTANT_CAPTAIN'].includes(role))sections.push(...jobCodeManualSections())
 sections.push(...capacityManualSections(role))
 sections.push(section('Access and recovery','สิทธิ์และการแก้ปัญหา','Only guides for your assigned roles are available, except company-wide Admin Managers. If a direct guide link is denied, return to User guides. Refresh retries a failed read; contact your Manager if an expected work area is missing.','คุณเปิดคู่มือได้เฉพาะตำแหน่งที่ได้รับมอบหมาย ยกเว้น Admin Manager ระดับบริษัท หากลิงก์คู่มือถูกปฏิเสธ ให้กลับหน้าคู่มือผู้ใช้ เมื่ออ่านข้อมูลไม่สำเร็จให้ลองใหม่ และติดต่อผู้จัดการหากส่วนงานที่ต้องใช้ไม่ปรากฏ'))
 return {role,title,sections}
}
export function visibleManualRoles(profile){
 if(profile?.status!=='ACTIVE')throw new AccessError('PERMISSION_DENIED',403)
 if((profile.roles||[]).some(g=>(g.roleCode||g.code)==='ADMIN_MANAGER'&&g.scope==='COMPANY'))return Object.keys(roleNames)
 return [...new Set((profile.roles||[]).map(g=>g.roleCode||g.code).filter(code=>Object.hasOwn(roleNames,code)))]
}
export function readManuals(profile,role){
 const allowed=visibleManualRoles(profile)
 if(role&&!allowed.includes(role))throw new AccessError('PERMISSION_DENIED',403)
 return {roles:allowed.map(code=>({role:code,title:manual(code).title})),manual:role?manual(role):null}
}
