// Bulk synthetic import, not a shortcut in customer APIs. Every committed batch proves all affected boat pools feasible.
import {assert,id,code,NAME,TAG,day,date,stamp,db,actor,stage,close,requireApply,safeError,saveReport} from './common.mjs'
import {dailyBookings,windows,chosenWindows} from './plan.mjs'
import {bookingJourney,bookingQuote} from '../../../packages/contracts/booking-plan.js'
import {componentQuantity} from '../../../packages/contracts/operations.js'
import {bookingCommissionSnapshot} from '../../src/modules/operations/booking-commission.js'
import {capacityInclude,poolContext,solveContext} from '../../src/modules/operations/capacity-core.js'
let current='initialize'
try{
 requireApply();const admin=await actor(),programs=await db.tourProgram.findMany({where:{code:{startsWith:code('T-')}},include:{components:{include:{resource:true}}}}),agents=await db.businessPartner.findMany({where:{code:{startsWith:code('A')}}}),rates=await db.agentTourPrice.findMany({where:{tourId:{in:programs.map(p=>p.id)}}})
 assert.equal(programs.length,8)
 await stage('readiness',async tx=>{const list=Array.from({length:49},(_,i)=>windows(i-2)).flat();const records=list.map(({offers,...p})=>p),offers=list.flatMap(p=>p.offers.map((o,i)=>({id:id('offer-'+p.id+'-'+i),poolId:p.id,...o})));for(const o of offers.filter(o=>o.status==='READY')){const p=records.find(p=>p.id===o.poolId);assert.equal(offers.filter(x=>x.status==='READY'&&x.vehicleId===o.vehicleId&&records.some(q=>q.id===x.poolId&&q.startsAt<p.endsAt&&q.endsAt>p.startsAt)).length,1,'Double-booked fixture vehicle')};await tx.capacityPool.createMany({data:records});await tx.capacityOffer.createMany({data:offers});await tx.auditEvent.create({data:{actorId:admin,action:'demo45.readiness.seeded',details:{dataset:TAG,windows:records.length,offers:offers.length}}});return {windows:records.length,offers:offers.length}})
 function build(s){const d=day(s.n),p=programs.find(p=>p.id===id('tour-'+s.tour));assert.ok(p);const journey=bookingJourney(p,d,'PENDING',null),first=journey.outboundDate||journey.returnDate,last=journey.returnDate||first,nights=Math.round((Date.parse(last)-Date.parse(first))/86400000)
  const children=s.pax>3&&s.j%3===0?Math.min(2,s.pax-1):0,adults=s.pax-children,agentIndex=s.j%4===3?null:1+(s.n*2+s.j+30)%15,agent=agentIndex?agents.find(a=>a.id===id('agent-'+agentIndex)):null,rate=agent?rates.find(r=>r.agentId===agent.id&&r.tourId===p.id):null
  const owner=id('staff-booking-'+(1+(s.n+s.j+90)%3)),key='B'+s.n+'-'+s.j,bookingId=id(key),tripId=id('trip-'+key),direction=journey.outboundDate?(journey.returnStatus==='NONE'||journey.returnStatus==='OTHER'?'OUTBOUND':'BOTH'):'RETURN'
  const lines=p.components.map(c=>{const r=c.resource,quantity=componentQuantity(c,adults,children,nights),selected=quantity>0&&(c.selection==='OPTIONAL'?r.id===id('res-VAN')?s.transfer:s.j%3===0:true);return {id:id('line-'+key+'-'+c.id),bookingId,resourceId:r.id,quantity,selected,included:['INCLUDED','REQUIRED'].includes(c.selection),usagePoint:c.usagePoint,dispatchDirection:direction,unitPrice:['INCLUDED','REQUIRED'].includes(c.selection)?'0':String(r.salePrice),snapshot:{name:r.name,code:r.code,baseUnit:r.baseUnit,kind:r.kind,category:r.category,day:c.day,notes:c.notes,basis:c.basis,selection:c.selection,componentId:c.id,componentVersion:c.version,basisQuantity:c.quantity,occupancy:r.occupancy,removalCredit:c.removalCredit?.toString()??null,demo:true,demoDataset:TAG}}})
  const adultPrice=String(rate?.adultPrice??p.adultPrice),childPrice=String(rate?.childPrice??p.childPrice),quote=bookingQuote({adultPrice,childPrice,adults,children,lines});assert.ok(quote.total!==null);assert.ok(lines.some(l=>l.selected))
  const programSnapshot={tourId:p.id,name:p.name,route:p.route,bookingOwnedTrip:true,journeyMode:p.journeyMode,durationDays:p.durationDays,startsAt:stamp(first,'00:00').toISOString(),endsAt:stamp(last,'23:59').toISOString(),savedAt:new Date().toISOString(),allowedPaymentTerms:agent?agent.allowedPaymentTerms:['PREPAID','COUNTER'],priceSource:agent?{kind:'AGENT',agentId:agent.id,rateId:rate.id,rateVersion:rate.version,agreementId:rate.agreementId}:{kind:'DIRECT',programId:p.id,programVersion:p.version},capacitySelections:chosenWindows(s,journey),demo:true,demoDataset:TAG,fixtureScenario:s.wait?'WAITING_TEAM':s.tour==='OPEN'?'OPEN_RETURN':s.status,capacityReview:s.wait?{status:'WAITING_TEAM',reason:'Whole Booking exceeds ready capacity; discuss additional vessel or alternate date'}:null}
  const booking={id:bookingId,code:code(key),name:NAME+d+' Group '+String(s.j+1).padStart(2,'0')+(s.wait?' · WAITING TEAM':''),tripId,adults,children,status:s.status,adultPrice,childPrice,programSnapshot,requestHash:code(key).padEnd(64,'0'),createdById:owner,assigneeId:owner,agentId:agent?.id||null,agentName:agent?.name||null,agentPhone:agent?'0000000000':null,agentReference:agent?code('REF-'+s.n+'-'+s.j):null,contactPhone:'0000000000',channelId:id('channel-'+(agent?'AGENT':['WEB','PHONE','LINE','WALKIN'][(s.n+s.j+100)%4])),hotelId:s.transfer?id('hotel-'+(1+s.j%6)):null,hotel:s.transfer?NAME+'Hotel '+(1+s.j%6):null,room:s.transfer?'DEMO-'+(101+s.j):null,pickupPoint:s.transfer?'DEMO hotel lobby':null,dropoffPoint:s.transfer?'DEMO hotel lobby':null,outboundDate:journey.outboundDate?date(journey.outboundDate):null,returnDate:journey.returnDate?date(journey.returnDate):null,returnStatus:journey.returnStatus,allergyStatus:s.status==='DRAFT'&&!s.wait?'UNKNOWN':s.j===4?'HAS':'NONE',allergies:s.j===4?'DEMO guest avoids nuts':null,specialRequirements:[],requestNotes:'DEMO ONLY — synthetic Booking, passenger identities, prices and dates. No real reservation or payment.',paymentTerms:agent?'AGENT_CREDIT':s.j%2?'PREPAID':'COUNTER',commissionSnapshot:bookingCommissionSnapshot({program:p,agent,adults,children,existing:null,ownerId:owner})}
  return {booking,lines,trip:{id:tripId,code:code('TR-'+s.n+'-'+s.j),name:booking.name,tourId:p.id,startsAt:stamp(first,'00:00'),endsAt:stamp(last,'23:59'),capacity:s.pax,status:'OPEN'}}
 }
 const batches=Array.from({length:45},(_,n)=>dailyBookings(n));const summary=[]
 for(let start=0;start<45;start+=5){current='bookings-'+start;const selected=batches.slice(start,start+5).flat(),built=selected.map(build);const res=await stage(current,async tx=>{await tx.operationTrip.createMany({data:built.map(b=>b.trip)});await tx.tourBooking.createMany({data:built.map(b=>b.booking)});await tx.bookingComponent.createMany({data:built.flatMap(b=>b.lines)});const dates=[...new Set(built.filter(b=>b.booking.status==='CONFIRMED').flatMap(b=>[b.booking.outboundDate,b.booking.returnDate].filter(Boolean).map(d=>d.toISOString().slice(0,10))))];const pools=await tx.capacityPool.findMany({where:{kind:'BOAT',code:{startsWith:'D45-'},serviceDate:{in:dates.map(date)}},include:capacityInclude});for(const p of pools){const context=await poolContext(tx,p),result=solveContext(context);assert.equal(result.status,'FEASIBLE',p.code+': '+result.reason)}await tx.auditEvent.create({data:{actorId:admin,action:'demo45.bookings.imported',details:{dataset:TAG,from:day(start),through:day(Math.min(44,start+4)),bookings:built.length,synthetic:true,wholeGroupProof:true,realPayments:0}}});return {bookings:built.length,confirmed:built.filter(b=>b.booking.status==='CONFIRMED').length}});summary.push(res)}
 const groups=await db.tourBooking.groupBy({by:['status'],where:{programSnapshot:{path:['demoDataset'],equals:TAG}},_count:{id:true},_sum:{adults:true,children:true}})
 saveReport('bookings-summary',{from:day(0),through:day(44),days:45,groups,created:batches.flat().length});console.log(JSON.stringify({result:'BOOKINGS_READY',days:45,groups}))
}catch(e){safeError(e,current)}finally{await close()}
