// Retained historical completion and live customer workflow examples, without real financial transfers.
import {assert,id,code,NAME,TAG,day,db,actor,stage,close,requireApply,safeError,saveReport,customers,hash} from './common.mjs'
import {getBlueprint,saveBooking,bookingStatus} from '../../src/modules/operations/bookings.js'
import {saveRun,dispatchCommand} from '../../src/modules/operations/dispatch.js'
import {stockCommand} from '../../src/modules/operations/stock.js'
import {quoteRequest,submitCustomerRequest,commandCustomerRequest,cancelCustomerRequest} from '../../src/modules/commerce/service.js'
let current='extras'
try{requireApply();const admin=await actor(),report={}
 report.history=await stage('historical-completion',async(tx,p)=>{
 const d='2026-09-24',input={tourId:id('tour-D1'),serviceDate:d,adults:2,children:1,returnStatus:'PENDING'};const blueprint=await getBlueprint(p,admin,new URLSearchParams(input));let b=(await saveBooking(p,id('staff-booking-1'),{...input,id:id('historic-booking'),version:0,name:NAME+'Historical completed day trip',allergyStatus:'NONE',specialRequirements:[],paymentTerms:'COUNTER',requestNotes:'DEMO completed journey, not a real guest or trip',lines:blueprint.lines.map(l=>({componentId:l.componentId,resourceId:l.resourceId,quantity:l.quantity,selected:l.quantity>0&&l.resource.id!==id('res-VAN')}))})).row
 await tx.tourBooking.update({where:{id:b.id},data:{programSnapshot:{...b.programSnapshot,demo:true,demoDataset:TAG,fixtureScenario:'HISTORICAL_COMPLETED'}}});const confirmed=await bookingStatus(p,admin,{id:id('historic-confirm'),bookingId:b.id,version:b.version,action:'CONFIRM'});assert.equal(confirmed.status,'CONFIRMED');b=await tx.tourBooking.findUnique({where:{id:b.id},include:{lines:{include:{resource:true}}}})
 const staff=[['captain-3','CAPTAIN'],['guide-3','GUIDE'],['assistant-guide-5','ASSISTANT_TOUR_GUIDE'],['assistant-guide-6','ASSISTANT_TOUR_GUIDE'],['assistant-captain-5','ASSISTANT_CAPTAIN'],['assistant-captain-6','ASSISTANT_CAPTAIN']].map(([key,role])=>({userId:id('staff-'+key),role})),runs=[]
 for(const direction of ['OUTBOUND','RETURN']){const back=direction==='RETURN';const r=(await saveRun(p,admin,{id:id('HIST-'+direction),version:0,code:code('HIST-'+direction),name:NAME+'Historical '+direction,kind:'BOAT',direction,period:back?'PM':'AM',resourceId:id('res-SEA'),vehicleId:id('boat-3'),capacity:65,startsAt:d+(back?' 15:00':' 09:00'),endsAt:d+(back?' 16:30':' 10:30'),staff})).row;runs.push(r);const line=b.lines.find(l=>l.resourceId===id('res-SEA'));await dispatchCommand(p,admin,{id:id('HIST-ASSIGN-'+direction),runId:r.id,version:r.version,action:'ASSIGN',bookingLineId:line.id,adults:2,children:1});const a=await tx.dispatchAssignment.findFirst({where:{runId:r.id,bookingLineId:line.id}});await dispatchCommand(p,admin,{id:id('HIST-ACTUAL-'+direction),runId:r.id,version:r.version+1,action:'ACTUAL',assignmentId:a.id,actualAdults:2,actualChildren:1})}
 let issued=0
 for(const line of b.lines.filter(l=>l.selected&&l.resource.kind!=='SERVICE')){current='history-issue-'+line.resource.code;const balance=await tx.stockBalance.findFirst({where:{locationId:id('store-MAIN'),lot:{resourceId:line.resourceId},condition:'READY',quantity:{gte:line.quantity}}});assert.ok(balance);const movement=(await stockCommand(p,admin,{id:id('HIST-ISSUE-'+line.id),action:'ISSUE',balanceId:balance.id,version:balance.version,quantity:line.quantity,destinationId:id('store-BOAT3'),custodian:NAME+'Historical crew',bookingLineId:line.id,runId:runs[0].id,note:'DEMO issued stock for historical workflow example'})).row;const equipment=line.resource.kind==='EQUIPMENT';await stockCommand(p,admin,{id:id('HIST-RETURN-'+line.id),action:'SETTLE',issueId:movement.details.issueId,quantity:line.quantity,disposition:equipment?(line.resourceId===id('res-MASK')?'RETURN_DAMAGED':'RETURN_READY'):'CONSUMED',...(equipment?{locationId:id('store-WASH')}:{}) ,note:'DEMO full settlement; returned equipment versus consumed water and fruit'});issued++}
 const fresh=await tx.tourBooking.findUnique({where:{id:b.id}});const result=await bookingStatus(p,admin,{id:id('HIST-COMPLETE'),bookingId:b.id,version:fresh.version,action:'COMPLETE'});assert.equal(result.status,'COMPLETED');return {bookingId:b.id,bookingCode:b.code,completed:1,settledResources:issued,realPayment:false}
 },{timeout:900000})
 report.preparation=await stage('tomorrow-preparation',async(tx,p)=>{const run=await tx.dispatchRun.findUnique({where:{id:id('TMR-B1-O')},include:{assignments:{include:{bookingLine:{include:{booking:{include:{lines:{include:{resource:true}}}}}}}}}});assert.ok(run);const booking=run.assignments[0].bookingLine.booking;let items=0;for(const line of booking.lines.filter(l=>l.selected&&[id('res-MASK'),id('res-WATER')].includes(l.resourceId))){const balance=await tx.stockBalance.findFirst({where:{locationId:id('store-MAIN'),lot:{resourceId:line.resourceId},condition:'READY',quantity:{gte:line.quantity}}});await stockCommand(p,id('staff-assistant-guide-1'),{id:id('TMR-PREP-'+line.id),action:'ISSUE',balanceId:balance.id,version:balance.version,quantity:line.quantity,destinationId:id('store-BOAT1'),custodian:NAME+'Assistant guide 1',bookingLineId:line.id,runId:run.id,note:'DEMO pre-trip preparation: this group is partly ready; other supplies remain to prepare'});items++}return {groupsPartlyPrepared:1,resourceLines:items,runId:run.id}})
 report.members=await stage('member-examples',async(tx,p)=>{const outcomes=[];const cases=[['pending',0,5,3],['wait',1,6,68],['accepted',2,9,3],['proposed',2,11,4],['rejected',0,16,2],['cancelled',1,18,2]]
 for(const [key,index,n,pax]of cases){current='member-'+key;const c=customers[index],user={id:c.id,email_confirmed_at:new Date().toISOString()};const input={id:id('request-'+key),tourId:id('tour-D1'),serviceDate:day(n),adults:pax,children:0,name:c.displayName+' · '+key,phone:'0000000000',allergyStatus:'NONE',allergies:'',notes:'DEMO ONLY — synthetic customer workflow; no real request or payment',optionalIds:[],capacitySelections:[],allowWaitlist:true};const quote=await quoteRequest(tx,input);input.quoteKey=hash(quote);const result=await submitCustomerRequest(p,user,input);assert.equal(result.status,key==='wait'?'WAITING_TEAM':'REQUESTED');if(key==='accepted'){const accepted=await commandCustomerRequest(p,admin,{id:id('accept-'+key),requestId:result.id,version:1,action:'ACCEPT',note:'DEMO accepted after real capacity validation; still unpaid'});assert.equal(accepted.status,'AWAITING_PAYMENT');const b=await tx.tourBooking.findUnique({where:{id:accepted.bookingId}});await tx.tourBooking.update({where:{id:b.id},data:{programSnapshot:{...b.programSnapshot,demo:true,demoDataset:TAG,fixtureScenario:'MEMBER_ACCEPTED'}}})}if(key==='proposed')await commandCustomerRequest(p,admin,{id:id('propose-'+key),requestId:result.id,version:1,action:'PROPOSE_DATE',proposedDate:day(12),note:'DEMO proposed alternative; customer must explicitly accept new date and price'});if(key==='rejected')await commandCustomerRequest(p,admin,{id:id('reject-'+key),requestId:result.id,version:1,action:'REJECT',note:'DEMO rejected request for testing; not a real customer refusal'});if(key==='cancelled')await cancelCustomerRequest(p,user,{requestId:result.id,version:1});const stored=await tx.customerRequest.findUnique({where:{id:result.id}});outcomes.push({key,id:result.id,member:c.key,status:stored.status,bookingId:stored.bookingId})}
 return {requests:outcomes,realCharges:0,emailsSent:0}}
 ,{timeout:900000})
 saveReport('extra-scenarios',report);console.log(JSON.stringify({result:'EXTRA_SCENARIOS_READY',completed:report.history.completed,preparation:report.preparation.resourceLines,memberRequests:report.members.requests.length}))
}catch(e){safeError(e,current)}finally{await close()}
