// Synthetic catalogue only. Prefix-isolated deterministic IDs; completed stages preserve user edits.
import {assert,id,code,NAME,TAG,day,date,db,actor,stage,close,requireApply,safeError,saveReport} from './common.mjs'
export const specs=[['D1','Surin Day Trip Classic','FIXED',1,2500,1500],['D1P','Surin Day Trip Plus','FIXED',1,2800,1800],['D1F','Surin Family Day Trip','FIXED',1,2400,1400],['N2','Surin Tent 2 Days 1 Night','FIXED',2,4300,2600],['N3','Surin Tent 3 Days 2 Nights','FIXED',3,5900,3600],['OUT','Surin Outbound Boat Ticket','OUTBOUND_ONLY',null,1000,700],['RET','Surin Return Boat Ticket','RETURN_ONLY',null,1000,700],['OPEN','Surin Open Return Ticket','OPEN_RETURN',null,1900,1200]]
export const rs=[['SEA','Boat passage','SERVICE','TOUR_BOAT','PERSON',0,{serviceMode:'JOIN',origin:'DEMO Khura Buri pier',destination:'DEMO Surin Islands'}],['VAN','Hotel transfer','SERVICE','TRANSFER','PERSON',200,{origin:'DEMO hotel zone',destination:'DEMO pier'}],['LUNCH','Island lunch','SERVICE','MEAL','PERSON_MEAL',150,{mealPeriod:'LUNCH'}],['DINNER','Island dinner','SERVICE','MEAL','PERSON_MEAL',150,{mealPeriod:'DINNER'}],['BREAKFAST','Island breakfast','SERVICE','MEAL','PERSON_MEAL',100,{mealPeriod:'BREAKFAST'}],['TENT','Tent for two','SERVICE','ACCOMMODATION','ROOM_NIGHT',700,{accommodationType:'STANDARD_TENT',occupancy:2,verificationStatus:'VERIFIED'}],['MASK','Snorkel mask','EQUIPMENT','SNORKEL_MASK','PIECE',0,{size:'Standard'}],['FINS','Fins','EQUIPMENT','FINS','PAIR',50,{size:'M'}],['TOWEL','Towel','EQUIPMENT','TOWEL','PIECE',50,{size:'Standard'}],['VESTA','Adult life jacket','EQUIPMENT','LIFEJACKET','PIECE',0,{size:'Adult'}],['VESTC','Child life jacket','EQUIPMENT','LIFEJACKET','PIECE',0,{size:'Child'}],['WATER','Drinking water 600ml','CONSUMABLE','WATER','BOTTLE',10,{packSize:12,caseSize:24}],['MELON','Watermelon','CONSUMABLE','WATERMELON','FRUIT',90,{}],['PINE','Pineapple','CONSUMABLE','PINEAPPLE','FRUIT',45,{}]]
export async function seedMasters(){const admin=await actor();return stage('masters',async tx=>{
 const agents=Array.from({length:15},(_,i)=>({id:id('agent-'+(i+1)),code:code('A'+String(i+1).padStart(2,'0')),name:NAME+['Andaman','Coral','Blue Sea','Island Time','Southern Sun','Ocean Way','Palm','Seabreeze','Lagoon','Tropical','Pearl','Sandy Beach','Horizon','Sunset','Green Trail'][i]+' Travel',status:'ACTIVE',roles:['SALES_AGENT'],contactName:'DEMO Agent Contact '+(i+1),phone:'0000000000',email:`d45.agent${i+1}@greenviewtour.test`,bookingCommissionEligible:i%4!==0,allowedPaymentTerms:['PREPAID','COUNTER','AGENT_CREDIT'],defaultPaymentTerms:'AGENT_CREDIT',paymentTerms:'DEMO ONLY — negotiated sample, not a signed commercial contract'}))
 await tx.businessPartner.createMany({data:[...agents,{id:id('supplier'),code:code('SUPPLY'),name:NAME+'Water and fruit supplier',status:'ACTIVE',roles:['SERVICE_PROVIDER'],allowedPaymentTerms:['COUNTER'],defaultPaymentTerms:'COUNTER'},{id:id('transport-provider'),code:code('TRANSPORT'),name:NAME+'Van partner',status:'ACTIVE',roles:['TRANSPORT_PROVIDER'],allowedPaymentTerms:['COUNTER'],defaultPaymentTerms:'COUNTER'}]})
 await tx.salesChannel.createMany({data:['AGENT','WEB','PHONE','LINE','WALKIN'].map((k,i)=>({id:id('channel-'+k),code:code('CH-'+k),name:NAME+k,status:'ACTIVE',kind:i===0?'AGENT':'DIRECT'}))})
 await tx.pickupLocation.createMany({data:Array.from({length:6},(_,i)=>({id:id('hotel-'+(i+1)),code:code('HOTEL'+(i+1)),name:NAME+'Hotel '+(i+1),kind:'HOTEL',status:'ACTIVE',zone:i<3?'DEMO nearby pier':'DEMO north pickup',pickupNotes:'DEMO lobby pickup; no real hotel address'}))})
 await tx.fleetVehicle.createMany({data:[...[30,45,65].map((capacity,i)=>({id:id('boat-'+(i+1)),code:code('BOAT'+(i+1)),name:NAME+'Boat '+(i+1)+' · '+capacity+' pax',status:'ACTIVE',kind:'SPEEDBOAT',capacity,totalCapacity:capacity+6,expectedCrew:6,engineCount:i+2,ownership:'GREENVIEW',purposes:['PASSENGER_TRANSFER'],registration:'DEMO-BOAT-'+(i+1),notes:'DEMO ONLY: capacity excludes captain, guide and four assistants'})),...[1,2].map(i=>({id:id('van-'+i),code:code('VAN'+i),name:NAME+'Company Van '+i,status:'ACTIVE',kind:'VAN',capacity:12,totalCapacity:13,expectedCrew:1,ownership:'GREENVIEW',purposes:['PASSENGER_TRANSFER'],registration:'DEMO-VAN-'+i,notes:'DEMO 12 passenger planning capacity, not a legal vehicle specification'}))]})
 await tx.operationResource.createMany({data:rs.map(([k,name,kind,category,baseUnit,price,extra])=>({id:id('res-'+k),code:code('R-'+k),name:NAME+name,kind,category,baseUnit,status:'ACTIVE',ownership:'GREENVIEW',salePrice:String(price),costPrice:String(k==='WATER'?6:k==='MELON'?60:k==='PINE'?30:kind==='EQUIPMENT'?250:Math.round(price*.6)),notes:'DEMO ONLY — synthetic price, not actual procurement cost',...extra}))})
 await tx.stockLocation.createMany({data:[['MAIN','Main stock','WAREHOUSE'],['WASH','Cleaning and returns','OTHER'],['BOAT1','Boat 1 stock','BOAT'],['BOAT2','Boat 2 stock','BOAT'],['BOAT3','Boat 3 stock','BOAT']].map(([k,name,kind])=>({id:id('store-'+k),code:code('S-'+k),name:NAME+name,kind,status:'ACTIVE',notes:'DEMO inventory only'}))})
 await tx.tourProgram.createMany({data:specs.map(([k,name,journeyMode,durationDays,adultPrice,childPrice])=>({id:id('tour-'+k),code:code('T-'+k),name:NAME+name,journeyMode,durationDays,status:'ACTIVE',ownership:'GREENVIEW',confirmationMode:'REQUEST',supplierPricing:'NOT_SET',adultPrice:String(adultPrice),childPrice:String(childPrice),publicStatus:'PUBLISHED',slug:'demo45-'+k.toLowerCase(),tourType:k.startsWith('N')?'OVERNIGHT':k.startsWith('D')?'DAY_TRIP':'TRANSFER',description:'DEMO ONLY — retained Preview testing programme. Not a real offer or travel date.',route:'DEMO Khura Buri – Surin Islands',childPolicy:'DEMO child rates only; verify real age rules before sale',bookingCommissionEligible:k!=='D1F',bookingAdultCommission:'50',bookingChildCommission:'30',cancellationTerms:'DEMO sample terms. No real payment, ticket or refund.',highlights:'DEMO data for testing booking, transport, equipment and expenses'}))})
 await tx.tourSeason.createMany({data:specs.map(([k])=>({id:id('season-'+k),code:code('SEASON-'+k),name:NAME+'Preview test window',tourId:id('tour-'+k),status:'ACTIVE',startsOn:date('2026-09-24'),endsOn:date('2026-11-12'),onlineStartsOn:date('2026-09-24'),onlineEndsOn:date('2026-11-12'),bookingStartsOn:date('2026-09-01'),bookingEndsOn:date('2026-11-12'),cutoffDays:0}))})
 const components=[]
 for(const [k] of specs){const ticket=['OUT','RET','OPEN'].includes(k),keys=ticket?['SEA','VAN']:['SEA','VAN','LUNCH','MASK','FINS','TOWEL','VESTA','VESTC','WATER','MELON','PINE',...(k.startsWith('N')?['TENT','DINNER','BREAKFAST']:[])];for(const r of keys)components.push({id:id('cmp-'+k+'-'+r),tourId:id('tour-'+k),resourceId:id('res-'+r),selection:['VAN','FINS','TOWEL'].includes(r)?'OPTIONAL':r==='LUNCH'?'INCLUDED':'REQUIRED',basis:r==='TENT'?'PER_ROOM_NIGHT':['MELON','PINE'].includes(r)?'PER_BOOKING':r==='VESTA'?'PER_ADULT':r==='VESTC'?'PER_CHILD':'PER_PERSON',quantity:r==='WATER'?2:1,usagePoint:r==='VAN'?'TRANSFER':r==='TENT'?'ISLAND':'BOAT',day:1,status:'ACTIVE',...(r==='LUNCH'?{removalCredit:'150'}:{})})}
 await tx.programComponent.createMany({data:components})
 await tx.agentAgreement.createMany({data:agents.map((a,i)=>({id:id('agreement-'+(i+1)),code:code('AGREE'+(i+1)),name:NAME+'UNSIGNED test price agreement '+(i+1),agentId:a.id,startsOn:date('2026-09-01'),endsOn:date('2027-05-15'),status:'ACTIVE',signedOn:null,evidenceUrl:null}))})
 await tx.agentTourPrice.createMany({data:agents.flatMap((a,i)=>specs.map(([k,,, ,adult,child])=>({id:id('rate-'+(i+1)+'-'+k),agentId:a.id,tourId:id('tour-'+k),agreementId:id('agreement-'+(i+1)),adultPrice:String(adult-100-(i%5)*50),childPrice:String(child-50-(i%3)*30),status:'ACTIVE'})))})
 await tx.auditEvent.create({data:{actorId:admin,action:'demo45.catalogue.seeded',details:{dataset:TAG,agents:15,boats:3,companyVans:2,programmes:8,realOffers:false}}})
 return {agents:15,boats:[30,45,65],companyVans:2,tours:8,resources:rs.length,components:components.length,agentRates:120,bookingsFrom:day(0),bookingsThrough:day(44)}
 })}
if(process.argv[1]?.endsWith('/masters.mjs'))try{requireApply();saveReport('masters',await seedMasters())}catch(e){safeError(e,'masters')}finally{await close()}
