// Retained operational/financial examples. No bank actions, actual payments or real receipts.
import {assert,id,code,NAME,TAG,day,date,db,actor,stage,close,requireApply,safeError,saveReport,staff} from './common.mjs'
import {stockCommand} from '../../src/modules/operations/stock.js'
import {saveCompanyWork,commandCompanyWork} from '../../src/modules/company-work/service.js'
import {validatePayload,savePersonnelFinance,commandPersonnelFinance} from '../../src/modules/personnel-finance/service.js'
let current='support'
try{requireApply();const admin=await actor();const summary={}
 summary.stock=await stage('inventory',async(tx,p)=>{const quantities={MASK:240,FINS:180,TOWEL:240,VESTA:180,VESTC:60,WATER:4800,MELON:180,PINE:240};for(const [key,quantity]of Object.entries(quantities)){current='receive-'+key;const r=await tx.operationResource.findUnique({where:{id:id('res-'+key)}});await stockCommand(p,admin,{id:id('opening-'+key),action:'RECEIVE',resourceId:r.id,locationId:id('store-MAIN'),quantity,unit:'BASE',lotLabel:code('OPEN-'+key),receivedOn:'2026-09-24',expiresOn:key==='WATER'?'2027-05-31':['MELON','PINE'].includes(key)?'2026-10-15':undefined,unitCost:String(r.costPrice),note:'DEMO ONLY — synthetic opening inventory, no real purchase or receipt'})}
 const b=await tx.stockBalance.findFirst({where:{locationId:id('store-MAIN'),lot:{resourceId:id('res-FINS')},condition:'READY'}});await stockCommand(p,admin,{id:id('damage-fins'),action:'CONDITION',balanceId:b.id,version:b.version,quantity:3,condition:'DAMAGED',note:'DEMO defective fins set aside, not real equipment'})
 await saveCompanyWork(p,admin,{id:id('custodian'),kind:'RESPONSIBILITY',version:0,name:NAME+'Demo warehouse team',payload:{storeId:id('store-MAIN'),primaryUserId:id('staff-assistant-guide-1'),deputyUserId:id('staff-assistant-guide-2'),reason:'DEMO stock only; does not grant global warehouse permissions'}})
 return {resources:Object.keys(quantities).length,quantities,damagedFins:3}})
 summary.cleaning=await stage('cleaning',async(tx,p)=>{const head=id('staff-head-housekeeping-1'),checklist=['DEMO wipe and sanitize work surfaces','DEMO clean floor','DEMO separate damaged equipment'];let jobs=0
 for(let i=1;i<=2;i++){const zone=(await saveCompanyWork(p,head,{id:id('zone-'+i),kind:'ZONE',version:0,name:NAME+(i===1?'Pier office':'Equipment wash area'),payload:{description:'DEMO cleaning area, no real premises',checklist}})).row;const schedule=(await saveCompanyWork(p,head,{id:id('clean-schedule-'+i),kind:'SCHEDULE',version:0,name:NAME+'Cleaning team '+i,payload:{jobKind:'CLEANING',zoneId:zone.id,storeId:'',assigneeId:id('staff-housekeeping-'+i),frequency:'CUSTOM',startsOn:day(0),endsOn:day(29),customDates:Array.from({length:30},(_,n)=>day(n)),checklist}})).row;const result=await commandCompanyWork(p,head,{id:id('clean-generate-'+i),kind:'SCHEDULE',recordId:schedule.id,version:schedule.version,action:'GENERATE',data:{through:day(29)}});jobs+=result.generated
 const history=(await saveCompanyWork(p,head,{id:id('clean-history-'+i),kind:'SCHEDULE',version:0,name:NAME+'Historical cleaning '+i,payload:{jobKind:'CLEANING',zoneId:zone.id,storeId:'',assigneeId:id('staff-housekeeping-'+i),frequency:'CUSTOM',startsOn:'2026-09-24',endsOn:'2026-09-24',customDates:['2026-09-24'],checklist}})).row;await commandCompanyWork(p,head,{id:id('clean-history-generate-'+i),kind:'SCHEDULE',recordId:history.id,version:history.version,action:'GENERATE',data:{through:'2026-09-24'}});const job=await tx.companyWorkRecord.findFirst({where:{parentId:history.id}});await commandCompanyWork(p,id('staff-housekeeping-'+i),{id:id('clean-complete-'+i),kind:'JOB',recordId:job.id,version:job.version,action:'COMPLETE',data:{checked:checklist,evidence:'',note:'DEMO historical checklist complete, awaiting independent acceptance'}});if(i===1)await commandCompanyWork(p,head,{id:id('clean-accept-'+i),kind:'JOB',recordId:job.id,version:job.version+1,action:'ACCEPT',data:{reason:'DEMO independently accepted'}})
 }
 const m=(await saveCompanyWork(p,id('staff-captain-3'),{id:id('maintenance'),kind:'MAINTENANCE',version:0,name:NAME+'Boat 3 planned inspection',payload:{vehicleId:id('boat-3'),resourceId:'',assigneeId:id('staff-captain-3'),dueOn:day(34),reason:'DEMO planned inspection; vessel unavailable in readiness on this date'}})).row;await commandCompanyWork(p,id('staff-captain-3'),{id:id('maintenance-submit'),kind:'MAINTENANCE',recordId:m.id,version:m.version,action:'SUBMIT',data:{}})
 return {futureJobs:jobs,historicalJobs:2,zones:2,awaitingAcceptance:1,accepted:1,maintenance:1}})
 summary.finance=await stage('finance',async(tx,p)=>{const records=[];const add=(key,kind,employeeId,payload)=>{const valid=validatePayload(kind,payload);records.push({id:id('finance-'+key),kind,title:NAME+key,employeeId,payload:valid,status:'DRAFT',createdBy:admin})}
 for(const a of staff){add('EMP-'+a.key,'EMPLOYMENT',a.id,{position:'DEMO '+a.role,startsOn:'2026-09-24',endsOn:'2027-05-15',notes:'DEMO employment record only; not an employment agreement'});add('PAY-OCT-'+a.key,'PAYROLL',a.id,{startsOn:'2026-10-01',endsOn:'2026-10-31',baseAmount:String(a.salary),basis:'DEMO monthly wage example, not real compensation or payroll policy',items:[{type:'EARNING',label:'DEMO seasonal allowance',reason:'Synthetic manually agreed example',amount:'500'}]})}
 for(let n=0;n<30;n++){const b=await tx.tourBooking.aggregate({where:{outboundDate:date(day(n)),status:'CONFIRMED',programSnapshot:{path:['demoDataset'],equals:TAG}},_sum:{adults:true,children:true}});const pax=(b._sum.adults||0)+(b._sum.children||0);for(const [key,amount,detail]of [['FUEL',Math.max(1,Math.ceil(pax/45))*1800,'Forecast boat/van fuel budget'],['WATER',pax*2*6,'Forecast water: 2 bottles per guest at DEMO 6 THB'],['FRUIT',Math.ceil(pax/10)*60+Math.ceil(pax/15)*30,'Forecast watermelon and pineapple budget']])add(key+'-'+day(n),'REIMBURSEMENT',id(key==='FUEL'?'staff-driver-1':'staff-assistant-guide-1'),{date:day(n),amount:String(Math.max(1,amount)),evidence:'DEMO ESTIMATE ONLY — NOT A RECEIPT',notes:detail+'; estimated '+pax+' guests. Future draft only; no money received or paid.'})}
 for(const [i,key]of ['staff-guide-1','staff-driver-1','staff-assistant-guide-1'].entries())add('ADVANCE-'+i,'WORK_ADVANCE',id(key),{date:'2026-09-25',dueOn:day(6),amount:String(1500+i*500),notes:'DEMO requested work advance. No payment or clearance yet.'})
 await tx.financePersonnelRecord.createMany({data:records});const test=await savePersonnelFinance(p,admin,{id:id('finance-past-expense'),kind:'REIMBURSEMENT',version:0,title:NAME+'Past fuel expense — approval example',employeeId:id('staff-driver-1'),payload:{date:'2026-09-24',amount:'1750',evidence:'DEMO REFERENCE ONLY — NOT A RECEIPT',notes:'Synthetic historical expense for approval flow, no actual payment'}});await commandPersonnelFinance(p,admin,{id:id('finance-submit-past'),recordId:test.row.id,version:test.row.version,action:'SUBMIT',note:'DEMO submit for independent review'})
 await tx.auditEvent.create({data:{actorId:admin,action:'demo45.finance.seeded',details:{dataset:TAG,payroll:26,employment:26,expenseDrafts:90,workAdvanceDrafts:3,realPayments:0}}});return {payrollDrafts:26,employmentDrafts:26,expenseDrafts:90,workAdvanceDrafts:3,submittedExample:1,month:'2026-10'}})
 saveReport('support-summary',summary);console.log(JSON.stringify({result:'SUPPORT_DATA_READY',...summary}))
}catch(e){safeError(e,current)}finally{await close()}
