// One-time automatic preparation of tomorrow's DEMO, using real dispatch commands.
import {assert,id,code,NAME,TAG,day,db,actor,stage,close,requireApply,safeError,saveReport} from './common.mjs'
import {saveRun,dispatchCommand} from '../../src/modules/operations/dispatch.js'
import {capacityInclude,poolContext,solveContext} from '../../src/modules/operations/capacity-core.js'
import {localStamp} from '../../../packages/contracts/operations.js'
let current='tomorrow'
try{requireApply();const admin=await actor();const report=await stage('tomorrow-dispatch',async(tx,p)=>{
 const bookings=await tx.tourBooking.findMany({where:{id:{in:Array.from({length:10},(_,j)=>id('B0-'+j))}},include:{lines:{include:{resource:true}}}});assert.equal(bookings.length,10);assert.ok(bookings.every(b=>b.status==='CONFIRMED'))
 const cap=await tx.capacityPool.findUnique({where:{id:id('BO-0')},include:capacityInclude}),plan=solveContext(await poolContext(tx,cap));assert.equal(plan.status,'FEASIBLE');assert.equal(plan.boatCount,2);assert.equal(plan.totalCapacity,75)
 const runs=[]
 async function createRun(key,kind,resourceId,vehicleId,capacity,direction,startsAt,endsAt,staff){current=key;const row=(await saveRun(p,admin,{id:id(key),version:0,code:code(key),name:NAME+key,kind,direction,period:direction==='OUTBOUND'?'AM':'PM',resourceId,vehicleId,capacity,startsAt,endsAt,staff})).row;runs.push(row);return row}
 async function assign(run,b){current='assign-'+b.code;const line=b.lines.find(l=>l.resourceId===run.slot.resourceId&&l.selected);assert.ok(line);const fresh=await tx.dispatchRun.findUnique({where:{id:run.id}});const input={id:id('assign-'+run.id+'-'+b.id),runId:run.id,version:fresh.version,action:'ASSIGN',bookingLineId:line.id,adults:b.adults,children:b.children};if(run.kind==='VEHICLE'&&run.direction==='OUTBOUND')input.pickupAt=localStamp(new Date(+new Date(run.slot.startsAt)+300000));await dispatchCommand(p,admin,input)}
 for(const group of plan.assignments){const boatNo=[1,2,3].find(i=>id('boat-'+i)===group.boatId);assert.ok(boatNo);const crew=[['captain-'+boatNo,'CAPTAIN'],['guide-'+boatNo,'GUIDE'],['assistant-guide-'+(boatNo*2-1),'ASSISTANT_TOUR_GUIDE'],['assistant-guide-'+(boatNo*2),'ASSISTANT_TOUR_GUIDE'],['assistant-captain-'+(boatNo*2-1),'ASSISTANT_CAPTAIN'],['assistant-captain-'+(boatNo*2),'ASSISTANT_CAPTAIN']].map(([key,role])=>({userId:id('staff-'+key),role}));const out=await createRun('TMR-B'+boatNo+'-O','BOAT',id('res-SEA'),group.boatId,group.capacity,'OUTBOUND',day(0)+' 09:00',day(0)+' 10:30',crew);const back=await createRun('TMR-B'+boatNo+'-R','BOAT',id('res-SEA'),group.boatId,group.capacity,'RETURN',day(0)+' 15:00',day(0)+' 16:30',crew);for(const bookingId of group.bookingIds){const b=bookings.find(b=>b.id===bookingId);assert.ok(b);await assign(out,b);if(b.returnDate?.toISOString().slice(0,10)===day(0))await assign(back,b)}}
 for(const [j,slot] of [[0,0],[1,1],[3,2]]){const window=await tx.capacityPool.findUnique({where:{id:id('VO-0-'+slot)},include:capacityInclude});const run=await createRun('TMR-V-O'+slot,'VEHICLE',id('res-VAN'),window.offers[0].vehicleId,12,'OUTBOUND',localStamp(window.startsAt),localStamp(window.endsAt),[{userId:id('staff-driver-1'),role:'DRIVER'}]);await assign(run,bookings.find(b=>b.id===id('B0-'+j)))}
 for(const [j,slot] of [[1,0],[3,1]]){const window=await tx.capacityPool.findUnique({where:{id:id('VR-0-'+slot)},include:capacityInclude});const run=await createRun('TMR-V-R'+slot,'VEHICLE',id('res-VAN'),window.offers[0].vehicleId,12,'RETURN',localStamp(window.startsAt),localStamp(window.endsAt),[{userId:id('staff-driver-1'),role:'DRIVER'}]);await assign(run,bookings.find(b=>b.id===id('B0-'+j)))}
 const assigned=await tx.dispatchAssignment.findMany({where:{runId:{in:runs.map(r=>r.id)}},include:{run:true,bookingLine:{include:{booking:true}}}})
 assert.equal(assigned.filter(a=>a.run.kind==='BOAT'&&a.run.direction==='OUTBOUND').reduce((n,a)=>n+a.adults+a.children,0),70)
 assert.equal(assigned.filter(a=>a.run.kind==='BOAT'&&a.run.direction==='RETURN').reduce((n,a)=>n+a.adults+a.children,0),50)
 const driverRuns=runs.filter(r=>r.kind==='VEHICLE').sort((a,b)=>+new Date(a.slot.startsAt)-+new Date(b.slot.startsAt));for(let i=1;i<driverRuns.length;i++)assert.ok(new Date(driverRuns[i-1].slot.endsAt)<=new Date(driverRuns[i].slot.startsAt),'Driver overlap')
 return {serviceDate:day(0),outboundPax:70,returnPax:50,boatCapacity:75,boatRuns:4,vehicleRuns:5,companyVansUsed:2,driversUsed:1,recurringAutomation:false,assignments:assigned.length,runs:runs.map(r=>({id:r.id,code:r.code,kind:r.kind,direction:r.direction,vehicle:r.slot.vehicle.name,startsAt:r.slot.startsAt,endsAt:r.slot.endsAt,staff:r.staff}))}
 },{timeout:900000});saveReport('tomorrow-assignments',report);console.log(JSON.stringify({result:'TOMORROW_ASSIGNED',date:day(0),boatRuns:report.boatRuns,vehicleRuns:report.vehicleRuns,assignments:report.assignments}))
}catch(e){safeError(e,current)}finally{await close()}
