// Read-only database assertions for this retained dataset; never exposes credentials.
import {assert,id,code,TAG,day,date,db,pool,OUT,staff,customers,readFileSync,saveReport,close,safeError} from './common.mjs'
import {bookingLegs,usableCapacity,capacityBookingInclude,capacityInclude} from '../../src/modules/operations/capacity-core.js'
import {planBoatGroups} from '../../src/modules/operations/boat-capacity-plan.js'
let report={dataset:TAG,checkedAt:new Date().toISOString(),checks:[]}
try{
 const profiles=await db.userProfile.findMany({where:{id:{in:staff.map(s=>s.id)}},include:{roles:true}});assert.equal(profiles.length,26);for(const s of staff){const p=profiles.find(p=>p.id===s.id);assert.equal(p.status,'ACTIVE');assert.deepEqual(p.roles.map(r=>r.roleCode),[s.role])}report.checks.push('26 exact staff profiles and unchanged least-privilege roles')
 const login=JSON.parse(readFileSync(OUT+'/login-verification.json','utf8'));assert.equal(login.allPassed,true);assert.equal(login.results.length,29);report.loginAccounts=29
 const agents=await db.businessPartner.count({where:{id:{in:Array.from({length:15},(_,i)=>id('agent-'+(i+1)))},roles:{has:'SALES_AGENT'}}});assert.equal(agents,15);report.agents=agents
 const vehicles=await db.fleetVehicle.findMany({where:{id:{in:[...Array.from({length:3},(_,i)=>id('boat-'+(i+1))),id('van-1'),id('van-2')]}}});assert.equal(vehicles.length,5);report.boats=vehicles.filter(v=>v.kind==='SPEEDBOAT').map(v=>v.capacity).sort((a,b)=>a-b);assert.deepEqual(report.boats,[30,45,65]);report.companyVans=2
 const bookings=await db.tourBooking.findMany({where:{programSnapshot:{path:['demoDataset'],equals:TAG}},include:capacityBookingInclude}),future=bookings.filter(b=>{const d=(b.outboundDate||b.returnDate)?.toISOString().slice(0,10);return d>=day(0)&&d<=day(44)})
 const dates=[...new Set(future.map(b=>(b.outboundDate||b.returnDate).toISOString().slice(0,10)))].sort();assert.deepEqual(dates,Array.from({length:45},(_,n)=>day(n)));report.bookingDays=dates.length;report.from=day(0);report.through=day(44);report.futureBookings=future.length;report.historicalBookings=bookings.length-future.length;report.bookingStatuses=bookings.reduce((a,b)=>(a[b.status]=(a[b.status]||0)+1,a),{});report.programMix=bookings.reduce((a,b)=>{const k=b.programSnapshot.journeyMode==='FIXED'?b.programSnapshot.durationDays>1?'OVERNIGHT':'DAY_TRIP':'BOAT_TICKET';a[k]=(a[k]||0)+1;return a},{})
 const windows=await db.capacityPool.findMany({where:{code:{startsWith:'D45-'},kind:'BOAT'},include:capacityInclude}),holds=await db.capacityHold.findMany({where:{poolId:{in:windows.map(w=>w.id)},expiresAt:{gt:new Date()},request:{bookingId:null,status:{in:['REQUESTED','DATE_PROPOSED']}}}});let proven=0
 for(const w of windows){const groups=[];for(const b of bookings.filter(b=>['CONFIRMED','COMPLETED'].includes(b.status))){const legs=bookingLegs(b).filter(l=>l.direction===w.direction&&l.serviceDate===w.serviceDate.toISOString().slice(0,10)&&w.resourceIds.includes(l.resourceId));if(!legs.length)continue;const selected=b.programSnapshot.capacitySelections||[];if(legs.every(l=>selected.some(s=>s.resourceId===l.resourceId&&s.direction===l.direction&&s.serviceDate===l.serviceDate&&s.poolId!==w.id)))continue;const assigned=b.lines.flatMap(l=>l.dispatchAssignments||[]).filter(a=>a.status!=='CANCELLED'&&a.run.kind==='BOAT'&&a.run.direction===w.direction);const ids=[...new Set(assigned.map(a=>a.run.slot.vehicleId))];assert.ok(ids.length<=1,'Split Booking');groups.push({id:b.id,pax:b.adults+b.children,fixedBoatId:ids[0]||null,exclusive:legs.some(l=>l.exclusive)})}for(const h of holds.filter(h=>h.poolId===w.id))groups.push({id:'hold:'+h.requestId,pax:h.passengers,exclusive:h.exclusive});const boats=w.offers.map(o=>({id:o.vehicleId,capacity:usableCapacity(o)})).filter(v=>v.capacity>0),plan=planBoatGroups({bookings:groups,boats});assert.equal(plan.status,'FEASIBLE',w.code+' whole-group proof');proven++}report.capacityWindowsProven=proven;report.checks.push('Every confirmed group and active customer hold fits compatible boats; no split')
 const runs=await db.dispatchRun.findMany({where:{code:{startsWith:'D45-'}},include:{slot:{include:{vehicle:true}},staff:true,assignments:{include:{bookingLine:{include:{booking:true}}}}}});for(const r of runs){assert.ok(r.assignments.reduce((n,a)=>n+a.adults+a.children,0)<=r.capacity);if(r.kind==='BOAT'){assert.equal(r.staff.length,6);for(const a of r.assignments)assert.equal(a.adults+a.children,a.bookingLine.booking.adults+a.bookingLine.booking.children)}for(const other of runs.filter(o=>o.id!==r.id&&o.slot.startsAt<r.slot.endsAt&&o.slot.endsAt>r.slot.startsAt)){assert.notEqual(other.slot.vehicleId,r.slot.vehicleId,'Vehicle overlap');assert.ok(!other.staff.some(s=>r.staff.some(t=>t.userId===s.userId)),'Staff overlap')}}report.checks.push('Every demo run obeys passenger, crew, vehicle and staff-time limits')
 const tomorrow=runs.filter(r=>r.code.includes('-TMR-'));assert.equal(tomorrow.length,9);report.tomorrow={date:day(0),boatRuns:tomorrow.filter(r=>r.kind==='BOAT').length,vehicleRuns:tomorrow.filter(r=>r.kind==='VEHICLE').length,counts:{}};for(const kind of ['BOAT','VEHICLE'])for(const direction of ['OUTBOUND','RETURN'])report.tomorrow.counts[kind+'_'+direction]=tomorrow.filter(r=>r.kind===kind&&r.direction===direction).flatMap(r=>r.assignments).reduce((n,a)=>n+a.adults+a.children,0);assert.equal(report.tomorrow.counts.BOAT_OUTBOUND,70);assert.equal(report.tomorrow.counts.BOAT_RETURN,50);assert.equal(report.tomorrow.counts.VEHICLE_OUTBOUND,23);assert.equal(report.tomorrow.counts.VEHICLE_RETURN,13)
 const memberRows=await db.customerRequest.findMany({where:{customerId:{in:customers.map(c=>c.customerId)}},include:{booking:true}});assert.equal(memberRows.length,6);report.memberRequests=memberRows.map(r=>({id:r.id,status:r.status,linkedBooking:Boolean(r.bookingId)}));assert.equal(memberRows.filter(r=>r.bookingId).length,1);assert.equal(new Set(memberRows.filter(r=>r.bookingId).map(r=>r.bookingId)).size,1)
 const finance=await db.financePersonnelRecord.findMany({where:{title:{startsWith:'DEMO 45D'}}});report.finance=finance.reduce((a,r)=>(a[r.kind]=(a[r.kind]||0)+1,a),{});assert.equal(report.finance.PAYROLL,26);assert.equal(report.finance.REIMBURSEMENT,91);assert.ok(finance.every(r=>r.payment===null&&['DRAFT','SUBMITTED'].includes(r.status)));report.checks.push('Payroll and expenses are synthetic drafts/submissions; no payment records')
 const jobs=await db.companyWorkRecord.findMany({where:{name:{startsWith:'DEMO 45D'},kind:'JOB'}});assert.equal(jobs.length,62);report.cleaningJobs=jobs.length;report.cleaningStates=jobs.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{})
 const before=JSON.parse(readFileSync('/tmp/greenview-demo45-260925/before.json','utf8'));const current=(await pool.query(`SELECT 'TourBooking' AS kind,id::text,md5(row_to_json(b)::text) hash FROM app_private."TourBooking" b UNION ALL SELECT 'UserProfile',id::text,md5(row_to_json(u)::text) FROM app_private."UserProfile" u UNION ALL SELECT 'FleetVehicle',id::text,md5(row_to_json(v)::text) FROM app_private."FleetVehicle" v UNION ALL SELECT 'BusinessPartner',id::text,md5(row_to_json(a)::text) FROM app_private."BusinessPartner" a`)).rows;const lookup=new Map(current.map(r=>[r.kind+':'+r.id,r.hash]));for(const old of before)assert.equal(lookup.get(old.kind+':'+old.id),old.hash,'Preexisting '+old.kind+' changed');report.existingRowsPreserved=before.length;report.checks.push('Preexisting bookings, profiles, fleet and agents unchanged')
 const auth=(await pool.query(`SELECT count(*)::int n FROM auth.users u WHERE raw_user_meta_data->>'demo_dataset'=$1 AND email_confirmed_at IS NOT NULL AND EXISTS (SELECT 1 FROM auth.identities i WHERE i.user_id=u.id AND i.provider='email')`,[TAG])).rows[0];assert.equal(auth.n,29)
 report.result='PASS';saveReport('verification',report);console.log(JSON.stringify(report))
}catch(e){report.result='FAIL';report.error=e.code||e.name;saveReport('verification',report);safeError(e,'verification')}finally{await close()}
