import {publicWebsiteOrigin} from '../../../core/navigation/publicWebsite.js'
import {emptyTourContent, validateTourContent} from '../../../../../../packages/contracts/tour-content.js'
import {catalog, initialValues, labelFor, validateCatalog, visibleField} from '../../../../../../packages/contracts/catalog.js'
import {translateLabel as bilingualLabel, formatDate, formatNumber} from '../../../core/i18n/runtime.js'
import {useLocale} from '../../../core/i18n/locale.jsx'
import {useNavigation, useUnsavedChanges} from '../../../core/navigation/Navigation.jsx'
import {api} from '../../../core/auth/api.js'
import {Button} from '../../../core/ui/Button.jsx'
import {FormField} from '../../../core/ui/FormField.jsx'
import {TextAreaField} from '../../../core/ui/TextAreaField.jsx'
import {SelectField} from '../../../core/ui/SelectField.jsx'
import {ReferenceField} from '../../../core/ui/ReferenceField.jsx'
import {Tabs} from '../../../core/ui/Tabs.jsx'
import WebsiteImageUpload from '../shared/WebsiteImageUpload.jsx'
import {FormEmpty,FormGrid,FormSection} from '../../../core/ui/FormSection.jsx'
import {MasterDetail} from '../../../core/ui/MasterDetail.jsx'
import {useCallback, useEffect, useRef, useState} from 'react'

const tabs=[
 ['overview','Overview'],['content','Public content'],['package','Package & availability'],['itinerary','Itinerary'],
 ['terms','Terms & conditions'],['media','Media'],['faq','FAQ'],['seo','SEO & publish'],
]
const uuid=()=>crypto.randomUUID()
const listRow=(type,index)=> type==='highlight'?{id:uuid(),status:'ACTIVE',sortOrder:index,titleTh:'',titleEn:'',descriptionTh:'',descriptionEn:''}
 :type==='itinerary'?{id:uuid(),status:'ACTIVE',sortOrder:index,day:1,timeLabel:'',titleTh:'',titleEn:'',descriptionTh:'',descriptionEn:'',locationTh:'',locationEn:''}
 :type==='faq'?{id:uuid(),status:'ACTIVE',sortOrder:index,questionTh:'',answerTh:'',questionEn:'',answerEn:''}
 :{id:uuid(),status:'ACTIVE',sortOrder:index,kind:index===0?'HERO':'GALLERY',url:'',altTh:'',altEn:'',captionTh:'',captionEn:''}
function snapshot(values,content,highlights,itinerary,faqs,media){return JSON.stringify({values,content,highlights,itinerary,faqs,media})}
const Section=FormSection
const Empty=FormEmpty
function Two({children}){return <FormGrid>{children}</FormGrid>}
function LocaleTabs({value,onChange}){return <Tabs items={[{id:'th',label:'Thai content'},{id:'en',label:'English content'}]} value={value} onChange={onChange} label="Content language" idPrefix="tour-content-locale"/>}
function StatusField({value,onChange,label='Status'}){return <SelectField label={label} value={value} onChange={onChange}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></SelectField>}

export default function TourProgramEditor({tourId}){
 const {t}=useLocale(),{navigate}=useNavigation(),isNew=tourId==='new',recordId=useRef(isNew?uuid():tourId)
 const [tab,setTab]=useState('overview'),[locale,setLocale]=useState('th'),[state,setState]=useState({loading:!isNew})
 const [values,setValues]=useState(()=>initialValues('tours')),[version,setVersion]=useState(0)
 const [content,setContent]=useState({th:emptyTourContent(),en:emptyTourContent()}),[highlights,setHighlights]=useState([]),[itinerary,setItinerary]=useState([]),[faqs,setFaqs]=useState([]),[media,setMedia]=useState([])
 const [selectedHighlightId,setSelectedHighlightId]=useState(null),[selectedItineraryId,setSelectedItineraryId]=useState(null),[selectedMediaId,setSelectedMediaId]=useState(null),[selectedFaqId,setSelectedFaqId]=useState(null)
 const [errors,setErrors]=useState({}),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),baseline=useRef(''),highlightDetail=useRef(null),itineraryDetail=useRef(null),mediaDetail=useRef(null),faqDetail=useRef(null),pendingFocus=useRef(null)
 const hydrate=useCallback(data=>{
   const nextValues=initialValues('tours',data.tour),nextContent={th:{...emptyTourContent(),...data.content?.th},en:{...emptyTourContent(),...data.content?.en}}
   const nextHighlights=(data.highlights||[]).map(row=>({...row})),nextItinerary=(data.itinerary||[]).map(row=>({...row})),nextFaqs=(data.faqs||[]).map(row=>({...row})),nextMedia=(data.media||[]).map(row=>({...row}))
   setValues(nextValues);setVersion(data.tour.version);setContent(nextContent);setHighlights(nextHighlights);setItinerary(nextItinerary);setFaqs(nextFaqs);setMedia(nextMedia)
   setSelectedHighlightId(current=>nextHighlights.some(row=>row.id===current)?current:(nextHighlights[0]?.id||null));setSelectedItineraryId(current=>nextItinerary.some(row=>row.id===current)?current:(nextItinerary[0]?.id||null));setSelectedMediaId(current=>nextMedia.some(row=>row.id===current)?current:(nextMedia[0]?.id||null));setSelectedFaqId(current=>nextFaqs.some(row=>row.id===current)?current:(nextFaqs[0]?.id||null))
   setState({loading:false,reference:data});setErrors({});setNotice('');baseline.current=snapshot(nextValues,nextContent,nextHighlights,nextItinerary,nextFaqs,nextMedia)
 },[])
 useEffect(()=>{
   if(isNew){baseline.current=snapshot(values,content,highlights,itinerary,faqs,media);setState({loading:false,reference:{seasons:[],promotions:[],components:[]}});return}
   const controller=new AbortController();setState({loading:true})
   api(`/api/settings/tours/${tourId}/editor`,undefined,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(15000)])}).then(hydrate).catch(error=>{if(!controller.signal.aborted)setState({loading:false,error:error.message})})
   return()=>controller.abort()
 // new editor baseline is intentionally created only once
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[tourId,isNew,hydrate])
 const dirty=baseline.current!==''&&baseline.current!==snapshot(values,content,highlights,itinerary,faqs,media)
 useUnsavedChanges(dirty||saving)
 const update=(key,value)=>{setValues(old=>({...old,[key]:value}));setErrors(old=>({...old,[key]:undefined}));setNotice('')}
 const updateContent=(key,value)=>{setContent(old=>({...old,[locale]:{...old[locale],[key]:value}}));setErrors(old=>({...old,[`content.${locale}.${key}`]:undefined}));setNotice('')}
 const loadOperators=useCallback(({q,page,signal})=>api(`/api/settings/partners?${new URLSearchParams({q,page:String(page),view:'options',status:'ACTIVE',role:'TOUR_OPERATOR'})}`,undefined,{signal}),[])
 const operatorLabel=state.reference?.tour?.operator?.name
 const listUpdate=(setter,index,key,value)=>setter(old=>old.map((row,i)=>i===index?{...row,[key]:value}:row))
 const selectCollection=(kind,id,setter,collection=kind)=>{setter(id);if(window.matchMedia?.('(max-width:900px)').matches)pendingFocus.current={kind,collection,id,focus:false}}
 const addHighlight=()=>{const row=listRow('highlight',highlights.length);setHighlights(old=>[...old,row]);setSelectedHighlightId(row.id);pendingFocus.current={kind:'content',collection:'highlight',id:row.id,focus:true};setTab('content')}
 const addItinerary=()=>{const row=listRow('itinerary',itinerary.length);setItinerary(old=>[...old,row]);setSelectedItineraryId(row.id);pendingFocus.current={kind:'itinerary',collection:'itinerary',id:row.id,focus:true};setTab('itinerary')}
 const addMedia=(url='')=>{const row={...listRow('media',media.length),url};setMedia(old=>[...old,row]);setSelectedMediaId(row.id);pendingFocus.current={kind:'media',collection:'media',id:row.id,focus:true};setTab('media')}
 const addFaq=()=>{const row=listRow('faq',faqs.length);setFaqs(old=>[...old,row]);setSelectedFaqId(row.id);pendingFocus.current={kind:'faq',collection:'faq',id:row.id,focus:true};setTab('faq')}
 const removeHighlight=index=>{const next=highlights.filter((_,i)=>i!==index).map((row,i)=>({...row,sortOrder:i}));setHighlights(next);setSelectedHighlightId(next[Math.min(index,next.length-1)]?.id||null)}
 const removeItinerary=index=>{const next=itinerary.filter((_,i)=>i!==index).map((row,i)=>({...row,sortOrder:i}));setItinerary(next);setSelectedItineraryId(next[Math.min(index,next.length-1)]?.id||null)}
 const removeMedia=index=>{const next=media.filter((_,i)=>i!==index).map((row,i)=>({...row,sortOrder:i}));setMedia(next);setSelectedMediaId(next[Math.min(index,next.length-1)]?.id||null)}
 const removeFaq=index=>{const next=faqs.filter((_,i)=>i!==index).map((row,i)=>({...row,sortOrder:i}));setFaqs(next);setSelectedFaqId(next[Math.min(index,next.length-1)]?.id||null)}
 useEffect(()=>{
  const pending=pendingFocus.current;if(!pending||tab!==pending.kind)return
  const selected={highlight:selectedHighlightId,itinerary:selectedItineraryId,media:selectedMediaId,faq:selectedFaqId}[pending.collection];if(selected!==pending.id)return
  const target={highlight:highlightDetail.current,itinerary:itineraryDetail.current,media:mediaDetail.current,faq:faqDetail.current}[pending.collection]
  target?.scrollIntoView({block:'nearest'})
  if(pending.focus!==false)target?.querySelector('.field-control input, textarea, .core-select-trigger')?.focus({preventScroll:true})
  pendingFocus.current=null
 },[tab,selectedHighlightId,selectedItineraryId,selectedMediaId,selectedFaqId,highlights.length,itinerary.length,media.length,faqs.length])
 async function save(){
   if(saving)return
   const base=validateCatalog('tours',{...values,id:recordId.current,version}),publicData=validateTourContent({content,highlights,itinerary,faqs,media})
   const nextErrors={...base.errors,...publicData.errors};setErrors(nextErrors)
   if(Object.keys(nextErrors).length){const first=Object.keys(publicData.errors)[0]||'';const target=Object.keys(base.errors).length?'overview':first.startsWith('media')?'media':first.startsWith('faqs')?'faq':first.startsWith('itinerary')?'itinerary':'content';setNotice('Review the highlighted fields before saving.');setTab(target);return}
   setSaving(true);setNotice('')
   try{
     const data=await api(`/api/settings/tours/${recordId.current}/editor`,{program:{...values,id:recordId.current,version},content,highlights,itinerary,faqs,media})
     hydrate(data);setNotice('Tour program saved.')
     if(isNew)navigate(`/settings/tours/${recordId.current}`,{replace:true})
   }catch(error){setNotice(error.message==='SETTINGS_CONFLICT'?'This program changed elsewhere. Reload before saving again.':error.message)}finally{setSaving(false)}
 }
 if(state.loading)return <section className="panel core-state-panel"><p role="status">{t('Loading current record…')}</p></section>
 if(state.error)return <section className="panel core-state-panel" role="alert"><h1>{bilingualLabel('Unable to load this record')}</h1><p>{t(state.error)}</p><Button onClick={()=>navigate('/settings/tours')}>Back to tour programs</Button></section>
 const reference=state.reference||{seasons:[],promotions:[],components:[]},current=content[locale]
 const mediaPreview=media.filter(row=>row.status==='ACTIVE'&&row.url),activeHighlights=highlights.filter(row=>row.status==='ACTIVE')
 const readiness=[['Thai summary',Boolean(content.th.summary)],['English summary',Boolean(content.en.summary)],['Hero image',media.some(row=>row.status==='ACTIVE'&&row.kind==='HERO'&&row.url)],['Itinerary',itinerary.some(row=>row.status==='ACTIVE')],['FAQ',faqs.some(row=>row.status==='ACTIVE')],['SEO title TH',Boolean(content.th.seoTitle)],['SEO title EN',Boolean(content.en.seoTitle)]]
 return <div className="core-editor-workspace">
   <div className="page-heading"><div><span className="eyebrow">{bilingualLabel('TOUR PROGRAM')}</span><h1 tabIndex={-1}>{values.name||t(isNew?'New tour program':'Tour program')}</h1><p>{t('One source for operations, booking, public content and SEO. Public publishing never exposes supplier or Agent pricing.')}</p></div><div className="page-actions"><Button onClick={()=>navigate('/settings/tours')}>← Tour programs</Button>{values.slug&&<a className="button" target="_blank" rel="noreferrer" href={`${publicWebsiteOrigin()}/tours?tour=${encodeURIComponent(values.slug)}`}>{t('Preview website')} ↗</a>}<Button className="button-primary" busy={saving} disabled={saving} onClick={save}>Save program</Button></div></div>
   {notice&&<p className={Object.keys(errors).length?'core-notice is-error':'core-notice'} role="status">{t(notice)}</p>}
   <Tabs items={tabs.map(([id,label])=>({id,label}))} value={tab} onChange={setTab} label="Tour program sections" idPrefix="tour-editor"/>

   {tab==='overview'&&<div className="core-stack">
    <Section title="Program identity" description="Internal identity and operating shape. These fields drive Bookings and Job Orders."><Two>
      <FormField label="Code" value={values.code} onChange={e=>update('code',e.target.value)} error={errors.code} maxLength={40}/><FormField label="Name" value={values.name} onChange={e=>update('name',e.target.value)} error={errors.name} maxLength={200}/>
      <FormField label="Job Order program code" value={values.printCode} onChange={e=>update('printCode',e.target.value)} error={errors.printCode} maxLength={10}/><StatusField value={values.status} onChange={e=>update('status',e.target.value)}/>
      <SelectField label="Organized by" value={values.ownership} onChange={e=>update('ownership',e.target.value)} error={errors.ownership}><option value="GREENVIEW">Greenview Tour</option><option value="PARTNER">Business partner</option></SelectField>
      <SelectField label="Journey type" value={values.journeyMode} onChange={e=>update('journeyMode',e.target.value)} error={errors.journeyMode}>{['FIXED','OPEN_RETURN','OUTBOUND_ONLY','RETURN_ONLY'].map(v=><option key={v} value={v}>{t(labelFor(v))}</option>)}</SelectField>
      <SelectField label="Tour type" value={values.tourType} onChange={e=>update('tourType',e.target.value)} error={errors.tourType}><option value="">Not set</option>{['DAY_TRIP','OVERNIGHT','PRIVATE','JOIN','TRANSFER'].map(v=><option key={v} value={v}>{t(labelFor(v))}</option>)}</SelectField>
      {visibleField(catalog.tours.fields.find(f=>f.key==='durationDays'),values)&&<FormField label="Duration in days" type="number" min="1" max="366" value={values.durationDays} onChange={e=>update('durationDays',e.target.value)} error={errors.durationDays}/>}<SelectField label="Booking confirmation" value={values.confirmationMode} onChange={e=>update('confirmationMode',e.target.value)} error={errors.confirmationMode}><option value="REQUEST">Request confirmation</option><option value="INSTANT">Instant confirmation</option></SelectField>
    </Two>{values.ownership==='PARTNER'&&<ReferenceField label="Tour operator" value={values.operatorId} selectedLabel={operatorLabel} onChange={e=>update('operatorId',e.target.value)} error={errors.operatorId} load={loadOperators}/>}</Section>
    <Section title="Booking commission" description="Internal staff commission only. This information never belongs to the Public API."><Two>
      <SelectField label="Booking staff commission" value={values.bookingCommissionEligible} onChange={e=>update('bookingCommissionEligible',e.target.value)}><option value="false">No commission</option><option value="true">Commission enabled</option></SelectField>
      {values.bookingCommissionEligible==='true'&&<><FormField label="Booking staff commission per adult (THB)" value={values.bookingAdultCommission} onChange={e=>update('bookingAdultCommission',e.target.value)} error={errors.bookingAdultCommission}/><FormField label="Booking staff commission per child (THB)" value={values.bookingChildCommission} onChange={e=>update('bookingChildCommission',e.target.value)} error={errors.bookingChildCommission}/></>}
    </Two></Section>
   </div>}

   {tab==='content'&&<div className="core-stack"><LocaleTabs value={locale} onChange={setLocale}/>
    <Section title="Public introduction" description="Customer-facing copy for this language. Keep facts consistent with the structured package below."><Two>
      <FormField label="Public tour name" value={current.name} onChange={e=>updateContent('name',e.target.value)} error={errors[`content.${locale}.name`]} maxLength={200}/><FormField label="Content reviewed" type="date" value={current.contentReviewedAt} onChange={e=>updateContent('contentReviewedAt',e.target.value)} error={errors[`content.${locale}.contentReviewedAt`]}/>
    </Two><TextAreaField label="Short summary" value={current.summary} onChange={e=>updateContent('summary',e.target.value)} error={errors[`content.${locale}.summary`]} maxLength={1000}/><TextAreaField label="Introduction" value={current.introduction} onChange={e=>updateContent('introduction',e.target.value)} error={errors[`content.${locale}.introduction`]} maxLength={5000}/><TextAreaField label="Long description" value={current.longDescription} onChange={e=>updateContent('longDescription',e.target.value)} error={errors[`content.${locale}.longDescription`]} maxLength={20000}/></Section>
    <Section title="Highlights" description="Select a highlight on the left, then edit Thai and English content on the right." actions={<Button onClick={addHighlight}>+ Add highlight</Button>}>
      <MasterDetail items={highlights} selectedId={selectedHighlightId} onSelect={id=>selectCollection('content',id,setSelectedHighlightId,'highlight')} label="Tour highlights" empty="No highlights yet." detailRef={highlightDetail} renderItem={(row,index)=><span className="core-master-copy"><strong>{row.titleTh||row.titleEn||`Highlight #${index+1}`}</strong><small>{row.titleTh&&row.titleEn?row.titleEn:'Title not complete yet'}</small><em>{t(labelFor(row.status))}</em></span>}>
       {(row,index)=><div><div className="core-master-pane-header"><div><strong>Highlight #{index+1}</strong><span className="cell-sub">{row.titleTh||row.titleEn||'New highlight'}</span></div><Button onClick={()=>removeHighlight(index)}>Remove</Button></div><StatusField value={row.status} onChange={e=>listUpdate(setHighlights,index,'status',e.target.value)}/><Two><FormField label="Thai title" value={row.titleTh||''} onChange={e=>listUpdate(setHighlights,index,'titleTh',e.target.value)} error={errors[`highlights.${index}.titleTh`]}/><FormField label="English title" value={row.titleEn||''} onChange={e=>listUpdate(setHighlights,index,'titleEn',e.target.value)} error={errors[`highlights.${index}.titleEn`]}/></Two><Two><TextAreaField label="Thai detail" value={row.descriptionTh||''} onChange={e=>listUpdate(setHighlights,index,'descriptionTh',e.target.value)}/><TextAreaField label="English detail" value={row.descriptionEn||''} onChange={e=>listUpdate(setHighlights,index,'descriptionEn',e.target.value)}/></Two></div>}
      </MasterDetail>
    </Section>
   </div>}

   {tab==='package'&&<div className="core-stack">
    <Section title="Direct pricing" description="Public direct prices. Agent selling prices remain in Agent prices and are never returned by the Public API."><Two><FormField label="Direct adult price (THB)" value={values.adultPrice} onChange={e=>update('adultPrice',e.target.value)} error={errors.adultPrice}/><FormField label="Direct child price (THB)" value={values.childPrice} onChange={e=>update('childPrice',e.target.value)} error={errors.childPrice}/>{values.ownership==='PARTNER'&&<><SelectField label="Supplier pricing basis" value={values.supplierPricing} onChange={e=>update('supplierPricing',e.target.value)}><option value="NOT_SET">Not set</option><option value="NET">Net cost</option><option value="COMMISSION">Commission per passenger</option></SelectField>{values.supplierPricing==='NET'?<><FormField label="Supplier adult net (THB)" value={values.supplierAdultNet} onChange={e=>update('supplierAdultNet',e.target.value)}/><FormField label="Supplier child net (THB)" value={values.supplierChildNet} onChange={e=>update('supplierChildNet',e.target.value)}/></>:values.supplierPricing==='COMMISSION'?<><FormField label="Adult commission received (THB)" value={values.supplierAdultCommission} onChange={e=>update('supplierAdultCommission',e.target.value)}/><FormField label="Child commission received (THB)" value={values.supplierChildCommission} onChange={e=>update('supplierChildCommission',e.target.value)}/></>:null}</>}</Two></Section>
    <Section title="Package services" description="Source of truth: Program components. REQUIRED is included and mandatory; INCLUDED is in the package; OPTIONAL is a separately priced add-on; EXCLUDED is not selectable. Customer-facing prices below come from the linked Service selling price.">{!reference.components?.length?<Empty>No program components linked yet. Add services from Program components.</Empty>:<div className="core-meta-list">{reference.components.map(row=><div key={row.id}><strong>{row.resource?.name||'Service'}</strong><span>{t(labelFor(row.selection))} · {t(labelFor(row.resource?.category))} · {formatNumber(row.quantity)} {t(labelFor(row.basis))}{row.day?` · Day ${row.day}`:''}{['OPTIONAL','EXCLUDED'].includes(row.selection)&&row.resource?.salePrice!=null?` · THB ${formatNumber(row.resource.salePrice)}`:''}</span></div>)}</div>}<a className="button" href="/settings/components">Open Program components →</a></Section>
    <Section title="Availability" description="Source of truth: Tour seasons. Service dates, online travel dates, booking windows, closed dates and cutoff stay structured.">{!reference.seasons?.length?<Empty>No seasons configured yet.</Empty>:<div className="core-meta-list">{reference.seasons.map(row=><div key={row.id}><strong>{row.name}</strong><span>{formatDate(row.startsOn)} – {formatDate(row.endsOn)} · {t(labelFor(row.status))} · cutoff {row.cutoffDays} day(s)</span></div>)}</div>}<a className="button" href="/settings/seasons">Open Tour seasons →</a></Section>
    <Section title="Promotions" description="Promotion booking period and travel period remain independent structured records.">{!reference.promotions?.length?<Empty>No promotions configured.</Empty>:<div className="core-meta-list">{reference.promotions.map(row=><div key={row.id}><strong>{row.name}</strong><span>{formatDate(row.serviceStartsOn)} – {formatDate(row.serviceEndsOn)} · {t(labelFor(row.status))}</span></div>)}</div>}<a className="button" href="/settings/promotions">Open Promotions →</a></Section>
   </div>}

   {tab==='itinerary'&&<Section title="Structured itinerary" description="Select a step on the left, then edit time, location and bilingual content on the right." actions={<Button onClick={addItinerary}>+ Add step</Button>}>
    <MasterDetail items={itinerary} selectedId={selectedItineraryId} onSelect={id=>selectCollection('itinerary',id,setSelectedItineraryId)} label="Tour itinerary" empty="No itinerary steps yet." detailRef={itineraryDetail} renderItem={(row,index)=><span className="core-master-copy"><strong>{row.timeLabel?`${row.timeLabel} · `:''}{row.titleTh||row.titleEn||`Step ${index+1}`}</strong><small>{[row.locationTh||row.locationEn,`Day ${row.day||1}`].filter(Boolean).join(' · ')}</small><em>{t(labelFor(row.status))}</em></span>}>
     {(row,index)=><div><div className="core-master-pane-header"><div><strong>Step {index+1}</strong><span className="cell-sub">{row.timeLabel||'No time'} · {row.titleTh||row.titleEn||'New itinerary step'}</span></div><Button onClick={()=>removeItinerary(index)}>Remove</Button></div><FormGrid columns={3}><FormField label="Day" type="number" min="1" max="366" value={row.day} onChange={e=>listUpdate(setItinerary,index,'day',e.target.value)} error={errors[`itinerary.${index}.day`]}/><FormField label="Time label" value={row.timeLabel||''} onChange={e=>listUpdate(setItinerary,index,'timeLabel',e.target.value)}/><StatusField value={row.status} onChange={e=>listUpdate(setItinerary,index,'status',e.target.value)}/></FormGrid><Two><FormField label="Thai title" value={row.titleTh||''} onChange={e=>listUpdate(setItinerary,index,'titleTh',e.target.value)} error={errors[`itinerary.${index}.titleTh`]}/><FormField label="English title" value={row.titleEn||''} onChange={e=>listUpdate(setItinerary,index,'titleEn',e.target.value)}/><FormField label="Thai location" value={row.locationTh||''} onChange={e=>listUpdate(setItinerary,index,'locationTh',e.target.value)}/><FormField label="English location" value={row.locationEn||''} onChange={e=>listUpdate(setItinerary,index,'locationEn',e.target.value)}/></Two><Two><TextAreaField label="Thai detail" value={row.descriptionTh||''} onChange={e=>listUpdate(setItinerary,index,'descriptionTh',e.target.value)}/><TextAreaField label="English detail" value={row.descriptionEn||''} onChange={e=>listUpdate(setItinerary,index,'descriptionEn',e.target.value)}/></Two></div>}
    </MasterDetail>
   </Section>}

   {tab==='terms'&&<div className="core-stack"><LocaleTabs value={locale} onChange={setLocale}/>
    <Section title="Schedule & booking" description="Customer-facing meeting, departure and booking rules for this language."><Two><TextAreaField label="Departure times" value={current.departureTimes} onChange={e=>updateContent('departureTimes',e.target.value)}/><TextAreaField label="Meeting point" value={current.meetingPoint} onChange={e=>updateContent('meetingPoint',e.target.value)}/><TextAreaField label="Booking cutoff" value={current.bookingCutoff} onChange={e=>updateContent('bookingCutoff',e.target.value)}/><TextAreaField label="Cancellation terms" value={current.cancellationTerms} onChange={e=>updateContent('cancellationTerms',e.target.value)}/></Two></Section>
    <Section title="Guest suitability & preparation" description="Participation guidance customers should know before travel."><Two><TextAreaField label="Child age / height policy" value={current.childPolicy} onChange={e=>updateContent('childPolicy',e.target.value)}/><TextAreaField label="Suitable for" value={current.suitableFor} onChange={e=>updateContent('suitableFor',e.target.value)}/><TextAreaField label="What to bring and participation restrictions" value={current.preparationNotes} onChange={e=>updateContent('preparationNotes',e.target.value)}/><TextAreaField label="Weather notes" value={current.weatherNotes} onChange={e=>updateContent('weatherNotes',e.target.value)}/><TextAreaField label="Special conditions" value={current.specialConditions} onChange={e=>updateContent('specialConditions',e.target.value)}/></Two></Section>
    <Section title="Meals, fees & package notes" description="Program Components remain the package source of truth; these fields add customer-facing context only."><Two><TextAreaField label="Meals and dietary options" value={current.meals} onChange={e=>updateContent('meals',e.target.value)}/><TextAreaField label="Fees" value={current.fees} onChange={e=>updateContent('fees',e.target.value)}/><TextAreaField label="Additional included notes" value={current.inclusions} onChange={e=>updateContent('inclusions',e.target.value)}/><TextAreaField label="Additional not-included notes" value={current.exclusions} onChange={e=>updateContent('exclusions',e.target.value)}/></Two></Section>
    {values.ownership==='PARTNER'&&<Section title="Partner verification" description="Internal evidence of where partner terms came from and when they were checked. These fields are not public."><FormField label="Partner source / reference URL" type="url" value={values.partnerSourceUrl} onChange={e=>update('partnerSourceUrl',e.target.value)} error={errors.partnerSourceUrl}/><Two><FormField label="Partner terms verified" type="date" value={values.partnerTermsVerifiedAt} onChange={e=>update('partnerTermsVerifiedAt',e.target.value)}/><FormField label="Partner content verified" type="date" value={values.partnerContentVerifiedAt} onChange={e=>update('partnerContentVerifiedAt',e.target.value)}/></Two></Section>}
   </div>}

   {tab==='media'&&<Section title="Tour media" description="Select an image on the left, then edit its customer-facing details on the right." actions={<Button onClick={()=>addMedia()}>+ Add media</Button>}>
    <WebsiteImageUpload disabled={saving} onUploaded={addMedia}/>
    <MasterDetail items={media} selectedId={selectedMediaId} onSelect={id=>selectCollection('media',id,setSelectedMediaId)} label="Tour media" empty="No media yet." detailRef={mediaDetail} renderItem={(row,index)=><><span className="core-master-thumb">{row.url?<img src={row.url.replace('/api/public/images/','/api/website-images/')} alt=""/>:<span>{index+1}</span>}</span><span className="core-master-copy"><strong>{row.kind==='HERO'?'Hero':'Gallery'} #{index+1}</strong><small>{row.captionTh||row.captionEn||row.altTh||row.altEn||'No caption yet'}</small><em>{t(labelFor(row.status))}</em></span></>}>
     {(row,index)=><div><div className="core-master-pane-header"><div><strong>{row.kind==='HERO'?'Hero image':'Gallery image'} #{index+1}</strong><span className="cell-sub">{t(labelFor(row.status))}</span></div><Button onClick={()=>removeMedia(index)}>Remove</Button></div>{row.url&&<img className="core-master-preview" src={row.url.replace('/api/public/images/','/api/website-images/')} alt=""/>}<FormGrid columns={3}><SelectField label="Media type" value={row.kind} onChange={e=>listUpdate(setMedia,index,'kind',e.target.value)} error={errors[`media.${index}.kind`]}><option value="HERO">Hero</option><option value="GALLERY">Gallery</option></SelectField><StatusField value={row.status} onChange={e=>listUpdate(setMedia,index,'status',e.target.value)}/></FormGrid><FormField label="Image URL" value={row.url||''} onChange={e=>listUpdate(setMedia,index,'url',e.target.value)} error={errors[`media.${index}.url`]}/><Two><FormField label="Thai alt text" value={row.altTh||''} onChange={e=>listUpdate(setMedia,index,'altTh',e.target.value)}/><FormField label="English alt text" value={row.altEn||''} onChange={e=>listUpdate(setMedia,index,'altEn',e.target.value)}/><FormField label="Thai caption" value={row.captionTh||''} onChange={e=>listUpdate(setMedia,index,'captionTh',e.target.value)}/><FormField label="English caption" value={row.captionEn||''} onChange={e=>listUpdate(setMedia,index,'captionEn',e.target.value)}/></Two></div>}
    </MasterDetail>
   </Section>}

   {tab==='faq'&&<Section title="Tour FAQ" description="Select a question on the left, then edit the Thai and English question and answer on the right." actions={<Button onClick={addFaq}>+ Add FAQ</Button>}>
    <MasterDetail items={faqs} selectedId={selectedFaqId} onSelect={id=>selectCollection('faq',id,setSelectedFaqId)} label="Tour FAQ" empty="No FAQ items yet." detailRef={faqDetail} renderItem={(row,index)=><span className="core-master-copy"><strong>{row.questionTh||row.questionEn||`FAQ #${index+1}`}</strong><small>{row.questionTh&&row.questionEn?row.questionEn:'Question not complete yet'}</small><em>{t(labelFor(row.status))}</em></span>}>
     {(row,index)=><div><div className="core-master-pane-header"><div><strong>FAQ #{index+1}</strong><span className="cell-sub">{row.questionTh||row.questionEn||'New question'}</span></div><Button onClick={()=>removeFaq(index)}>Remove</Button></div><StatusField value={row.status} onChange={e=>listUpdate(setFaqs,index,'status',e.target.value)}/><Two><FormField label="Thai question" value={row.questionTh||''} onChange={e=>listUpdate(setFaqs,index,'questionTh',e.target.value)} error={errors[`faqs.${index}.questionTh`]}/><FormField label="English question" value={row.questionEn||''} onChange={e=>listUpdate(setFaqs,index,'questionEn',e.target.value)}/><TextAreaField label="Thai answer" value={row.answerTh||''} onChange={e=>listUpdate(setFaqs,index,'answerTh',e.target.value)}/><TextAreaField label="English answer" value={row.answerEn||''} onChange={e=>listUpdate(setFaqs,index,'answerEn',e.target.value)}/></Two></div>}
    </MasterDetail>
   </Section>}

   {tab==='seo'&&<div className="core-stack"><Section title="Publication" description="Website publishing, URL and Home merchandising. Program classification stays in Overview."><Two><SelectField label="Website publication" value={values.publicStatus} onChange={e=>update('publicStatus',e.target.value)} error={errors.publicStatus}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></SelectField><FormField label="Website URL name" value={values.slug} onChange={e=>update('slug',e.target.value)} error={errors.slug} maxLength={100}/><SelectField label="Show on Home" value={values.homeFeatured} onChange={e=>update('homeFeatured',e.target.value)}><option value="false">Do not feature</option><option value="true">Feature on Home</option></SelectField>{values.homeFeatured==='true'&&<><FormField label="Home display order" type="number" min="1" max="99" value={values.homeFeaturedOrder} onChange={e=>update('homeFeaturedOrder',e.target.value)} error={errors.homeFeaturedOrder}/><SelectField label="Home badge" value={values.homeBadge} onChange={e=>update('homeBadge',e.target.value)}><option value="">No badge</option><option value="BEST_SELLER">Best seller</option><option value="RECOMMENDED">Recommended</option><option value="SIGNATURE">Signature</option></SelectField></>}</Two><div className="core-readiness"><h3>{bilingualLabel('Content readiness')}</h3>{readiness.map(([label,ready])=><span key={label} className={ready?'ready':'missing'}>{ready?'✓':'○'} {label}</span>)}</div></Section><LocaleTabs value={locale} onChange={setLocale}/><Section title="Search appearance" description="SEO metadata for this language. Keep titles useful to people; do not stuff keywords."><FormField label="SEO title" value={current.seoTitle} onChange={e=>updateContent('seoTitle',e.target.value)} error={errors[`content.${locale}.seoTitle`]} maxLength={120}/><TextAreaField label="Meta description" value={current.metaDescription} onChange={e=>updateContent('metaDescription',e.target.value)} error={errors[`content.${locale}.metaDescription`]} maxLength={320}/><Two><FormField label="Open Graph title" value={current.ogTitle} onChange={e=>updateContent('ogTitle',e.target.value)} maxLength={120}/><TextAreaField label="Open Graph description" value={current.ogDescription} onChange={e=>updateContent('ogDescription',e.target.value)} maxLength={320}/></Two></Section>{mediaPreview.length>0&&<Section title="Current media preview"><div className="core-media-grid">{mediaPreview.slice(0,6).map(row=><img key={row.id} src={row.url.replace('/api/public/images/','/api/website-images/')} alt=""/>)}</div></Section>}{activeHighlights.length>0&&<Section title="Current highlight preview"><ul>{activeHighlights.map(row=><li key={row.id}>{locale==='th'?(row.titleTh||row.titleEn):(row.titleEn||row.titleTh)}</li>)}</ul></Section>}</div>}
 </div>
}
