import {emptyTourContent, validateTourContent} from '../../../../../../packages/contracts/tour-content.js'
import {catalog, initialValues, labelFor, validateCatalog, visibleField} from '../../../../../../packages/contracts/catalog.js'
import {translateLabel as bilingualLabel, formatDate, formatNumber} from '../../../core/i18n/runtime.js'
import {useLocale} from '../../../core/i18n/locale.jsx'
import {useNavigation, useUnsavedChanges} from '../../../core/navigation/Navigation.jsx'
import {api} from '../../../core/auth/api.js'
import {Button} from '../../../core/ui/Button.jsx'
import {FormField} from '../../../core/ui/FormField.jsx'
import {TextAreaField} from '../../../core/ui/TextAreaField.jsx'
import {SelectField} from '../../../core/ui/SelectField.jsx'
import {ReferenceField} from '../../../core/ui/ReferenceField.jsx'
import {Tabs} from '../../../core/ui/Tabs.jsx'
import WebsiteImageUpload from '../shared/WebsiteImageUpload.jsx'
import {useCallback, useEffect, useRef, useState} from 'react'
import './TourProgramEditor.css'

const tabs=[
 ['overview','Overview'],['content','Public content'],['package','Package & availability'],['itinerary','Itinerary'],
 ['terms','Terms & conditions'],['media','Media & FAQ'],['seo','SEO & publish'],
]
const publicOrigin=()=>['localhost','127.0.0.1'].includes(location.hostname)?'http://localhost:5173':'https://greenviewtour.com'
const uuid=()=>crypto.randomUUID()
const listRow=(type,index)=> type==='highlight'?{id:uuid(),status:'ACTIVE',sortOrder:index,titleTh:'',titleEn:'',descriptionTh:'',descriptionEn:''}
 :type==='itinerary'?{id:uuid(),status:'ACTIVE',sortOrder:index,day:1,timeLabel:'',titleTh:'',titleEn:'',descriptionTh:'',descriptionEn:'',locationTh:'',locationEn:''}
 :type==='faq'?{id:uuid(),status:'ACTIVE',sortOrder:index,questionTh:'',answerTh:'',questionEn:'',answerEn:''}
 :{id:uuid(),status:'ACTIVE',sortOrder:index,kind:index===0?'HERO':'GALLERY',url:'',altTh:'',altEn:'',captionTh:'',captionEn:''}
function snapshot(values,content,highlights,itinerary,faqs,media){return JSON.stringify({values,content,highlights,itinerary,faqs,media})}
function Section({title,description,children,actions}){return <section className="tour-editor-section panel"><header><div><h2>{bilingualLabel(title)}</h2>{description&&<p>{description}</p>}</div>{actions}</header><div className="tour-editor-body">{children}</div></section>}
function Empty({children}){return <p className="tour-editor-empty">{children}</p>}
function Two({children}){return <div className="tour-editor-grid">{children}</div>}
function LocaleTabs({value,onChange}){return <Tabs items={[{id:'th',label:'Thai content'},{id:'en',label:'English content'}]} value={value} onChange={onChange} label="Content language" idPrefix="tour-content-locale"/>}
function StatusField({value,onChange,label='Status'}){return <SelectField label={label} value={value} onChange={onChange}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></SelectField>}

export default function TourProgramEditor({tourId}){
 const {t}=useLocale(),{navigate}=useNavigation(),isNew=tourId==='new',recordId=useRef(isNew?uuid():tourId)
 const [tab,setTab]=useState('overview'),[locale,setLocale]=useState('th'),[state,setState]=useState({loading:!isNew})
 const [values,setValues]=useState(()=>initialValues('tours')),[version,setVersion]=useState(0)
 const [content,setContent]=useState({th:emptyTourContent(),en:emptyTourContent()}),[highlights,setHighlights]=useState([]),[itinerary,setItinerary]=useState([]),[faqs,setFaqs]=useState([]),[media,setMedia]=useState([])
 const [errors,setErrors]=useState({}),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),baseline=useRef('')
 const hydrate=useCallback(data=>{
   const nextValues=initialValues('tours',data.tour),nextContent={th:{...emptyTourContent(),...data.content?.th},en:{...emptyTourContent(),...data.content?.en}}
   const nextHighlights=(data.highlights||[]).map(row=>({...row})),nextItinerary=(data.itinerary||[]).map(row=>({...row})),nextFaqs=(data.faqs||[]).map(row=>({...row})),nextMedia=(data.media||[]).map(row=>({...row}))
   setValues(nextValues);setVersion(data.tour.version);setContent(nextContent);setHighlights(nextHighlights);setItinerary(nextItinerary);setFaqs(nextFaqs);setMedia(nextMedia)
   setState({loading:false,reference:data});setErrors({});setNotice('');baseline.current=snapshot(nextValues,nextContent,nextHighlights,nextItinerary,nextFaqs,nextMedia)
 },[])
 useEffect(()=>{
   if(isNew){baseline.current=snapshot(values,content,highlights,itinerary,faqs,media);setState({loading:false,reference:{seasons:[],promotions:[],components:[]}});return}
   const controller=new AbortController();setState({loading:true})
   api(`/api/settings/tours/${tourId}/editor`,undefined,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(15000)])}).then(hydrate).catch(error=>{if(!controller.signal.aborted)setState({loading:false,error:error.message})})
   return()=>controller.abort()
 // new editor baseline is intentionally created only once
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[tourId,isNew,hydrate])
 const dirty=baseline.current!==''&&baseline.current!==snapshot(values,content,highlights,itinerary,faqs,media)
 useUnsavedChanges(dirty||saving)
 const update=(key,value)=>{setValues(old=>({...old,[key]:value}));setErrors(old=>({...old,[key]:undefined}));setNotice('')}
 const updateContent=(key,value)=>{setContent(old=>({...old,[locale]:{...old[locale],[key]:value}}));setErrors(old=>({...old,[`content.${locale}.${key}`]:undefined}));setNotice('')}
 const loadOperators=useCallback(({q,page,signal})=>api(`/api/settings/partners?${new URLSearchParams({q,page:String(page),view:'options',status:'ACTIVE',role:'TOUR_OPERATOR'})}`,undefined,{signal}),[])
 const operatorLabel=state.reference?.tour?.operator?.name
 const listUpdate=(setter,index,key,value)=>setter(old=>old.map((row,i)=>i===index?{...row,[key]:value}:row))
 const remove=(setter,index)=>setter(old=>old.filter((_,i)=>i!==index).map((row,i)=>({...row,sortOrder:i})))
 async function save(){
   if(saving)return
   const base=validateCatalog('tours',{...values,id:recordId.current,version}),publicData=validateTourContent({content,highlights,itinerary,faqs,media})
   const nextErrors={...base.errors,...publicData.errors};setErrors(nextErrors)
   if(Object.keys(nextErrors).length){setNotice('Review the highlighted fields before saving.');setTab(Object.keys(base.errors).length?'overview':'content');return}
   setSaving(true);setNotice('')
   try{
     const data=await api(`/api/settings/tours/${recordId.current}/editor`,{program:{...values,id:recordId.current,version},content,highlights,itinerary,faqs,media})
     hydrate(data);setNotice('Tour program saved.')
     if(isNew)navigate(`/settings/tours/${recordId.current}`,{replace:true})
   }catch(error){setNotice(error.message==='SETTINGS_CONFLICT'?'This program changed elsewhere. Reload before saving again.':error.message)}finally{setSaving(false)}
 }
 if(state.loading)return <section className="panel tour-editor-state"><p role="status">{t('Loading current record…')}</p></section>
 if(state.error)return <section className="panel tour-editor-state" role="alert"><h1>{bilingualLabel('Unable to load this record')}</h1><p>{t(state.error)}</p><Button onClick={()=>navigate('/settings/tours')}>Back to tour programs</Button></section>
 const reference=state.reference||{seasons:[],promotions:[],components:[]},current=content[locale]
 const mediaPreview=media.filter(row=>row.status==='ACTIVE'&&row.url),activeHighlights=highlights.filter(row=>row.status==='ACTIVE')
 const readiness=[['Thai summary',Boolean(content.th.summary)],['English summary',Boolean(content.en.summary)],['Hero image',media.some(row=>row.status==='ACTIVE'&&row.kind==='HERO'&&row.url)],['Itinerary',itinerary.some(row=>row.status==='ACTIVE')],['FAQ',faqs.some(row=>row.status==='ACTIVE')],['SEO title TH',Boolean(content.th.seoTitle)],['SEO title EN',Boolean(content.en.seoTitle)]]
 return <div className="tour-editor">
   <div className="page-heading tour-editor-heading"><div><span className="eyebrow">{bilingualLabel('TOUR PROGRAM')}</span><h1 tabIndex={-1}>{values.name||t(isNew?'New tour program':'Tour program')}</h1><p>{t('One source for operations, booking, public content and SEO. Public publishing never exposes supplier or Agent pricing.')}</p></div><div className="page-actions"><Button onClick={()=>navigate('/settings/tours')}>← Tour programs</Button>{values.slug&&<a className="button" target="_blank" rel="noreferrer" href={`${publicOrigin()}/tours?tour=${encodeURIComponent(values.slug)}`}>{t('Preview website')} ↗</a>}<Button className="button-primary" busy={saving} disabled={saving} onClick={save}>Save program</Button></div></div>
   {notice&&<p className={Object.keys(errors).length?'tour-editor-notice error':'tour-editor-notice'} role="status">{t(notice)}</p>}
   <Tabs items={tabs.map(([id,label])=>({id,label}))} value={tab} onChange={setTab} label="Tour program sections" idPrefix="tour-editor"/>

   {tab==='overview'&&<div className="tour-editor-stack">
    <Section title="Program identity" description="Internal identity and operating shape. These fields drive Bookings and Job Orders."><Two>
      <FormField label="Code" value={values.code} onChange={e=>update('code',e.target.value)} error={errors.code} maxLength={40}/><FormField label="Name" value={values.name} onChange={e=>update('name',e.target.value)} error={errors.name} maxLength={200}/>
      <FormField label="Job Order program code" value={values.printCode} onChange={e=>update('printCode',e.target.value)} error={errors.printCode} maxLength={10}/><StatusField value={values.status} onChange={e=>update('status',e.target.value)}/>
      <SelectField label="Organized by" value={values.ownership} onChange={e=>update('ownership',e.target.value)} error={errors.ownership}><option value="GREENVIEW">Greenview Tour</option><option value="PARTNER">Business partner</option></SelectField>
      <SelectField label="Journey type" value={values.journeyMode} onChange={e=>update('journeyMode',e.target.value)} error={errors.journeyMode}>{['FIXED','OPEN_RETURN','OUTBOUND_ONLY','RETURN_ONLY'].map(v=><option key={v} value={v}>{t(labelFor(v))}</option>)}</SelectField>
      {visibleField(catalog.tours.fields.find(f=>f.key==='durationDays'),values)&&<FormField label="Duration in days" type="number" min="1" max="366" value={values.durationDays} onChange={e=>update('durationDays',e.target.value)} error={errors.durationDays}/>}<SelectField label="Booking confirmation" value={values.confirmationMode} onChange={e=>update('confirmationMode',e.target.value)} error={errors.confirmationMode}><option value="REQUEST">Request confirmation</option><option value="INSTANT">Instant confirmation</option></SelectField>
    </Two>{values.ownership==='PARTNER'&&<ReferenceField label="Tour operator" value={values.operatorId} selectedLabel={operatorLabel} onChange={e=>update('operatorId',e.target.value)} error={errors.operatorId} load={loadOperators}/>}</Section>
    <Section title="Booking commission" description="Internal staff commission only. This information never belongs to the Public API."><Two>
      <SelectField label="Booking staff commission" value={values.bookingCommissionEligible} onChange={e=>update('bookingCommissionEligible',e.target.value)}><option value="false">No commission</option><option value="true">Commission enabled</option></SelectField>
      {values.bookingCommissionEligible==='true'&&<><FormField label="Booking staff commission per adult (THB)" value={values.bookingAdultCommission} onChange={e=>update('bookingAdultCommission',e.target.value)} error={errors.bookingAdultCommission}/><FormField label="Booking staff commission per child (THB)" value={values.bookingChildCommission} onChange={e=>update('bookingChildCommission',e.target.value)} error={errors.bookingChildCommission}/></>}
    </Two></Section>
   </div>}

   {tab==='content'&&<div className="tour-editor-stack"><LocaleTabs value={locale} onChange={setLocale}/>
    <Section title="Public introduction" description="Customer-facing copy for this language. Keep facts consistent with the structured package below."><Two>
      <FormField label="Public tour name" value={current.name} onChange={e=>updateContent('name',e.target.value)} error={errors[`content.${locale}.name`]} maxLength={200}/><FormField label="Content reviewed" type="date" value={current.contentReviewedAt} onChange={e=>updateContent('contentReviewedAt',e.target.value)} error={errors[`content.${locale}.contentReviewedAt`]}/>
    </Two><TextAreaField label="Short summary" value={current.summary} onChange={e=>updateContent('summary',e.target.value)} error={errors[`content.${locale}.summary`]} maxLength={1000}/><TextAreaField label="Introduction" value={current.introduction} onChange={e=>updateContent('introduction',e.target.value)} error={errors[`content.${locale}.introduction`]} maxLength={5000}/><TextAreaField label="Long description" value={current.longDescription} onChange={e=>updateContent('longDescription',e.target.value)} error={errors[`content.${locale}.longDescription`]} maxLength={20000}/></Section>
    <Section title="Highlights" description="Short scan-friendly reasons to choose this program. Each item supports Thai and English." actions={<Button onClick={()=>setHighlights(old=>[...old,listRow('highlight',old.length)])}>+ Add highlight</Button>}>
      {!highlights.length?<Empty>No highlights yet.</Empty>:highlights.map((row,index)=><article className="tour-editor-repeat" key={row.id}><div className="tour-editor-repeat-head"><strong>#{index+1}</strong><Button onClick={()=>remove(setHighlights,index)}>Remove</Button></div><Two><FormField label="Thai title" value={row.titleTh||''} onChange={e=>listUpdate(setHighlights,index,'titleTh',e.target.value)} error={errors[`highlights.${index}.titleTh`]}/><FormField label="English title" value={row.titleEn||''} onChange={e=>listUpdate(setHighlights,index,'titleEn',e.target.value)} error={errors[`highlights.${index}.titleEn`]}/></Two><Two><TextAreaField label="Thai detail" value={row.descriptionTh||''} onChange={e=>listUpdate(setHighlights,index,'descriptionTh',e.target.value)}/><TextAreaField label="English detail" value={row.descriptionEn||''} onChange={e=>listUpdate(setHighlights,index,'descriptionEn',e.target.value)}/></Two></article>)}
    </Section>
   </div>}

   {tab==='package'&&<div className="tour-editor-stack">
    <Section title="Direct pricing" description="Public direct prices. Agent selling prices remain in Agent prices and are never returned by the Public API."><Two><FormField label="Direct adult price (THB)" value={values.adultPrice} onChange={e=>update('adultPrice',e.target.value)} error={errors.adultPrice}/><FormField label="Direct child price (THB)" value={values.childPrice} onChange={e=>update('childPrice',e.target.value)} error={errors.childPrice}/>{values.ownership==='PARTNER'&&<><SelectField label="Supplier pricing basis" value={values.supplierPricing} onChange={e=>update('supplierPricing',e.target.value)}><option value="NOT_SET">Not set</option><option value="NET">Net cost</option><option value="COMMISSION">Commission per passenger</option></SelectField>{values.supplierPricing==='NET'?<><FormField label="Supplier adult net (THB)" value={values.supplierAdultNet} onChange={e=>update('supplierAdultNet',e.target.value)}/><FormField label="Supplier child net (THB)" value={values.supplierChildNet} onChange={e=>update('supplierChildNet',e.target.value)}/></>:values.supplierPricing==='COMMISSION'?<><FormField label="Adult commission received (THB)" value={values.supplierAdultCommission} onChange={e=>update('supplierAdultCommission',e.target.value)}/><FormField label="Child commission received (THB)" value={values.supplierChildCommission} onChange={e=>update('supplierChildCommission',e.target.value)}/></>:null}</>}</Two></Section>
    <Section title="Package services" description="Source of truth: Program components. Included / required / optional / excluded services should be maintained here, not duplicated in SEO copy.">{!reference.components?.length?<Empty>No program components linked yet. Add services from Program components.</Empty>:<div className="tour-editor-list">{reference.components.map(row=><div key={row.id}><strong>{row.resource?.name||'Service'}</strong><span>{t(labelFor(row.selection))} · {formatNumber(row.quantity)} {t(labelFor(row.basis))}{row.day?` · Day ${row.day}`:''}</span></div>)}</div>}<a className="button" href="/settings/components">Open Program components →</a></Section>
    <Section title="Availability" description="Source of truth: Tour seasons. Service dates, online travel dates, booking windows, closed dates and cutoff stay structured.">{!reference.seasons?.length?<Empty>No seasons configured yet.</Empty>:<div className="tour-editor-list">{reference.seasons.map(row=><div key={row.id}><strong>{row.name}</strong><span>{formatDate(row.startsOn)} – {formatDate(row.endsOn)} · {t(labelFor(row.status))} · cutoff {row.cutoffDays} day(s)</span></div>)}</div>}<a className="button" href="/settings/seasons">Open Tour seasons →</a></Section>
    <Section title="Promotions" description="Promotion booking period and travel period remain independent structured records.">{!reference.promotions?.length?<Empty>No promotions configured.</Empty>:<div className="tour-editor-list">{reference.promotions.map(row=><div key={row.id}><strong>{row.name}</strong><span>{formatDate(row.serviceStartsOn)} – {formatDate(row.serviceEndsOn)} · {t(labelFor(row.status))}</span></div>)}</div>}<a className="button" href="/settings/promotions">Open Promotions →</a></Section>
   </div>}

   {tab==='itinerary'&&<Section title="Structured itinerary" description="One step per time/location. Public can render this as a timeline and structured itinerary." actions={<Button onClick={()=>setItinerary(old=>[...old,listRow('itinerary',old.length)])}>+ Add step</Button>}>
    {!itinerary.length?<Empty>No itinerary steps yet.</Empty>:itinerary.map((row,index)=><article className="tour-editor-repeat" key={row.id}><div className="tour-editor-repeat-head"><strong>Step {index+1}</strong><Button onClick={()=>remove(setItinerary,index)}>Remove</Button></div><div className="tour-editor-grid compact"><FormField label="Day" type="number" min="1" max="366" value={row.day} onChange={e=>listUpdate(setItinerary,index,'day',e.target.value)} error={errors[`itinerary.${index}.day`]}/><FormField label="Time label" value={row.timeLabel||''} onChange={e=>listUpdate(setItinerary,index,'timeLabel',e.target.value)}/><StatusField value={row.status} onChange={e=>listUpdate(setItinerary,index,'status',e.target.value)}/></div><Two><FormField label="Thai title" value={row.titleTh||''} onChange={e=>listUpdate(setItinerary,index,'titleTh',e.target.value)} error={errors[`itinerary.${index}.titleTh`]}/><FormField label="English title" value={row.titleEn||''} onChange={e=>listUpdate(setItinerary,index,'titleEn',e.target.value)}/><FormField label="Thai location" value={row.locationTh||''} onChange={e=>listUpdate(setItinerary,index,'locationTh',e.target.value)}/><FormField label="English location" value={row.locationEn||''} onChange={e=>listUpdate(setItinerary,index,'locationEn',e.target.value)}/></Two><Two><TextAreaField label="Thai detail" value={row.descriptionTh||''} onChange={e=>listUpdate(setItinerary,index,'descriptionTh',e.target.value)}/><TextAreaField label="English detail" value={row.descriptionEn||''} onChange={e=>listUpdate(setItinerary,index,'descriptionEn',e.target.value)}/></Two></article>)}
   </Section>}

   {tab==='terms'&&<div className="tour-editor-stack"><LocaleTabs value={locale} onChange={setLocale}/><Section title="Customer terms" description="Public-facing operating conditions. Do not put internal supplier prices or settlement notes here."><Two><TextAreaField label="Departure times" value={current.departureTimes} onChange={e=>updateContent('departureTimes',e.target.value)}/><TextAreaField label="Booking cutoff" value={current.bookingCutoff} onChange={e=>updateContent('bookingCutoff',e.target.value)}/><TextAreaField label="Child age / height policy" value={current.childPolicy} onChange={e=>updateContent('childPolicy',e.target.value)}/><TextAreaField label="Cancellation terms" value={current.cancellationTerms} onChange={e=>updateContent('cancellationTerms',e.target.value)}/><TextAreaField label="Meals and dietary options" value={current.meals} onChange={e=>updateContent('meals',e.target.value)}/><TextAreaField label="Fees" value={current.fees} onChange={e=>updateContent('fees',e.target.value)}/><TextAreaField label="Included services" value={current.inclusions} onChange={e=>updateContent('inclusions',e.target.value)}/><TextAreaField label="Not included" value={current.exclusions} onChange={e=>updateContent('exclusions',e.target.value)}/><TextAreaField label="What to bring and participation restrictions" value={current.preparationNotes} onChange={e=>updateContent('preparationNotes',e.target.value)}/><TextAreaField label="Special conditions" value={current.specialConditions} onChange={e=>updateContent('specialConditions',e.target.value)}/></Two></Section>
    {values.ownership==='PARTNER'&&<Section title="Partner verification" description="Internal evidence of where partner terms came from and when they were checked. These fields are not public."><FormField label="Partner source / reference URL" type="url" value={values.partnerSourceUrl} onChange={e=>update('partnerSourceUrl',e.target.value)} error={errors.partnerSourceUrl}/><Two><FormField label="Partner terms verified" type="date" value={values.partnerTermsVerifiedAt} onChange={e=>update('partnerTermsVerifiedAt',e.target.value)}/><FormField label="Partner content verified" type="date" value={values.partnerContentVerifiedAt} onChange={e=>update('partnerContentVerifiedAt',e.target.value)}/></Two></Section>}
   </div>}

   {tab==='media'&&<div className="tour-editor-stack"><Section title="Tour media" description="Hero and gallery images. Alt text and captions are authored separately for Thai and English." actions={<Button onClick={()=>setMedia(old=>[...old,listRow('media',old.length)])}>+ Add media</Button>}><WebsiteImageUpload disabled={saving} onUploaded={url=>setMedia(old=>[...old,{...listRow('media',old.length),url}])}/>{!media.length?<Empty>No media yet.</Empty>:media.map((row,index)=><article className="tour-editor-repeat" key={row.id}><div className="tour-editor-repeat-head"><strong>{row.kind==='HERO'?'Hero':'Gallery'} #{index+1}</strong><Button onClick={()=>remove(setMedia,index)}>Remove</Button></div>{row.url&&<img className="tour-editor-thumb" src={row.url.replace('/api/public/images/','/api/website-images/')} alt=""/>}<div className="tour-editor-grid compact"><SelectField label="Media type" value={row.kind} onChange={e=>listUpdate(setMedia,index,'kind',e.target.value)} error={errors[`media.${index}.kind`]}><option value="HERO">Hero</option><option value="GALLERY">Gallery</option></SelectField><StatusField value={row.status} onChange={e=>listUpdate(setMedia,index,'status',e.target.value)}/></div><FormField label="Image URL" value={row.url||''} onChange={e=>listUpdate(setMedia,index,'url',e.target.value)} error={errors[`media.${index}.url`]}/><Two><FormField label="Thai alt text" value={row.altTh||''} onChange={e=>listUpdate(setMedia,index,'altTh',e.target.value)}/><FormField label="English alt text" value={row.altEn||''} onChange={e=>listUpdate(setMedia,index,'altEn',e.target.value)}/><FormField label="Thai caption" value={row.captionTh||''} onChange={e=>listUpdate(setMedia,index,'captionTh',e.target.value)}/><FormField label="English caption" value={row.captionEn||''} onChange={e=>listUpdate(setMedia,index,'captionEn',e.target.value)}/></Two></article>)}</Section>
    <Section title="Tour FAQ" description="Questions specific to this program. Public V2 can use these for the page FAQ and structured data." actions={<Button onClick={()=>setFaqs(old=>[...old,listRow('faq',old.length)])}>+ Add FAQ</Button>}>{!faqs.length?<Empty>No FAQ items yet.</Empty>:faqs.map((row,index)=><article className="tour-editor-repeat" key={row.id}><div className="tour-editor-repeat-head"><strong>FAQ #{index+1}</strong><Button onClick={()=>remove(setFaqs,index)}>Remove</Button></div><Two><FormField label="Thai question" value={row.questionTh||''} onChange={e=>listUpdate(setFaqs,index,'questionTh',e.target.value)} error={errors[`faqs.${index}.questionTh`]}/><FormField label="English question" value={row.questionEn||''} onChange={e=>listUpdate(setFaqs,index,'questionEn',e.target.value)}/><TextAreaField label="Thai answer" value={row.answerTh||''} onChange={e=>listUpdate(setFaqs,index,'answerTh',e.target.value)}/><TextAreaField label="English answer" value={row.answerEn||''} onChange={e=>listUpdate(setFaqs,index,'answerEn',e.target.value)}/></Two></article>)}</Section></div>}

   {tab==='seo'&&<div className="tour-editor-stack"><Section title="Publication" description="The current Public site continues using the compatibility fields generated from this editor until Tour Detail V2 is switched over."><Two><SelectField label="Website publication" value={values.publicStatus} onChange={e=>update('publicStatus',e.target.value)} error={errors.publicStatus}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></SelectField><SelectField label="Tour type" value={values.tourType} onChange={e=>update('tourType',e.target.value)} error={errors.tourType}><option value="">Not set</option>{['DAY_TRIP','OVERNIGHT','PRIVATE','JOIN','TRANSFER'].map(v=><option key={v} value={v}>{t(labelFor(v))}</option>)}</SelectField><FormField label="Website URL name" value={values.slug} onChange={e=>update('slug',e.target.value)} error={errors.slug} maxLength={100}/></Two><div className="tour-readiness"><h3>{bilingualLabel('Content readiness')}</h3>{readiness.map(([label,ready])=><span key={label} className={ready?'ready':'missing'}>{ready?'✓':'○'} {label}</span>)}</div></Section><LocaleTabs value={locale} onChange={setLocale}/><Section title="Search appearance" description="SEO metadata for this language. Keep titles useful to people; do not stuff keywords."><FormField label="SEO title" value={current.seoTitle} onChange={e=>updateContent('seoTitle',e.target.value)} error={errors[`content.${locale}.seoTitle`]} maxLength={120}/><TextAreaField label="Meta description" value={current.metaDescription} onChange={e=>updateContent('metaDescription',e.target.value)} error={errors[`content.${locale}.metaDescription`]} maxLength={320}/><Two><FormField label="Open Graph title" value={current.ogTitle} onChange={e=>updateContent('ogTitle',e.target.value)} maxLength={120}/><TextAreaField label="Open Graph description" value={current.ogDescription} onChange={e=>updateContent('ogDescription',e.target.value)} maxLength={320}/></Two></Section>{mediaPreview.length>0&&<Section title="Current media preview"><div className="tour-media-preview">{mediaPreview.slice(0,6).map(row=><img key={row.id} src={row.url.replace('/api/public/images/','/api/website-images/')} alt=""/>)}</div></Section>}{activeHighlights.length>0&&<Section title="Current highlight preview"><ul>{activeHighlights.map(row=><li key={row.id}>{locale==='th'?(row.titleTh||row.titleEn):(row.titleEn||row.titleTh)}</li>)}</ul></Section>}</div>}
 </div>
}
