-- Authorization catalog from packages/contracts/access.js and identity-access/policy.js.
-- Fresh Production database only; contains no users, sessions or business records.
INSERT INTO Role(code,name) VALUES ('ADMIN_MANAGER','Admin Manager');
INSERT INTO Role(code,name) VALUES ('MANAGER','Manager');
INSERT INTO Role(code,name) VALUES ('BOOKING','Booking Assistant');
INSERT INTO Role(code,name) VALUES ('HEAD_BOOKING','Booking Manager');
INSERT INTO Role(code,name) VALUES ('SALES','Sales');
INSERT INTO Role(code,name) VALUES ('ACCOUNT','Account');
INSERT INTO Role(code,name) VALUES ('GUIDE','Guide');
INSERT INTO Role(code,name) VALUES ('HEAD_GUIDE','Head Guide');
INSERT INTO Role(code,name) VALUES ('ASSISTANT_TOUR_GUIDE','Assistant tour guide');
INSERT INTO Role(code,name) VALUES ('CAPTAIN','Captain');
INSERT INTO Role(code,name) VALUES ('HEAD_CAPTAIN','Head Captain');
INSERT INTO Role(code,name) VALUES ('ASSISTANT_CAPTAIN','Assistant Captain');
INSERT INTO Role(code,name) VALUES ('DRIVER','Driver');
INSERT INTO Role(code,name) VALUES ('HEAD_DRIVER','Head Driver');
INSERT INTO Role(code,name) VALUES ('HOUSEKEEPING','Housekeeping');
INSERT INTO Role(code,name) VALUES ('HEAD_HOUSEKEEPING','Head Housekeeping');
INSERT INTO Permission(code,description) VALUES ('users.profile.edit','Edit account profile within delegated department');
INSERT INTO Permission(code,description) VALUES ('profile.read','Read own account');
INSERT INTO Permission(code,description) VALUES ('users.read','Read company user directory');
INSERT INTO Permission(code,description) VALUES ('users.invite','Invite ordinary staff');
INSERT INTO Permission(code,description) VALUES ('users.roles','Assign ordinary roles');
INSERT INTO Permission(code,description) VALUES ('users.suspend','Suspend ordinary staff');
INSERT INTO Permission(code,description) VALUES ('managers.manage','Manage Manager accounts');
INSERT INTO Permission(code,description) VALUES ('administrators.manage','Manage Admin Manager grants');
INSERT INTO Permission(code,description) VALUES ('audit.read','Read account audit events');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('ADMIN_MANAGER','users.profile.edit');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('ADMIN_MANAGER','profile.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('ADMIN_MANAGER','users.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('ADMIN_MANAGER','users.invite');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('ADMIN_MANAGER','users.roles');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('ADMIN_MANAGER','users.suspend');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('ADMIN_MANAGER','managers.manage');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('ADMIN_MANAGER','administrators.manage');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('ADMIN_MANAGER','audit.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('MANAGER','users.profile.edit');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('MANAGER','profile.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('MANAGER','users.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('MANAGER','users.invite');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('MANAGER','users.roles');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('MANAGER','users.suspend');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('MANAGER','audit.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('BOOKING','profile.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('HEAD_BOOKING','profile.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('HEAD_BOOKING','users.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('HEAD_BOOKING','users.profile.edit');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('SALES','profile.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('ACCOUNT','profile.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('GUIDE','profile.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('HEAD_GUIDE','profile.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('HEAD_GUIDE','users.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('HEAD_GUIDE','users.profile.edit');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('ASSISTANT_TOUR_GUIDE','profile.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('CAPTAIN','profile.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('HEAD_CAPTAIN','profile.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('HEAD_CAPTAIN','users.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('HEAD_CAPTAIN','users.profile.edit');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('ASSISTANT_CAPTAIN','profile.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('DRIVER','profile.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('HEAD_DRIVER','profile.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('HEAD_DRIVER','users.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('HEAD_DRIVER','users.profile.edit');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('HOUSEKEEPING','profile.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('HEAD_HOUSEKEEPING','profile.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('HEAD_HOUSEKEEPING','users.read');
INSERT INTO RolePermission(roleCode,permissionCode) VALUES ('HEAD_HOUSEKEEPING','users.profile.edit');
