// Public editorial routes; live offers and operational data remain API-owned.
export const publicInfoRoutes = {
  '/information': {title:{th:'ข้อมูลการท่องเที่ยว',en:'Information'},description:{th:'รู้จักกรีนวิว ทัวร์และหมู่เกาะสุรินทร์ พร้อมข้อมูลเตรียมตัวเดินทาง คำถามที่พบบ่อย และช่องทางติดต่อทีมงาน',en:'Meet Greenview Tour and discover the Surin Islands. Find planning information, frequently asked questions and contact details.'}},
  '/about': {title: {th: 'รู้จักกรีนวิว ทัวร์', en: 'About Greenview Tour'}, description: {th: 'รู้จักกรีนวิว ทัวร์ เริ่มต้นทริปหมู่เกาะสุรินทร์จากคุระบุรี จังหวัดพังงา พร้อมข้อมูลสำหรับเลือกโปรแกรมและติดต่อทีมงาน', en: 'Meet Greenview Tour. Plan your Surin Islands trip from Khura Buri, Phang Nga, explore programmes and contact the team.'}},
  "/surin-islands": {"title": {"th": "รู้จักหมู่เกาะสุรินทร์ก่อนเดินทาง", "en": "Surin Islands: a first-time guide"}, "description": {"th": "รู้จักหมู่เกาะสุรินทร์ในจังหวัดพังงา จุดเด่นของการเที่ยวทะเล และสิ่งที่ควรตัดสินใจก่อนวางแผนเดินทาง", "en": "Get oriented to the Surin Islands in Phang Nga, their marine setting and the decisions to make before planning a visit."}},
  "/surin-islands/getting-there": {"title": {"th": "ไปหมู่เกาะสุรินทร์อย่างไร", "en": "How to get to the Surin Islands"}, "description": {"th": "วางแผนการเดินทางไปหมู่เกาะสุรินทร์โดยแยกช่วงเดินทางบนฝั่งกับเรือ พร้อมตรวจจุดรับและแผนขากลับ", "en": "Plan the mainland and boat legs separately, confirm your pickup and departure points, and leave room for the return journey."}},
  "/surin-islands/piers": {"title": {"th": "เตรียมตัวที่ท่าเรือไปหมู่เกาะสุรินทร์", "en": "Surin Islands departure and check-in checklist"}, "description": {"th": "ตรวจท่าเรือ จุดนัดพบ ที่จอดรถ และสัมภาระก่อนออกเดินทาง เพื่อให้วันขึ้นเรือไปหมู่เกาะสุรินทร์ราบรื่น", "en": "Confirm the exact pier, meeting point, parking arrangements and luggage plan before your Surin Islands departure."}},
  "/surin-islands/best-time": {"title": {"th": "เลือกวันเที่ยวหมู่เกาะสุรินทร์อย่างไร", "en": "Choosing dates for a Surin Islands visit"}, "description": {"th": "เลือกวันเที่ยวหมู่เกาะสุรินทร์โดยดูประกาศเปิดพื้นที่ควบคู่กับสภาพทะเล และแยกฤดูท่องเที่ยวออกจากพยากรณ์รายวัน", "en": "Choose travel dates using official access notices and sea conditions, while keeping seasonal patterns separate from daily forecasts."}},
  "/surin-islands/weather": {"title": {"th": "อ่านอากาศและคลื่นลมก่อนเที่ยวสุรินทร์", "en": "Surin Islands weather and sea conditions"}, "description": {"th": "อ่านพยากรณ์ทะเลก่อนเที่ยวหมู่เกาะสุรินทร์ ตรวจเวลาที่ออกประกาศ และเตรียมแผนเมื่อเรือหรือกิจกรรมเปลี่ยน", "en": "Read marine forecasts, check when warnings were issued, and prepare for changes to your crossing or island activities."}},
  "/surin-islands/how-many-days": {"title": {"th": "เที่ยวสุรินทร์กี่วันดี", "en": "Surin Islands: day trip or overnight?"}, "description": {"th": "เปรียบเทียบเที่ยวสุรินทร์แบบไปเช้าเย็นกลับกับค้างคืนจากเวลาเดินทาง ความสบาย และเวลาพักที่ต้องการ", "en": "Compare a Surin day trip with an overnight stay using travel time, comfort and the amount of unhurried time you want."}},
  "/surin-islands/costs": {"title": {"th": "วางงบเที่ยวหมู่เกาะสุรินทร์", "en": "Budgeting for a Surin Islands trip"}, "description": {"th": "แยกค่าเดินทาง ค่าเข้าพื้นที่ ที่พัก อาหาร และอุปกรณ์ก่อนเปรียบเทียบงบเที่ยวหมู่เกาะสุรินทร์", "en": "Separate transport, entry, accommodation, meals and equipment costs before comparing the total budget for a Surin visit."}},
  "/surin-islands/accommodation": {"title": {"th": "เต็นท์และที่พักบนหมู่เกาะสุรินทร์", "en": "Surin Islands camping and accommodation"}, "description": {"th": "ทำความเข้าใจโซนพักบนหมู่เกาะสุรินทร์ และคำถามเรื่องที่นอน ห้องน้ำ อาหาร และเรือที่ควรตรวจให้ครบ", "en": "Understand the park’s accommodation areas and what to confirm about bedding, bathrooms, meals and boat connections."}},
  "/surin-islands/facilities": {"title": {"th": "ห้องน้ำ ไฟฟ้า และการติดต่อบนเกาะสุรินทร์", "en": "Surin Islands facilities: what to check"}, "description": {"th": "เตรียมเรื่องห้องน้ำ น้ำดื่ม ชาร์จไฟ สัญญาณโทรศัพท์ และการจ่ายเงิน โดยตรวจตามจุดพักจริงบนหมู่เกาะสุรินทร์", "en": "Prepare for bathrooms, drinking water, charging, phone connectivity and payment arrangements at your actual island stop."}},
  "/surin-islands/snorkeling": {"title": {"th": "เลือกจุดดำน้ำตื้นหมู่เกาะสุรินทร์", "en": "Choosing Surin Islands snorkeling sites"}, "description": {"th": "รู้จักการเลือกจุดดำน้ำตื้นหมู่เกาะสุรินทร์จากสภาพน้ำ จุดขึ้นลง และความพร้อม แทนการยึดรายชื่ออ่าวตายตัว", "en": "Choose snorkeling stops by conditions, entry and exit arrangements, and ability rather than expecting a fixed list of bays."}},
  "/surin-islands/beginner-snorkeling": {"title": {"th": "ดำน้ำตื้นสุรินทร์สำหรับมือใหม่", "en": "Surin snorkeling for beginners"}, "description": {"th": "เตรียมตัวดำน้ำตื้นครั้งแรกที่หมู่เกาะสุรินทร์ ตั้งแต่แจ้งทักษะการว่ายน้ำ ทดลองอุปกรณ์ ไปจนถึงเลือกข้ามกิจกรรม", "en": "Prepare for a first snorkel by explaining your swimming ability, getting help with equipment and knowing when to sit out."}},
  "/surin-islands/marine-life": {"title": {"th": "สัตว์ทะเลที่อาจพบรอบหมู่เกาะสุรินทร์", "en": "Marine life around the Surin Islands"}, "description": {"th": "รู้จักกลุ่มปลาตามแนวปะการังรอบหมู่เกาะสุรินทร์ และวิธีสังเกตสัตว์ทะเลโดยไม่รบกวนหรือคาดหวังการพบแน่นอน", "en": "Learn about reef fish recorded around Surin and how to observe marine life without disturbance or guaranteed-sighting expectations."}},
  "/surin-islands/coral-reefs": {"title": {"th": "ทำความเข้าใจแนวปะการังสุรินทร์", "en": "Understanding Surin’s coral reefs"}, "description": {"th": "รู้ว่าปะการังเป็นสัตว์ เข้าใจความหมายของการฟอกขาว และแยกความรู้ทั่วไปออกจากสภาพแนวปะการังสุรินทร์ปัจจุบัน", "en": "Understand coral as living animals, what bleaching means and why general reef knowledge cannot establish today’s Surin conditions."}},
  "/surin-islands/beaches": {"title": {"th": "อ่าวและพื้นที่พักริมทะเลสุรินทร์", "en": "Surin Islands bays and visitor areas"}, "description": {"th": "แยกพื้นที่พัก จุดบริการ และจุดลงน้ำของหมู่เกาะสุรินทร์ พร้อมตรวจทางขึ้นลงและข้อจำกัดของอ่าวที่จะไป", "en": "Distinguish accommodation areas from swimming and snorkeling stops, and check access arrangements at the bay you will visit."}},
  "/surin-islands/moken-community": {"title": {"th": "รู้จักชุมชนมอแกนเกาะสุรินทร์", "en": "Learning about Surin’s Moken community"}, "description": {"th": "เรียนรู้บริบทชุมชนมอแกนเกาะสุรินทร์ พร้อมหลักการเยี่ยมเยือนที่เคารพเจ้าบ้าน ความเป็นส่วนตัว และการตัดสินใจของชุมชน", "en": "Learn about the Moken community and approach any visit with respect for residents, privacy and the community’s own decisions."}},
  "/surin-islands/with-children": {"title": {"th": "เตรียมเที่ยวสุรินทร์กับเด็ก", "en": "Planning a Surin Islands family visit"}, "description": {"th": "ประเมินทริปสุรินทร์จากการเดินทาง อุปกรณ์เด็ก การดูแลใกล้น้ำ และทางเลือกพักก่อนตัดสินใจพาครอบครัวไป", "en": "Assess the crossing, child-sized equipment, supervision near water and rest options before choosing a family visit."}},
  "/surin-islands/travel-guide": {"title": {"th": "จัดกระเป๋าเที่ยวหมู่เกาะสุรินทร์", "en": "What to pack for the Surin Islands"}, "description": {"th": "จัดของสำหรับเที่ยวหมู่เกาะสุรินทร์แบบวันเดียวหรือค้างคืน แยกของใช้ระหว่างทางและตรวจอุปกรณ์ที่มีให้ก่อนแพ็ก", "en": "Pack for a day visit or overnight stay, keep crossing essentials accessible and check what equipment is actually supplied."}},
  "/surin-islands/park-rules": {"title": {"th": "ตรวจข้อกำหนดก่อนเข้าสุรินทร์", "en": "Surin Islands entry and park rules"}, "description": {"th": "เตรียมข้อมูลเข้าพื้นที่และตรวจประกาศอุทยานหมู่เกาะสุรินทร์ รวมถึงเขตปิด อุปกรณ์ และกิจกรรมที่ต้องสอบถามก่อน", "en": "Check entry arrangements and park notices, including restricted areas, equipment and activities that need advance clarification."}},
  "/surin-islands/responsible-travel": {"title": {"th": "เที่ยวสุรินทร์อย่างรับผิดชอบ", "en": "Responsible visits to the Surin Islands"}, "description": {"th": "ลดผลกระทบระหว่างดำน้ำตื้นและพักบนเกาะสุรินทร์ ด้วยการดูแลอุปกรณ์ เว้นระยะสัตว์ทะเล และจัดการขยะของตนเอง", "en": "Reduce your impact while snorkeling and spending time ashore by controlling equipment, respecting wildlife and managing your waste."}},
  "/surin-islands/surin-vs-similan": {"title": {"th": "สุรินทร์หรือสิมิลัน เลือกอย่างไร", "en": "Surin or Similan: how to choose"}, "description": {"th": "เปรียบเทียบสุรินทร์กับสิมิลันจากสิ่งที่อยากเห็น การเดินทาง และรูปแบบทริป โดยไม่ตัดสินจากภาพทะเลเพียงอย่างเดียว", "en": "Compare Surin and Similan by the scenery you want, transport arrangements and trip format rather than photographs alone."}},
  '/faq': {title: {th: 'คำถามที่พบบ่อย', en: 'Frequently asked questions'}, description: {th: 'คำถามเรื่องโปรแกรมทัวร์สุรินทร์ สถานะคำขอจอง วันกลับ อาหาร และข้อมูลที่ควรเตรียมก่อนติดต่อกรีนวิว ทัวร์', en: 'Answers about Surin tour choices, booking requests, return dates, meals and preparing to contact Greenview Tour.'}},
  '/contact-us': {title: {th: 'ติดต่อกรีนวิว ทัวร์', en: 'Contact Greenview Tour'}, description: {th: 'ช่องทางติดต่อ ที่ตั้ง และแผนที่กรีนวิว ทัวร์จากข้อมูลบริษัท พร้อมข้อมูลที่ควรแจ้งเพื่อวางแผนทริปหมู่เกาะสุรินทร์', en: 'Find Greenview Tour contact details, location and map, and the information to share when planning your island trip.'}},
}
export const normalizePublicPath = value => value === '/' ? '/' : value.replace(/\/+$/, '')
const owned = new Set(['/', '/tours', '/promotions', ...Object.keys(publicInfoRoutes)])
export const ownsPublicPath = value => owned.has(normalizePublicPath(value))
export const publicInfo = value => publicInfoRoutes[normalizePublicPath(value)] ?? null
