import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { chromium } from 'playwright'
const output = new URL('../screenshots.local/', import.meta.url)
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ headless: true, ...(process.platform === 'win32' ? { channel: 'msedge' } : {}) })
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  const errors = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('http://localhost:5174/settings/users')
  await page.waitForURL('**/login')
  assert.equal((await page.request.get('http://localhost:5174/api/users')).status(), 401)
  await page.getByRole('heading', { name: 'Welcome back' }).waitFor()
  await page.screenshot({ path: fileURLToPath(new URL('login-desktop.png', output)), fullPage: true })
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByText('Enter a valid email address.', { exact: true }).waitFor()
  assert.equal(await page.getByLabel('Email address', { exact: true }).evaluate(input => input === document.activeElement), true)
  await page.getByLabel('Password', { exact: true }).fill('fixture-password-only')
  await page.getByRole('button', { name: 'Show password', exact: true }).click()
  assert.equal(await page.getByLabel('Password', { exact: true }).getAttribute('type'), 'text')
  await page.getByRole('button', { name: 'Hide password', exact: true }).click()
  await page.getByLabel('Email address', { exact: true }).fill('fixture@example.invalid')
  await page.route('**/api/auth/login', route => route.fulfill({ status: 400, json: { code: 'INVALID_CREDENTIALS' } }))
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('alert').waitFor()
  await page.goto('http://localhost:5174/register')
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await page.getByText('Paste the complete invitation code from your Manager.').waitFor()
  await page.getByLabel('Email address', { exact: true }).fill('fixture@example.invalid')
  await page.getByLabel('Invitation code', { exact: true }).fill('a'.repeat(64))
  await page.getByLabel('New password', { exact: true }).fill('fixture-password-only')
  await page.getByLabel('Confirm password', { exact: true }).fill('different-password')
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await page.getByText('Passwords must match.', { exact: true }).waitFor()
  await page.getByLabel('Confirm password', { exact: true }).fill('fixture-password-only')
  await page.route('**/api/auth/register', route => route.fulfill({ json: { message: 'CONFIRM_EMAIL_THEN_LOGIN' } }))
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await page.getByRole('status').waitFor()
  await page.goto('http://localhost:5174/forgot-password')
  await page.route('**/api/auth/recover', route => route.fulfill({ json: { message: 'RECOVERY_REQUESTED' } }))
  await page.getByLabel('Email address').fill('fixture@example.invalid')
  await page.getByRole('button', { name: 'Send reset link', exact: true }).click()
  await page.getByRole('status').waitFor()
  await page.goto('http://localhost:5174/reset-password')
  await page.getByText('Open the password reset link from your email to continue.').waitFor()
  for (const route of ['login', 'register']) {
    await page.goto(`http://localhost:5174/${route}`)
    await page.setViewportSize({ width: 390, height: 844 })
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
    await page.screenshot({ path: fileURLToPath(new URL(`${route}-mobile.png`, output)), fullPage: true })
  }
  assert.deepEqual(errors, [])
  console.log(JSON.stringify({ result: 'PASS', live: ['anonymous users API denied', 'protected route redirects'], fixtures: ['credential error', 'registration confirmation', 'recovery confirmation'], checks: ['field validation', 'first-error focus', 'password visibility', 'password matching', 'reset without token denied', 'mobile layout'], providerEmailsSent: 0 }))
} finally { await browser.close() }
