import {translateLabel as bilingualLabel} from '../../core/i18n/runtime.js'
import { formatDate as displayDate } from '../../core/i18n/runtime.js'
import { translate as t, useLocale } from '../../core/i18n/locale.jsx'
import {useRef,useState} from 'react'
import {api} from '../../core/auth/api.js'
import {Button} from '../../core/ui/Button.jsx'
import {DataTable} from '../../core/ui/DataTable.jsx'
import {Dialog} from '../../core/ui/Dialog.jsx'
import {FormField} from '../../core/ui/FormField.jsx'
import {useUnsavedChanges} from '../../core/navigation/Navigation.jsx'

function Ink({strokes}){
 useLocale();return strokes.map((stroke,i)=><polyline key={i} points={stroke.map(p=>p.join(',')).join(' ')} fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>)}
export default function BillSignatures({row,signatures=[],documentHash,onSaved}){
 useLocale();
 const [side,setSide]=useState(null)
 return <section className="bill-signatures"><h2>{bilingualLabel("Billing signatures")}</h2><p>{signatures.some(s=>s.side==='AGENT')?t('Received by Agent'):signatures.length?t('Awaiting Agent signature'):t('Awaiting company signature')}{' '}{t("· Signing acknowledges the billing document; payment is recorded separately.")}</p>{['COMPANY','AGENT'].map(role=>{const saved=signatures.find(s=>s.side===role);return <div className="signature-record" key={role}><h3>{role==='COMPANY'?bilingualLabel('Company presenter'):bilingualLabel('Agent recipient')}</h3>{saved?<><svg viewBox="0 0 1000 260" className="signature-pad" role="img" aria-label={t("{value0} signature by {value1}", {value0: role==='COMPANY'?'Company':'Agent', value1: saved.signerName})}><Ink strokes={saved.strokes}/></svg><p>{saved.signerName} · {displayDate(new Date(saved.signedAt), {dateStyle:'short', timeStyle:'medium', ...{timeZone:'Asia/Bangkok'}})}{' '}{t("(Bangkok)")}</p></>:<Button disabled={row.status==='VOID'||role==='AGENT'&&!signatures.some(s=>s.side==='COMPANY')} onClick={()=>setSide(role)}>{t("Sign as")}{' '}{role==='COMPANY'?t('company presenter'):t('Agent recipient')}</Button>}</div>})}{side&&<Sign row={row} side={side} documentHash={documentHash} onClose={()=>setSide(null)} onSaved={()=>{setSide(null);onSaved()}}/>}</section>
}
function Sign({row,side,documentHash,onClose,onSaved}){
 useLocale();
 const [name,setName]=useState(''),[strokes,setStrokes]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[discard,setDiscard]=useState(false),[accepted,setAccepted]=useState(false)
 const drawing=useRef(null),pad=useRef(null),lock=useRef(false),command=useRef(crypto.randomUUID()),cursor=useRef([500,130])
 const dirty=Boolean(name||strokes.length);useUnsavedChanges(dirty)
 const changed=()=>{command.current=crypto.randomUUID();setError('');setAccepted(false)}
 const close=()=>dirty?setDiscard(true):onClose()
 function point(e){const r=pad.current.getBoundingClientRect();return [Math.max(0,Math.min(1000,Math.round((e.clientX-r.left)/r.width*1000))),Math.max(0,Math.min(260,Math.round((e.clientY-r.top)/r.height*260)))]}
 function begin(e){if(busy||e.button!==0||strokes.length>=100)return;e.preventDefault();changed();drawing.current=e.pointerId;pad.current.setPointerCapture(e.pointerId);setStrokes(s=>s.length>=100?s:[...s,[point(e)]])}
 function move(e){if(drawing.current!==e.pointerId)return;const p=point(e);setStrokes(s=>{if(s.reduce((n,l)=>n+l.length,0)>=4000)return s;return s.map((line,i)=>i===s.length-1?[...line,p]:line)})}
 function end(){drawing.current=null;setStrokes(s=>s.filter(line=>line.length>1))}
 function keyboard(e){if(busy||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))return;e.preventDefault();changed();if(e.key===' '){setStrokes(s=>[...s,[cursor.current]]);return}const old=cursor.current,p=[Math.max(0,Math.min(1000,old[0]+(e.key==='ArrowRight'?10:e.key==='ArrowLeft'?-10:0))),Math.max(0,Math.min(260,old[1]+(e.key==='ArrowDown'?10:e.key==='ArrowUp'?-10:0)))];cursor.current=p;setStrokes(s=>s.reduce((n,l)=>n+l.length,0)>=4000?s:s.length?s.map((l,i)=>i===s.length-1?[...l,p]:l):[[old,p]])}
 async function save(e){e.preventDefault();if(lock.current)return;const valid=strokes.filter(s=>s.length>1);if(!name.trim()||valid.flat().length<8||!accepted){setError('Enter your name, draw your signature and confirm the document before saving.');return}lock.current=true;setBusy(true);setError('');try{await api('/api/receivables',{id:command.current,action:'SIGN',billId:row.id,version:row.version,side,signerName:name,strokes:valid,documentHash});onSaved()}catch(e){setError(({RECORD_CONFLICT:'This statement changed. Close and reopen it to review before signing.',ALREADY_SIGNED:'This side has already signed. Close and reopen the statement.',PERMISSION_DENIED:'You no longer have permission to record this signature.',INVALID_SIGNATURE:'Draw a complete signature; a dot or very short mark is not enough.',COMPANY_SIGNATURE_REQUIRED:'The company presenter must sign first.'})[e.message]||'Unable to confirm the signature. Your drawing is retained; retrying will not duplicate it.')}finally{lock.current=false;setBusy(false)}}
 return <Dialog title={side==='COMPANY'?bilingualLabel('Company presenter signature'):bilingualLabel('Agent recipient signature')} variant="signature" busy={busy} onClose={close}><form noValidate onSubmit={save}><p>{row.title} · {row.agentName}</p><p>{t("Total THB")}{' '}{row.total}{' '}{t("· Due")}{' '}{row.dueOn.slice(0,10)}</p><DataTable columns={['Booking','Amount (THB)']} label={bilingualLabel("Bookings in this billing document")}>{row.snapshot.map(b=><tr key={b.bookingId}><td>{b.code} · {b.name}</td><td>{b.total}</td></tr>)}</DataTable><p>{t("The named person signs here on this device. This records the document acknowledgement and does not record a payment.")}</p><FormField label={bilingualLabel("Signer full name")} value={name} required maxLength={160} disabled={busy} onChange={e=>{changed();setName(e.target.value)}}/><p id="signature-help">{t("Draw in the wide box using your finger, pen or mouse. Keyboard: arrow keys draw; Space begins another stroke.")}</p><svg ref={pad} viewBox="0 0 1000 260" preserveAspectRatio="none" className="signature-pad signature-pad-edit" tabIndex={busy?-1:0} role="group" aria-label={t("Draw signature")} aria-describedby="signature-help" onPointerDown={begin} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onKeyDown={keyboard}><Ink strokes={strokes}/></svg><div className="page-actions"><Button disabled={busy} onClick={()=>{changed();setStrokes([])}}>{t("Clear signature")}</Button></div><label className="signature-consent"><input type="checkbox" disabled={busy} checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>{bilingualLabel("I am the named signer and have reviewed this billing document. Save my signature with this version.")}</label>{error&&<p role="alert">{t(error)}</p>}<div className="dialog-actions"><Button disabled={busy} onClick={close}>{t("Cancel")}</Button><Button type="submit" busy={busy} disabled={busy}>{t("Save signature")}</Button></div></form>{discard&&<Dialog title={bilingualLabel("Discard signature?")} onClose={()=>setDiscard(false)}><p>{t("Your unsaved name and signature will be discarded.")}</p><div className="dialog-actions"><Button autoFocus onClick={()=>setDiscard(false)}>{t("Keep signing")}</Button><Button onClick={onClose}>{t("Discard signature")}</Button></div></Dialog>}</Dialog>
}
