import {RefreshButton} from '../../core/ui/RefreshButton.jsx'
import {prepareDocumentImage} from '../../core/ui/prepareDocumentImage.js'
import {Dropdown} from '../../core/ui/Dropdown.jsx'
import {downloadPrivateFile} from '../../core/auth/download.js'
import {useEffect,useRef,useState} from 'react'
import {api} from '../../core/auth/api.js'
import {Button} from '../../core/ui/Button.jsx'
import {Dialog} from '../../core/ui/Dialog.jsx'
import {FormField} from '../../core/ui/FormField.jsx'
import {SelectField} from '../../core/ui/SelectField.jsx'
import {DataTable} from '../../core/ui/DataTable.jsx'
import {Pagination} from '../../core/ui/Pagination.jsx'
import {useUnsavedChanges} from '../../core/navigation/Navigation.jsx'
const types={'image/jpeg':/\.jpe?g$/i,'image/png':/\.png$/i,'application/pdf':/\.pdf$/i}
const shortName=name=>{const parts=Array.from(new Intl.Segmenter('th',{granularity:'grapheme'}).segment(name),s=>s.segment);return parts.length>9?parts.slice(0,8).join('')+'…':name}
const labels={AGENT_TICKET:'Agent ticket',AGENT_BOOKING:'Agent booking confirmation',RECEIPT:'Company-issued receipt',TAX_INVOICE:'Company-issued tax invoice',PAYMENT:'Payment evidence',OTHER:'Other supporting document'}
export default function EvidenceAttachments({targetKind,targetId}){
 const downloadLock=useRef(false)
 const [downloading,setDownloading]=useState(null),[downloadError,setDownloadError]=useState(''),[details,setDetails]=useState(null)
 async function download(row){if(downloadLock.current)return;downloadLock.current=true;setDownloading(row.id);setDownloadError('');try{await downloadPrivateFile(`/api/evidence/${row.id}`,row.filename);setNotice('Download started. Check your browser downloads.')}catch(e){setDownloadError(['LOGIN_REQUIRED','SESSION_REQUIRED','SESSION_EXPIRED'].includes(e.message)?'Your session expired. Sign in again before downloading.':e.message==='PERMISSION_DENIED'?'You no longer have permission to download this document.':'Unable to download the document. Check your connection and retry.')}finally{downloadLock.current=false;setDownloading(null)}}
 const [data,setData]=useState({rows:[],loading:true}),[attempt,setAttempt]=useState(0),[page,setPage]=useState(1),[upload,setUpload]=useState(false),[notice,setNotice]=useState('')
 useEffect(()=>{const controller=new AbortController();api(`/api/evidence?${new URLSearchParams({targetKind,targetId,page})}`,undefined,{signal:controller.signal}).then(d=>{if(!controller.signal.aborted)setData({...d,loading:false})}).catch(()=>{if(!controller.signal.aborted)setData({rows:[],error:'Unable to load supporting documents. Check your access or retry.',loading:false})});return()=>controller.abort()},[targetKind,targetId,page,attempt])
 return <section className="evidence-section" aria-label="Supporting documents"><h2>Supporting documents</h2><p>Attach Agent tickets, booking confirmations or company documents. Uploading a document does not record or change a payment.</p>{notice&&<p role="status">{notice}</p>}{downloadError&&<p role="alert">{downloadError}</p>}<div className="page-actions"><RefreshButton disabled={data.loading} onClick={()=>{setData(s=>({...s,loading:true}));setAttempt(n=>n+1)}} label="Refresh documents"/>{data.access?.upload&&<Button onClick={()=>setUpload(true)}>Attach document</Button>}</div><DataTable columns={[{label:'Document',weight:1.5},{label:'Reference',weight:1.5},{label:'Download',weight:1},{label:'Actions',weight:0.55}]} busy={data.loading} error={data.error} onRetry={()=>setAttempt(n=>n+1)} isEmpty={!data.rows.length}>{data.rows.map(row=><tr key={row.id}><td>{row.filename}<div className="field-help">{labels[row.category]} · {Math.ceil(row.size/1024)} KB</div></td><td>{row.documentNumber||'No document number'}<div>{row.note}</div></td><td><Button className="button-download" title={row.filename} aria-label={`Download ${row.filename}`} disabled={Boolean(downloading)} busy={downloading===row.id} onClick={()=>download(row)}>{shortName(row.filename)}</Button></td><td><Dropdown rowActions label={`Actions for ${row.filename}`} items={[{label:'View document ↗',icon:'view',href:row.mimeType==='application/pdf'?`/api/evidence/${row.id}?view=inline`:`/documents/${row.id}`,target:'_blank'},{label:'View document details',icon:'view',onSelect:()=>setDetails(row)}]}/></td></tr>)}</DataTable><Pagination page={data.page||page} total={data.total} busy={data.loading} onPageChange={setPage}/>{details&&<Dialog title="Document details" onClose={()=>setDetails(null)}><dl className="catalog-details"><div><dt>Filename</dt><dd>{details.filename}</dd></div><div><dt>Type</dt><dd>{labels[details.category]}</dd></div><div><dt>Document number</dt><dd>{details.documentNumber||'Not provided'}</dd></div><div><dt>Note / payment reference</dt><dd>{details.note||'Not provided'}</dd></div></dl><div className="dialog-actions"><Button onClick={()=>setDetails(null)}>Close</Button></div></Dialog>}{upload&&<Upload targetKind={targetKind} targetId={targetId} onClose={()=>setUpload(false)} onSaved={()=>{setUpload(false);setNotice('Document attached.');setPage(1);setAttempt(n=>n+1)}}/>}</section>
}
function Upload({targetKind,targetId,onClose,onSaved}){
 const [file,setFile]=useState(null),[category,setCategory]=useState(targetKind==='BOOKING'?'AGENT_BOOKING':'RECEIPT'),[documentNumber,setNumber]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[discard,setDiscard]=useState(false)
 const [preparing,setPreparing]=useState(false),[originalSize,setOriginalSize]=useState(0),[preview,setPreview]=useState('')
 const selection=useRef(0)
 useEffect(()=>{if(!file||!file.type.startsWith('image/'))return;const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file])
 async function chooseFile(source){if(!source)return;const seq=++selection.current;changed();setPreparing(true);setFile(null);setPreview('');setOriginalSize(source.size);try{const prepared=await prepareDocumentImage(source);if(seq===selection.current)setFile(prepared)}catch(e){if(seq===selection.current)setError(e.message)}finally{if(seq===selection.current)setPreparing(false)}}
 const id=useRef(crypto.randomUUID()),pending=useRef(false),input=useRef(null)
 const dirty=Boolean(file||documentNumber||note||category!==(targetKind==='BOOKING'?'AGENT_BOOKING':'RECEIPT'));useUnsavedChanges(dirty)
 const close=()=>dirty?setDiscard(true):onClose()
 const changed=()=>{id.current=crypto.randomUUID();setError('')}
 async function submit(event){event.preventDefault();if(pending.current||preparing)return
  if(!file||!types[file.type]?.test(file.name)||!file.size||file.size>5242880){setError('Choose a JPEG, PNG or PDF up to 5 MB.');input.current?.focus();return}
  pending.current=true;setBusy(true);setError('')
  try{const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});await api('/api/evidence',{id:id.current,targetKind,targetId,filename:file.name,mimeType:file.type,base64,category,documentNumber,note});onSaved()}
  catch(e){setError(e.message==='INVALID_EVIDENCE_FILE'?'The file does not match its format. Export a fresh JPEG, PNG or PDF and retry.':e.message==='PERMISSION_DENIED'?'You no longer have permission to attach documents.':'Upload could not be confirmed. Your file and entries are retained; retrying will not create a duplicate.')}
  finally{pending.current=false;setBusy(false)}
 }
 return <Dialog title="Attach document" busy={busy||preparing} onClose={close}><form noValidate onSubmit={submit}><FormField key={`file-${selection.current}`} ref={input} type="file" label="Document file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,application/pdf" disabled={busy||preparing} hint="Photos up to 25 MB are compressed before upload; PDF up to 5 MB." onChange={e=>chooseFile(e.target.files?.[0])} error={error}/><FormField key={`camera-${selection.current}`} type="file" label="Take photo" accept="image/*" capture="environment" disabled={busy||preparing} hint="On a supported phone, opens the camera. On desktop, choose a photo from your device." onChange={e=>chooseFile(e.target.files?.[0])}/>{preparing&&<p role="status">Preparing a smaller document image…</p>}{file&&<><p>{file.name} · {Math.ceil(originalSize/1024)} KB → {Math.ceil(file.size/1024)} KB</p>{preview&&<a href={preview} target="_blank" rel="noreferrer" aria-label="Open prepared photo at full size"><img className="evidence-preview" src={preview} alt="Prepared document — check text and numbers before attaching"/></a>}<p>Check that names, amounts and document numbers are readable before attaching.</p><Button disabled={busy} onClick={()=>{selection.current++;setFile(null);setPreview('');changed()}}>Remove selected file</Button></>}<SelectField label="Document type" value={category} disabled={busy} onChange={e=>{changed();setCategory(e.target.value)}}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</SelectField><FormField label="Document number" value={documentNumber} maxLength={100} disabled={busy} onChange={e=>{changed();setNumber(e.target.value)}}/><FormField label="Document note / payment reference" value={note} maxLength={1000} disabled={busy} onChange={e=>{changed();setNote(e.target.value)}}/><p>The file is added to this record's history. Check the selected record and document before attaching.</p><div className="dialog-actions"><Button disabled={busy} onClick={close}>Cancel</Button><Button type="submit" busy={busy||preparing} disabled={busy||preparing}>Attach document</Button></div></form>{discard&&<Dialog title="Discard attachment?" onClose={()=>setDiscard(false)}><p>The selected file and unsaved details will be discarded.</p><Button autoFocus onClick={()=>setDiscard(false)}>Keep editing</Button><Button onClick={onClose}>Discard changes</Button></Dialog>}</Dialog>
}
