import {translateLabel as bilingualLabel} from '../../core/i18n/runtime.js'
import { formatNumber } from '../../core/i18n/runtime.js'
import { translate as t, useLocale } from '../../core/i18n/locale.jsx'
import {RefreshButton} from '../../core/ui/RefreshButton.jsx'
import {saveDownload} from '../../core/auth/download.js'
import EvidenceAttachments from './EvidenceAttachments.jsx'
import { useCallback,useEffect,useRef,useState } from 'react'
import { personnelFinanceKinds,financialTotal,personnelFinanceErrors,cents } from '../../../../../packages/contracts/personnel-finance.js'
import { api } from '../../core/auth/api.js'
import { Button } from '../../core/ui/Button.jsx'
import { DataTable } from '../../core/ui/DataTable.jsx'
import { Dialog } from '../../core/ui/Dialog.jsx'
import { Dropdown } from '../../core/ui/Dropdown.jsx'
import { FormField } from '../../core/ui/FormField.jsx'
import { DateField } from '../../core/ui/DateField.jsx'
import { SelectField } from '../../core/ui/SelectField.jsx'
import { Pagination } from '../../core/ui/Pagination.jsx'
import { SearchField } from '../../core/ui/SearchField.jsx'
import { SummaryCards } from '../../core/ui/SummaryCards.jsx'
import { ReferenceField } from '../../core/ui/ReferenceField.jsx'
import { useUnsavedChanges } from '../../core/navigation/Navigation.jsx'
const label=value=>t(value.toLowerCase().replaceAll('_',' ').replace(/^./,c=>c.toUpperCase()))
const money=value=>formatNumber(value/100, {style:'currency',currency:'THB'})
const messages={RECORD_CONFLICT:'This record changed. Your entries are retained. Close and refresh before editing again.',TRANSITION_NOT_ALLOWED:'This action needs a different authorized employee, or the record has already moved on.',CLEARANCE_MUST_BALANCE:'Expenses plus returned cash must equal the advance.',ATTENDANCE_ALREADY_RECORDED:'An attendance record already exists for this employee and date.',EMPLOYEE_NOT_ASSIGNED:'Choose a Job Order to which this employee is assigned.',PERMISSION_DENIED:'You do not have permission to view or change this information.',INVALID_PAYROLL_TOTAL:'Earnings less deductions must be greater than zero.',INVALID_AMOUNT:'Enter a positive amount with no more than two decimal places.'}
const message=e=>messages[e.message]||'Check the required fields and references, then retry. Your entries are retained.'
export default function PersonnelFinancePage({kind='EMPLOYMENT'}){
 useLocale();
 const [state,setState]=useState({rows:[],employees:[],runs:[],loading:true}),[page,setPage]=useState(1),[attempt,setAttempt]=useState(0),[editor,setEditor]=useState(null),[command,setCommand]=useState(null),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[composing,setComposing]=useState(false),[status,setStatus]=useState('')
 const [exporting,setExporting]=useState(false)
 const spec=personnelFinanceKinds[kind]
 async function exportCsv(){if(exporting)return;setExporting(true);try{const result=await api(`/api/payroll-export?${new URLSearchParams({q:query,status})}`);saveDownload(new Blob([result.csv],{type:'text/csv;charset=utf-8'}),'greenview-payroll.csv');setNotice(`Exported ${result.count} payroll records matching the filters.`)}catch(e){setNotice(e.message==='EXPORT_TOO_LARGE'?'More than 5,000 records match. Narrow the search before exporting.':'Unable to export payroll. Retry after checking your connection and permissions.')}finally{setExporting(false)}}
 useEffect(()=>{if(composing)return;const controller=new AbortController();const timer=setTimeout(()=>{setState(s=>({...s,loading:true,error:null}));api(`/api/personnel-finance?${new URLSearchParams({kind,page,q:query,status})}`,undefined,{signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setState({...data,loading:false})}).catch(e=>{if(!controller.signal.aborted)setState({rows:[],employees:[],runs:[],purchases:[],access:null,summary:null,loading:false,error:message(e)})})},query?300:0);return()=>{clearTimeout(timer);controller.abort()}},[kind,page,attempt,query,status,composing])
 function saved(){setEditor(null);setCommand(null);setNotice('Record saved.');setAttempt(n=>n+1)}
 return <><div className="page-heading"><div><span className="eyebrow">{spec.group==='personnel'?bilingualLabel('COMPANY & PERSONNEL'):bilingualLabel('ACCOUNTS & FINANCE')}</span><h1>{bilingualLabel(spec.title)}</h1><p>{kind==='ATTENDANCE'?t('Record rest, leave and actual attendance separately. No Job Order does not mean absence.'):kind==='PAYROLL'?t('Enter agreed earnings and deductions. A separate reviewer approves the exact draft.'):t('Draft → review → approval. Payments record an external payment and its reference.')}</p></div>{state.access?.edit&&<Button disabled={state.loading} onClick={()=>setEditor({})}>{t("Add record")}</Button>}</div>
 {notice&&<p role="status">{t(notice)}</p>}<SummaryCards label={bilingualLabel("All records, before filters")} items={[{label:'Drafts',value:state.loading?null:state.summary?.draft,detail:'Awaiting submission'},{label:'In review',value:state.loading?null:state.summary?.submitted,detail:'Awaiting separate reviewer'},{label:'Approved',value:state.loading?null:state.summary?.approved,detail:spec.group==='personnel'?'Reviewed records':'Awaiting external payment record'}]}/><section className="panel table-panel"><div className="filterbar"><SearchField value={query} onChange={value=>{setQuery(value);setPage(1)}} onCompositionChange={setComposing} label={bilingualLabel("Search records")} placeholder={t("Search record name…")}/><SelectField label={bilingualLabel("Status")} value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">{t("All statuses")}</option>{['DRAFT','SUBMITTED','APPROVED','REJECTED','PAID','CLEARANCE_SUBMITTED','CLEARED','CANCELLED'].map(s=><option value={s} key={s}>{label(s)}</option>)}</SelectField><RefreshButton onClick={()=>setAttempt(n=>n+1)} disabled={state.loading}/>{kind==='PAYROLL'&&state.access?.view&&<Button disabled={state.loading||exporting} busy={exporting} onClick={exportCsv}>{t("Export filtered payroll CSV")}</Button>}</div><DataTable columns={['Record','Employee','Details','Status','Actions']} busy={state.loading} error={state.error} onRetry={()=>setAttempt(n=>n+1)} isEmpty={!state.rows.length}>
 {state.rows.map(row=><tr key={row.id}><td>{row.title}</td><td>{state.employees.find(e=>e.id===row.employeeId)?.displayName||t("Employee unavailable")}</td><td>{spec.group==='personnel'?(row.payload.date||`${row.payload.startsOn} – ${row.payload.endsOn}`):money(financialTotal(kind,row.payload))}</td><td>{label(row.status)}</td><td><Dropdown rowActions label={bilingualLabel("Actions for {value0}", {value0: row.title})} items={[{label:'View',icon:'view',onSelect:()=>setEditor({...row,readOnly:true})},...(row.status==='DRAFT'&&state.access.edit&&row.createdBy===state.actorId?[{label:'Edit',icon:'edit',onSelect:()=>setEditor(row)}]:[]),...row.actions.map(action=>({label:action==='PAY'?'Record payment':label(action),icon:'briefcase',onSelect:()=>setCommand({row,action})}))]}/></td></tr>)}
 </DataTable><Pagination page={state.page||page} total={state.total} busy={state.loading} onPageChange={setPage}/></section>
 {editor&&<Editor key={editor.id||'new'} kind={kind} row={editor} employees={state.employees} runs={state.runs} purchases={state.purchases||[]} onClose={()=>setEditor(null)} onSaved={saved}/>}
 {command&&<Command {...command} employees={state.employees} runs={state.runs} purchases={state.purchases||[]} onClose={()=>setCommand(null)} onSaved={saved}/>}</>
}
function Lookup({kind,lookup,...props}){
 useLocale();
 const load=useCallback(({q,page,signal})=>api(`/api/personnel-finance?${new URLSearchParams({kind,lookup,q,page})}`,undefined,{signal}),[kind,lookup])
 return <ReferenceField {...props} load={load}/>
}
function Items({items,onChange,readOnly=false,clearance=false,error}){
 useLocale();
 const set=(index,key,value)=>onChange(items.map((item,i)=>i===index?{...item,[key]:value}:item))
 return <fieldset disabled={readOnly}><legend>{clearance?bilingualLabel('Expenses / repayment evidence'):bilingualLabel('Additions and deductions')}</legend>{error&&<p className="field-error" role="alert" tabIndex={-1}>{t(error)}</p>}{items.map((item,index)=><div key={index} className="form-grid"><FormField label={clearance?bilingualLabel('Description'):bilingualLabel('Item description')} value={item[clearance?'description':'label']} onChange={e=>set(index,clearance?'description':'label',e.target.value)} disabled={readOnly} required/>{!clearance&&<><SelectField label={bilingualLabel("Type")} value={item.type} onChange={e=>set(index,'type',e.target.value)} disabled={readOnly}><option value="EARNING">{t("Addition")}</option><option value="DEDUCTION">{t("Deduction")}</option></SelectField><FormField label={bilingualLabel("Reason")} value={item.reason} onChange={e=>set(index,'reason',e.target.value)} disabled={readOnly} required/></>}<FormField label={bilingualLabel("Amount (THB)")} inputMode="decimal" value={item.amount} onChange={e=>set(index,'amount',e.target.value)} disabled={readOnly} required/>{clearance&&<FormField label={bilingualLabel("Evidence reference")} value={item.evidence} onChange={e=>set(index,'evidence',e.target.value)} disabled={readOnly} required/>}{!readOnly&&<Button onClick={()=>onChange(items.filter((_,i)=>i!==index))}>{t("Remove item")}</Button>}</div>)}{!readOnly&&<Button onClick={()=>onChange([...items,clearance?{description:'',amount:'',evidence:''}:{label:'',reason:'',type:'EARNING',amount:''}])}>{t("Add item")}</Button>}</fieldset>
}
function Discard({onKeep,onDiscard}){
 useLocale();return <Dialog title={bilingualLabel("Discard changes?")} onClose={onKeep}><p>{t("Your unsaved changes will be lost.")}</p><Button autoFocus onClick={onKeep}>{t("Keep editing")}</Button><Button onClick={onDiscard}>{t("Discard changes")}</Button></Dialog>}
function Details({row,employees=[],runs=[],purchases=[]}){
 useLocale();
 const spec=personnelFinanceKinds[row.kind]
 return <><dl className="catalog-details"><div><dt>{bilingualLabel("Employee")}</dt><dd>{employees.find(e=>e.id===row.employeeId)?.displayName||row.employeeId}</dd></div>{spec.fields.filter(f=>f[2]!=='items').map(([key,title,type])=><div key={key}><dt>{bilingualLabel(title)}</dt><dd>{type==='run'?runs.find(r=>r.id===row.payload[key])?.name||row.payload[key]:type==='purchase'?purchases.find(p=>p.id===row.payload[key])?.name||row.payload[key]:type==='employee-optional'?employees.find(e=>e.id===row.payload[key])?.displayName||t("No substitution"):row.payload[key]||t("Not set")}</dd></div>)}</dl>{row.kind==='PAYROLL'&&<><Items items={row.payload.items} readOnly/><p>{t("Net payable:")}{' '}{money(financialTotal(row.kind,row.payload))}</p></>}{row.payment&&<p>{t("Payment recorded:")}{' '}{row.payment.paidOn} · {row.payment.reference}</p>}{row.clearance&&<><Items items={row.clearance.items} readOnly clearance/><p>{t("Returned cash:")}{' '}{row.clearance.returnedAmount}{' '}{t("THB")}</p></>}</>
}
function Editor({kind,row,employees,runs,purchases,onClose,onSaved}){
 useLocale();
 const spec=personnelFinanceKinds[kind],initial=useRef({title:row.title||'',employeeId:row.employeeId||'',payload:row.payload||Object.fromEntries(spec.fields.map(([key,,type,options])=>[key,type==='items'?[]:type==='select'?options[0]:'']))})
 const [values,setValues]=useState(initial.current),[busy,setBusy]=useState(false),[error,setError]=useState(''),[errors,setErrors]=useState({}),[discard,setDiscard]=useState(false),id=useRef(row.id||crypto.randomUUID()),pending=useRef(false),form=useRef(null)
 const dirty=!row.readOnly&&JSON.stringify(values)!==JSON.stringify(initial.current);useUnsavedChanges(dirty)
 const close=()=>dirty?setDiscard(true):onClose()
 const set=(key,value)=>{setValues(v=>({...v,payload:{...v.payload,[key]:value}}));setErrors(e=>({...e,[key]:undefined}))}
 async function submit(e){e.preventDefault();if(pending.current)return;const checked=personnelFinanceErrors(kind,values);setErrors(checked);if(Object.keys(checked).length){setTimeout(()=>form.current?.querySelector('[aria-invalid="true"],.field-error')?.focus(),0);return}pending.current=true;setBusy(true);setError('');try{await api('/api/personnel-finance/save',{id:id.current,version:row.version||0,kind,...values});onSaved()}catch(e){setError(message(e))}finally{pending.current=false;setBusy(false)}}
 return <Dialog title={`${bilingualLabel(row.readOnly?'View':row.id?'Edit':'Add')} ${bilingualLabel(spec.title.toLowerCase())}`} busy={busy} onClose={close}>{row.readOnly?<><Details row={row} employees={employees} runs={runs} purchases={purchases}/><EvidenceAttachments targetKind="PERSONNEL_FINANCE" targetId={row.id}/><Button onClick={onClose}>{t("Close")}</Button></>:<form noValidate ref={form} onSubmit={submit}><FormField label={bilingualLabel("Record name")} value={values.title} onChange={e=>setValues({...values,title:e.target.value})} required maxLength={160} error={errors.title} disabled={busy}/><Lookup kind={kind} lookup="employees" label={bilingualLabel("Employee")} value={values.employeeId} selectedLabel={employees.find(e=>e.id===values.employeeId)?.displayName} onChange={e=>setValues({...values,employeeId:e.target.value})} error={errors.employeeId} disabled={busy}/>
 {spec.fields.map(([key,title,type,options])=>{const props={label:title,value:values.payload[key]||'',onChange:e=>set(key,e.target.value),error:errors[key],disabled:busy};return type==='items'?<Items key={key} items={values.payload[key]} onChange={value=>set(key,value)} readOnly={busy} error={errors[key]}/>:type==='date'?<DateField key={key} {...props} required/>:['employee-optional','run','purchase'].includes(type)?<div key={key}><Lookup {...props} kind={kind} lookup={type==='run'?'runs':type==='purchase'?'purchases':'employees'} selectedLabel={type==='run'?runs.find(r=>r.id===values.payload[key])?.name:type==='purchase'?purchases.find(p=>p.id===values.payload[key])?.name:employees.find(e=>e.id===values.payload[key])?.displayName}/>{type==='employee-optional'&&<Button disabled={busy} onClick={()=>set(key,'')}>{t("No substitution")}</Button>}</div>:type==='select'?<SelectField key={key} {...props}>{options.map(o=><option key={o} value={o}>{label(o)}</option>)}</SelectField>:<FormField key={key} {...props} inputMode={type==='money'?'decimal':undefined} required/>})}
 {kind==='PAYROLL'&&<p>{t("Net payable:")}{' '}{(()=>{try{return money(financialTotal(kind,values.payload))}catch{return 'Complete the base wage and item amounts.'}})()}</p>}{error&&<p role="alert">{t(error)}</p>}<div className="dialog-actions"><Button disabled={busy} onClick={close}>{t("Close")}</Button><Button type="submit" busy={busy} disabled={busy}>{t("Save draft")}</Button></div></form>}{discard&&<Discard onKeep={()=>setDiscard(false)} onDiscard={onClose}/>}</Dialog>
}
function Command({row,action,onClose,onSaved,employees,runs,purchases}){
 useLocale();
 const [note,setNote]=useState(''),[reference,setReference]=useState(''),[paidOn,setPaidOn]=useState(''),[items,setItems]=useState([]),[returned,setReturned]=useState('0'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[errors,setErrors]=useState({}),[discard,setDiscard]=useState(false),id=useRef(crypto.randomUUID()),pending=useRef(false),form=useRef(null)
 const dirty=Boolean(note||reference||paidOn||items.length||returned!=='0');useUnsavedChanges(dirty);const close=()=>dirty?setDiscard(true):onClose()
 async function submit(e){e.preventDefault();if(pending.current)return;const checked={};if(action==='PAY'){if(!paidOn)checked.paidOn='Enter the external payment date.';if(!reference.trim())checked.reference='Enter the external payment reference.'}if(action.includes('REJECT')&&!note.trim())checked.note='Explain why this record needs correction.';if(action==='CLEAR'){try{if(items.some(item=>!item.description.trim()||!item.evidence.trim())||items.reduce((n,item)=>n+cents(item.amount),0)+cents(returned)!==financialTotal(row.kind,row.payload))throw new Error()}catch{checked.items='Enter evidenced expenses and returned cash totaling the advance.'}}setErrors(checked);if(Object.keys(checked).length){setTimeout(()=>form.current?.querySelector('[aria-invalid="true"],.field-error')?.focus(),0);return}pending.current=true;setBusy(true);setError('');try{await api('/api/personnel-finance/command',{id:id.current,recordId:row.id,version:row.version,action,note,...(action==='PAY'?{paidOn,reference}:{}),...(action==='CLEAR'?{clearanceItems:items,returnedAmount:returned}:{})});onSaved()}catch(e){setError(message(e))}finally{pending.current=false;setBusy(false)}}
 return <Dialog title={action==='PAY'?bilingualLabel('Record external payment'):label(action)} busy={busy} onClose={close}><form noValidate ref={form} onSubmit={submit}><p>{row.title} · {label(row.status)}</p><Details row={row} employees={employees} runs={runs} purchases={purchases}/>{!['EMPLOYMENT','ATTENDANCE'].includes(row.kind)&&<p>{t("Amount:")}{' '}{money(financialTotal(row.kind,row.payload))}</p>}<p>{action==='APPROVE'?t('Confirm that you reviewed these details and supporting evidence.'):action==='PAY'?t('Use the reference from an already completed external payment. This action records payment only.'):t('Confirm this action for the displayed revision.')}</p>{action==='PAY'&&<><DateField label={bilingualLabel("Payment date")} error={errors.paidOn} value={paidOn} onChange={e=>setPaidOn(e.target.value)} required disabled={busy}/><FormField label={bilingualLabel("Payment reference")} error={errors.reference} value={reference} onChange={e=>setReference(e.target.value)} required disabled={busy}/></>}{action==='CLEAR'&&<><Items items={items} onChange={setItems} error={errors.items} clearance readOnly={busy}/><FormField label={bilingualLabel("Cash returned (THB)")} value={returned} onChange={e=>setReturned(e.target.value)} required disabled={busy}/></>}<FormField label={bilingualLabel("Review note")} error={errors.note} value={note} onChange={e=>setNote(e.target.value)} required={action.includes('REJECT')} disabled={busy}/>{error&&<p role="alert">{t(error)}</p>}<div className="dialog-actions"><Button disabled={busy} onClick={close}>{t("Cancel")}</Button><Button type="submit" busy={busy} disabled={busy}>{action==='PAY'?t('Record payment'):label(action)}</Button></div></form>{discard&&<Discard onKeep={()=>setDiscard(false)} onDiscard={onClose}/>}</Dialog>
}