import {translateLabel as bilingualLabel} from '../../core/i18n/runtime.js'
import { formatNumber } from '../../core/i18n/runtime.js'
import { translate as t, useLocale } from '../../core/i18n/locale.jsx'
import {RefreshButton} from '../../core/ui/RefreshButton.jsx'
import BillSignatures from './BillSignatures.jsx'
import {Dropdown} from '../../core/ui/Dropdown.jsx'
import {useEffect,useRef,useState} from 'react'
import {api} from '../../core/auth/api.js'
import {Button} from '../../core/ui/Button.jsx'
import {Dialog} from '../../core/ui/Dialog.jsx'
import {FormField} from '../../core/ui/FormField.jsx'
import {DateField} from '../../core/ui/DateField.jsx'
import {DataTable} from '../../core/ui/DataTable.jsx'
import {Pagination} from '../../core/ui/Pagination.jsx'
import {SearchField} from '../../core/ui/SearchField.jsx'
import {useUnsavedChanges} from '../../core/navigation/Navigation.jsx'
import EvidenceAttachments from './EvidenceAttachments.jsx'
const money=n=>formatNumber(Number(n), {style:'currency',currency:'THB'})
const messages={BOOKINGS_NOT_BILLABLE:'Choose completed Agent credit bookings for the same Agent.',BOOKINGS_ALREADY_BILLED:'A selected booking has already been billed. Refresh and select again.',PAYMENT_EXCEEDS_BALANCE:'The payment exceeds the current outstanding balance.',RECORD_CONFLICT:'This statement changed. Close and reopen it before recording another action.',PERMISSION_DENIED:'You no longer have permission to access these records.',INVALID_AMOUNT:'Enter a positive amount with up to two decimal places.',PAYMENT_DATE_IN_FUTURE:'The payment date cannot be in the future.'}
const message=e=>messages[e.message]||'Unable to confirm the action. Your entries are retained. Check them and retry.'
export default function ReceivablesPage(){
 useLocale();
 const [data,setData]=useState({rows:[],loading:true}),[page,setPage]=useState(1),[q,setQ]=useState(''),[composing,setComposing]=useState(false),[attempt,setAttempt]=useState(0),[create,setCreate]=useState(false),[view,setView]=useState(null),[notice,setNotice]=useState('')
 useEffect(()=>{if(composing)return;const c=new AbortController(),timer=setTimeout(()=>{setData(d=>({...d,loading:true}));api(`/api/receivables?${new URLSearchParams({page,q})}`,undefined,{signal:c.signal}).then(d=>{if(!c.signal.aborted)setData({...d,loading:false})}).catch(e=>{if(!c.signal.aborted)setData({rows:[],loading:false,error:message(e)})})},q?300:0);return()=>{clearTimeout(timer);c.abort()}},[page,q,composing,attempt])
 return <><div className="page-heading"><div><span className="eyebrow">{bilingualLabel("ACCOUNTS & FINANCE")}</span><h1>{bilingualLabel("Agent receivables")}</h1><p>{t("Internal billing statements and payments received. The company issues receipts and tax invoices separately.")}</p></div><Button onClick={()=>setCreate(true)}>{t("Create internal statement")}</Button></div>{notice&&<p role="status">{t(notice)}</p>}<section className="panel table-panel"><div className="filterbar"><SearchField label={bilingualLabel("Search statements")} value={q} onChange={v=>{setQ(v);setPage(1)}} onCompositionChange={setComposing}/><RefreshButton disabled={data.loading} onClick={()=>setAttempt(n=>n+1)}/></div><DataTable columns={['Statement','Agent','Total','Received','Outstanding','Status','Actions']} busy={data.loading} error={data.error} onRetry={()=>setAttempt(n=>n+1)} isEmpty={!data.rows.length}>{data.rows.map(row=><tr key={row.id}><td>{row.title}<div>{t("Due")}{' '}{row.dueOn.slice(0,10)}</div></td><td>{row.agentName}</td><td>{money(row.total)}</td><td>{money(row.paid)}</td><td>{row.status==='VOID'?'—':money(Number(row.total)-Number(row.paid))}</td><td>{t(row.status)}</td><td><Dropdown rowActions label={bilingualLabel("Actions for {value0}", {value0: row.title})} items={[{label:'View statement',icon:'view',onSelect:()=>setView(row.id)}]}/></td></tr>)}</DataTable><Pagination page={data.page||page} total={data.total} busy={data.loading} onPageChange={setPage}/></section>{create&&<Create onClose={()=>setCreate(false)} onSaved={()=>{setCreate(false);setNotice('Internal statement created.');setAttempt(n=>n+1)}}/>}{view&&<Statement id={view} onClose={()=>{setView(null);setAttempt(n=>n+1)}}/>}</>
}
function Create({onClose,onSaved}){
 useLocale();
 const [data,setData]=useState({rows:[],loading:true}),[page,setPage]=useState(1),[attempt,setAttempt]=useState(0),[selected,setSelected]=useState([]),[title,setTitle]=useState(''),[dueOn,setDue]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[discard,setDiscard]=useState(false)
 const id=useRef(crypto.randomUUID()),lock=useRef(false),form=useRef(null);const dirty=Boolean(selected.length||title||dueOn);useUnsavedChanges(dirty)
 useEffect(()=>{const c=new AbortController();api(`/api/receivables?eligible=true&page=${page}`,undefined,{signal:c.signal}).then(d=>{if(!c.signal.aborted)setData({...d,loading:false})}).catch(e=>{if(!c.signal.aborted)setData({rows:[],loading:false,error:message(e)})});return()=>c.abort()},[page,attempt])
 const changed=()=>{id.current=crypto.randomUUID();setError('')}
 async function submit(e){e.preventDefault();if(lock.current)return;if(!selected.length||!title.trim()||!dueOn){setError('Enter a statement name, due date and select at least one booking.');form.current?.querySelector('input')?.focus();return}lock.current=true;setBusy(true);setError('');try{await api('/api/receivables',{id:id.current,action:'CREATE',title,dueOn,bookingIds:selected.map(b=>b.id)});onSaved()}catch(e){setError(message(e))}finally{lock.current=false;setBusy(false)}}
 const close=()=>dirty?setDiscard(true):onClose()
 return <Dialog title={bilingualLabel("Create internal billing statement")} busy={busy} onClose={close}><form noValidate ref={form} onSubmit={submit}><p>{t("Select completed bookings with Agent credit terms for one Agent, up to 50 per statement. Each booking can belong to one active statement.")}</p><FormField label={bilingualLabel("Statement name")} maxLength={160} value={title} required disabled={busy} onChange={e=>{changed();setTitle(e.target.value)}}/><DateField label={bilingualLabel("Due date")} value={dueOn} required disabled={busy} onChange={e=>{changed();setDue(e.target.value)}}/><p role="status">{t("Selected")}{' '}{selected.length} · {money(selected.reduce((n,b)=>n+Number(b.total),0))} · {selected[0]?.agentName||t("Choose an Agent booking")}</p><DataTable columns={['Select','Booking','Agent','Amount']} empty={<><h3>{bilingualLabel("No eligible bookings")}</h3><p>{t("Completed Agent-credit bookings appear here when they have not already been billed.")}</p></>} busy={data.loading} error={data.error} onRetry={()=>setAttempt(n=>n+1)} isEmpty={!data.rows.length}>{data.rows.map(row=><tr key={row.id}><td><input type="checkbox" aria-label={t("Select {value0}", {value0: row.code})} checked={selected.some(b=>b.id===row.id)} disabled={busy||!row.total||Number(row.total)<=0||Boolean(selected.length&&selected[0].agentId!==row.agentId)||selected.length>=50&&!selected.some(b=>b.id===row.id)} onChange={e=>{changed();setSelected(s=>e.target.checked?[...s,row]:s.filter(b=>b.id!==row.id))}}/></td><td>{row.code} · {row.name}</td><td>{row.agentName}</td><td>{row.total===null?t('Price unavailable'):money(row.total)}</td></tr>)}</DataTable><Pagination page={data.page||page} total={data.total} busy={data.loading||busy} onPageChange={p=>{setData(d=>({...d,loading:true}));setPage(p)}}/>{error&&<p role="alert">{t(error)}</p>}<p>{t("This creates an internal statement. Check the selected bookings and total before saving.")}</p><div className="dialog-actions"><Button disabled={busy} onClick={close}>{t("Cancel")}</Button><Button type="submit" disabled={busy} busy={busy}>{t("Create internal statement")}</Button></div></form>{discard&&<Discard onKeep={()=>setDiscard(false)} onDiscard={onClose}/>}</Dialog>
}
function Discard({onKeep,onDiscard}){
 useLocale();return <Dialog title={bilingualLabel("Discard changes?")} onClose={onKeep}><p>{t("Your unsaved entries will be lost.")}</p><Button autoFocus onClick={onKeep}>{t("Keep editing")}</Button><Button onClick={onDiscard}>{t("Discard changes")}</Button></Dialog>}
function Statement({id,onClose}){
 useLocale();
 const [data,setData]=useState({loading:true}),[page,setPage]=useState(1),[attempt,setAttempt]=useState(0),[action,setAction]=useState(null),[evidence,setEvidence]=useState(null)
 useEffect(()=>{const c=new AbortController();api(`/api/receivables?id=${id}&page=${page}`,undefined,{signal:c.signal}).then(d=>{if(!c.signal.aborted)setData({...d,loading:false})}).catch(e=>{if(!c.signal.aborted)setData({loading:false,error:message(e)})});return()=>c.abort()},[id,page,attempt])
 const row=data.row
 return <Dialog title={row?.title||bilingualLabel("Internal statement")} onClose={onClose}>{data.loading?<p role="status">{t("Loading statement…")}</p>:data.error?<><p role="alert">{t(data.error)}</p><Button onClick={()=>setAttempt(n=>n+1)}>{t("Retry")}</Button></>:<><p>{t("INTERNAL STATEMENT ·")}{' '}{row.agentName} · {t(row.status)}</p><p>{t("Total")}{' '}{money(row.total)}{' '}{t("· Received")}{' '}{money(row.paid)}{' '}{t("· Outstanding")}{' '}{row.status==='VOID'?'—':money(Number(row.total)-Number(row.paid))}</p><p>{t("Due")}{' '}{row.dueOn.slice(0,10)}</p><DataTable columns={['Booking','Amount']} isEmpty={!row.snapshot.length}>{row.snapshot.map(b=><tr key={b.bookingId}><td>{b.code} · {b.name}</td><td>{money(b.total)}</td></tr>)}</DataTable>{row.status==='OPEN'&&<div className="dialog-actions"><Button onClick={()=>setAction('PAY')}>{t("Record received payment")}</Button>{Number(row.paid)===0&&<Button onClick={()=>setAction('VOID')}>{t("Void unpaid statement")}</Button>}</div>}<BillSignatures row={row} signatures={data.signatures} documentHash={data.documentHash} onSaved={()=>{setData({loading:true});setAttempt(n=>n+1)}}/><h2>{bilingualLabel("Received payments")}</h2><DataTable columns={['Date','Reference','Amount','Actions']} isEmpty={!data.payments.length}>{data.payments.map(p=><tr key={p.id}><td>{p.receivedOn.slice(0,10)}</td><td>{p.reference}</td><td>{money(p.amount)}</td><td><Dropdown rowActions label={bilingualLabel("Actions for {value0}", {value0: p.reference})} items={[{label:'Supporting documents',icon:'view',onSelect:()=>setEvidence(p)}]}/></td></tr>)}</DataTable><Pagination page={data.page} total={data.total} onPageChange={p=>{setData(d=>({...d,loading:true}));setPage(p)}}/><EvidenceAttachments targetKind="AGENT_BILL" targetId={id}/></>}{action&&<Payment row={row} action={action} onClose={()=>setAction(null)} onSaved={()=>{setAction(null);setData({loading:true});setAttempt(n=>n+1)}}/>}{evidence&&<Dialog title={bilingualLabel("Payment documents · {value0}", {value0: evidence.reference})} onClose={()=>setEvidence(null)}><EvidenceAttachments targetKind="AGENT_PAYMENT" targetId={evidence.id}/></Dialog>}</Dialog>
}
function Payment({row,action,onClose,onSaved}){
 useLocale();
 const [amount,setAmount]=useState(''),[receivedOn,setDate]=useState(''),[reference,setReference]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[discard,setDiscard]=useState(false)
 const id=useRef(crypto.randomUUID()),lock=useRef(false),form=useRef(null);const dirty=Boolean(amount||receivedOn||reference||reason);useUnsavedChanges(dirty)
 const changed=()=>{id.current=crypto.randomUUID();setError('')},close=()=>dirty?setDiscard(true):onClose()
 async function submit(e){e.preventDefault();if(lock.current)return;if(action==='PAY'?(!amount||!receivedOn||!reference.trim()):!reason.trim()){setError('Complete all required fields.');form.current?.querySelector('input')?.focus();return}lock.current=true;setBusy(true);setError('');try{await api('/api/receivables',{id:id.current,billId:row.id,version:row.version,action,...(action==='PAY'?{amount,receivedOn,reference}:{reason})});onSaved()}catch(e){setError(message(e))}finally{lock.current=false;setBusy(false)}}
 return <Dialog title={action==='PAY'?bilingualLabel('Record received payment'):bilingualLabel('Void unpaid statement?')} busy={busy} onClose={close}><form ref={form} noValidate onSubmit={submit}><p>{row.title} · {row.agentName}{' '}{t("· Outstanding")}{' '}{money(Number(row.total)-Number(row.paid))}</p>{action==='PAY'?<><p>{t("Record money already received outside the system. Verify the amount and reference before saving; this entry becomes part of the payment history.")}</p><FormField label={bilingualLabel("Received amount (THB)")} placeholder={t("e.g. 2000.00")} inputMode="decimal" required disabled={busy} value={amount} onChange={e=>{changed();setAmount(e.target.value)}}/><DateField label={bilingualLabel("Received date")} required disabled={busy} value={receivedOn} onChange={e=>{changed();setDate(e.target.value)}}/><FormField label={bilingualLabel("Payment reference")} required maxLength={300} disabled={busy} value={reference} onChange={e=>{changed();setReference(e.target.value)}}/></>:<><p>{t("The unpaid statement is voided and its bookings become available for another statement. The original statement stays in history.")}</p><FormField label={bilingualLabel("Reason for voiding")} required maxLength={1000} value={reason} disabled={busy} onChange={e=>{changed();setReason(e.target.value)}}/></>}{error&&<p role="alert">{t(error)}</p>}<div className="dialog-actions"><Button autoFocus disabled={busy} onClick={close}>{t("Cancel")}</Button><Button type="submit" busy={busy} disabled={busy}>{action==='PAY'?t('Record received payment'):t('Void statement')}</Button></div></form>{discard&&<Discard onKeep={()=>setDiscard(false)} onDiscard={onClose}/>}</Dialog>
}
