import {useLocale} from '../../../core/i18n/locale.jsx'
import {translateLabel as label,formatNumber} from '../../../core/i18n/runtime.js'
import {DataTable} from '../../../core/ui/DataTable.jsx'
import {Panel,Stat,Bars} from './ReferenceDashboard.jsx'
export function BookingDashboard({data,persona,onSelect}){
 const {t}=useLocale(),overview=data.bookingOverview,manager=persona==='booking-manager'
 if(!overview)return <section className="panel dashboard-state" role="status"><p>{t('Booking overview is unavailable. Refresh your account to check your access.')}</p></section>
 const {calendar30,work,team,rows}=overview
 return <div className="reference-dashboard-content"><div className="reference-stat-grid"><Stat title="Customers (today)" value={calendar30[0]?.pax} icon="users" detail="Confirmed and completed arrivals"/><Stat title="Customers (next 30 days)" value={calendar30.reduce((n,d)=>n+d.pax,0)} icon="users" detail="Confirmed and completed arrivals"/><Stat title={manager?'Team bookings (next 30 days)':'My bookings (next 30 days)'} value={work.total} icon="calendar" detail="All statuses"/><Stat title="Draft bookings to follow up" value={work.draft} tone="orange" icon="calendar" detail={manager?'All Booking Assistants':'Assigned to me'}/></div><Panel title="Customers next 30 days" icon="users" href="/operations/bookings"><Bars days={calendar30} onSelect={onSelect}/><p className="reference-range">{overview.from} – {overview.through} · {t('Select a bar for tour program totals.')}</p></Panel><div className="reference-main-grid"><Panel title={manager?'Team booking work':'My booking work'} icon="calendar" href="/operations/bookings"><p>{t(manager?'Review all assistants and assign the responsible person from Bookings.':'You can see all bookings. Changes are limited to bookings assigned to you.')}</p><DataTable columns={['Booking no.','Tour program','Responsible person','Guests','Status']} label={label('Booking work')} layout="content" isEmpty={!rows.length}>{rows.map(row=><tr key={row.id}><td>{row.code}</td><td>{row.program||'—'}</td><td>{row.owner||t('Unassigned')}</td><td>{formatNumber(row.pax)}</td><td>{t(row.status)}</td></tr>)}</DataTable><p className="reference-range">{t('Up to 10 open bookings shown. Open Bookings for the complete list.')}</p></Panel>{manager?<Panel title="Booking team overview" icon="users"><DataTable columns={['Responsible person','Total bookings','Draft','Confirmed','Completed']} label={label('Booking team overview')} layout="content" isEmpty={!team.length}>{team.map(row=><tr key={row.id||'unassigned'}><td>{row.name||t('Unassigned')}</td><td>{formatNumber(row.total)}</td><td>{formatNumber(row.draft)}</td><td>{formatNumber(row.confirmed)}</td><td>{formatNumber(row.completed)}</td></tr>)}</DataTable></Panel>:<Panel title="Booking commission" icon="briefcase"><p>{t('No commission applies when either the agent or tour program excludes Booking commission.')}</p><p>{t('Each booking keeps its saved commission conditions. Open the booking to review them.')}</p><a href="/manuals/BOOKING">{t('User guides')}</a></Panel>}</div></div>
}
